/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface ABActiveTextRanges : NSObject
{
    NSArray *links;
    NSArray *hashtags;
    NSArray *usernames;
    NSArray *lists;
    NSArray *stockSymbols;
    NSArray *emailAddresses;
    NSArray *activeRanges;
}

- (id)initWithString:(id)arg1;
- (void)dealloc;
@property(readonly, nonatomic) NSArray *activeRanges;
@property(readonly, nonatomic) NSArray *emailAddresses; // @synthesize emailAddresses;
@property(readonly, nonatomic) NSArray *stockSymbols; // @synthesize stockSymbols;
@property(readonly, nonatomic) NSArray *lists; // @synthesize lists;
@property(readonly, nonatomic) NSArray *usernames; // @synthesize usernames;
@property(readonly, nonatomic) NSArray *hashtags; // @synthesize hashtags;
@property(readonly, nonatomic) NSArray *links; // @synthesize links;

@end

