/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIPopoverController.h"

@class ABAutocompleteTableView, UITextView;

@interface ABAutocompletePopover : UIPopoverController
{
    UITextView *textView;
    BOOL autocompleting;
}

- (id)init;
@property(readonly, nonatomic) ABAutocompleteTableView *tableView;
- (BOOL)updateAutocomplete;
- (BOOL)endAutocomplete;
@property(nonatomic) UITextView *textView; // @synthesize textView;

@end

