/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABColumnBar, NSArray, NSString, UIButton, UIView, UIViewController;

@interface ABColumnItem : NSObject
{
    NSString *title;
    UIView *_titleView;
    UIView *_backButtonView;
    NSArray *_toolbarItems;
    ABColumnBar *_columnBar;
    UIViewController *_owner;
}

- (void)dealloc;
@property(retain, nonatomic) UIView *titleView;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(readonly, nonatomic) UIButton *backButtonView;
- (void)setToolbarItems:(id)arg1 animated:(BOOL)arg2;
- (id)toolbarItems;

@end

