/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABImage.h"

@class UIImage;

@interface ABConcreteImage : ABImage
{
    UIImage *uiImage;
    struct CGImage *CGImage;
}

- (id)init;
- (id)initWithUIImage:(id)arg1;
- (id)initWithCGImage:(struct CGImage *)arg1;
- (void)dealloc;
- (struct CGSize)size;
- (struct CGImage *)CGImage;
- (id)uiImage;
- (void)drawInContext:(struct CGContext *)arg1 inRect:(struct CGRect)arg2 flipped:(BOOL)arg3;
- (void)drawInContext:(struct CGContext *)arg1 inRect:(struct CGRect)arg2;

@end

