/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABColumnItem.h"

@interface ABColumnItem (ABColumnBarAdditions)
- (void)_setColumnBar:(id)arg1;
@end

