/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"

@class NSArray, NSString, UINavigationController;

@interface ABEmailComposer : NSObject <MFMailComposeViewControllerDelegate>
{
    NSArray *toRecipients;
    NSString *body;
    NSString *subject;
    BOOL isHTML;
    UINavigationController *sourceNavigationController;
}

+ (id)composer;
- (void)dealloc;
- (id)presentableViewController;
- (void)showFrom:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
@property(nonatomic) BOOL isHTML; // @synthesize isHTML;
@property(copy, nonatomic) NSString *subject; // @synthesize subject;
@property(copy, nonatomic) NSString *body; // @synthesize body;
@property(copy, nonatomic) NSArray *toRecipients; // @synthesize toRecipients;

@end

