/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface ABGPS : NSObject
{
}

+ (void)startMonitoringSignificantLocationChanges;
+ (void)stopMonitoringSignificantLocationChanges;
+ (id)lastSignificantLocation;
+ (id)callbacks;
+ (void)broadcast:(id)arg1;
+ (void)_startup;
+ (void)_shutdown;
+ (void)watchdog:(id)arg1;
+ (void)sleep;
+ (void)wake;
+ (id)beginGPSUpdates:(id)arg1;
+ (void)endGPSUpdates:(id)arg1;
+ (void)cancelGeocoder;
+ (void)reverseGeocoder:(id)arg1 didFindPlacemark:(id)arg2;
+ (void)reverseGeocoder:(id)arg1 didFailWithError:(id)arg2;
+ (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
+ (BOOL)locationUpdatesAreProbablyDisabled;
+ (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;

@end

