/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class UIColor;

@interface ABGradientView : UIView
{
    UIColor *a;
    UIColor *b;
}

- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) UIColor *b; // @synthesize b;
@property(retain, nonatomic) UIColor *a; // @synthesize a;

@end

