/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABRowView.h"

@class UIView;

@interface ABGroupedRowView : ABRowView
{
    UIView *container;
}

- (float)xOffset;
- (float)childWidth:(float)arg1;
- (id)childContainer;

@end

