/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class ABCallback, ABHTTPMultipartFormData, ABMutableMultiDictionary, NSData, NSDictionary, NSError, NSInputStream, NSMutableData, NSString, NSURL, NSURLConnection;

@interface ABHTTPRequest : NSObject <NSCoding>
{
    NSURL *url;
    NSURL *finalURL;
    NSString *method;
    NSData *body;
    NSInputStream *bodyStream;
    ABMutableMultiDictionary *headers;
    ABHTTPMultipartFormData *multipartFormData;
    NSString *username;
    NSString *password;
    NSString *oAuthConsumerKey;
    NSString *oAuthConsumerSecret;
    NSString *oAuthToken;
    NSString *oAuthTokenSecret;
    long connectionTimeout;
    int maxRetries;
    int retries;
    int autoRetries;
    ABCallback *responseCallback;
    ABCallback *progressCallback;
    ABCallback *chunkCallback;
    int statusCode;
    NSMutableData *_data;
    NSError *error;
    NSDictionary *responseHeaders;
    long long downloadContentLength;
    long long downloadedBytes;
    long long uploadContentLength;
    long long uploadedBytes;
    unsigned int _flags;
    int streamingState;
    int streamingBytesLeft;
    NSMutableData *streamingBuffer;
    NSURLConnection *connection;
    double startTime;
    int networkStatus;
}

+ (id)request;
- (id)init;
@property(readonly, nonatomic) NSURL *finalURL;
- (void)cancel;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)addValue:(id)arg1 forHTTPHeaderField:(id)arg2;
- (void)setValue:(id)arg1 forHTTPHeaderField:(id)arg2;
@property(retain, nonatomic) ABHTTPMultipartFormData *multipartFormData;
@property(copy, nonatomic) NSData *data;
@property(readonly, nonatomic) double downloadProgress;
@property(readonly, nonatomic) double uploadProgress;
- (void)startRequest;
- (void)endRequest;
- (void)noteProgress;
@property(readonly, nonatomic) int networkStatus; // @synthesize networkStatus;
@property(readonly, nonatomic) double startTime; // @synthesize startTime;
@property(retain, nonatomic) NSDictionary *responseHeaders; // @synthesize responseHeaders;
@property(readonly, nonatomic) ABMutableMultiDictionary *headers; // @synthesize headers;
@property(nonatomic) int statusCode; // @synthesize statusCode;
@property(copy, nonatomic) NSError *error; // @synthesize error;
@property(nonatomic) int maxRetries; // @synthesize maxRetries;
@property(nonatomic) long connectionTimeout; // @synthesize connectionTimeout;
@property(retain, nonatomic) ABCallback *chunkCallback; // @synthesize chunkCallback;
@property(retain, nonatomic) ABCallback *progressCallback; // @synthesize progressCallback;
@property(retain, nonatomic) ABCallback *responseCallback; // @synthesize responseCallback;
@property(retain, nonatomic) NSString *oAuthTokenSecret; // @synthesize oAuthTokenSecret;
@property(retain, nonatomic) NSString *oAuthToken; // @synthesize oAuthToken;
@property(retain, nonatomic) NSString *oAuthConsumerSecret; // @synthesize oAuthConsumerSecret;
@property(retain, nonatomic) NSString *oAuthConsumerKey; // @synthesize oAuthConsumerKey;
@property(retain, nonatomic) NSString *password; // @synthesize password;
@property(retain, nonatomic) NSString *username; // @synthesize username;
@property(retain, nonatomic) NSInputStream *bodyStream; // @synthesize bodyStream;
@property(copy, nonatomic) NSData *body; // @synthesize body;
@property(copy, nonatomic) NSString *method; // @synthesize method;
@property(copy, nonatomic) NSURL *url; // @synthesize url;

@end

