/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSMutableArray, NSString;

@interface ABHTTPMultipartFormData : NSObject <NSCoding>
{
    NSMutableArray *parts;
    NSString *dataFile;
    int dataLength;
}

- (id)init;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)addDataPart:(id)arg1 name:(id)arg2;
- (void)addTextPart:(id)arg1 name:(id)arg2;
- (void)addImageFile:(id)arg1 name:(id)arg2;
- (void)addVideoFile:(id)arg1 name:(id)arg2;
- (id)boundary;
- (id)contentTypeHeader;
- (void)_writeData:(id)arg1 toFileHandle:(id)arg2;
- (id)dataInputStream;
- (int)dataInputLength;
- (void)cleanup;

@end

