/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABHTTPRequest.h"

@interface ABHTTPRequest (Streams)
+ (id)keepAliveData;
- (BOOL)startStreamChunk:(id)arg1;
- (void)processStreamChunk:(id)arg1;
- (void)didRecieveChunk:(id)arg1;
@end

