/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABHTTPRequest.h"

@interface ABHTTPRequest (Additions)
+ (void)beginNetworkActivity;
+ (void)endNetworkActivity;
+ (id)persistentRequests;
+ (void)savePersistentRequests;
+ (void)addPersistentRequest:(id)arg1;
+ (void)removePersistentRequest:(id)arg1;
+ (void)servicePersistentRequests;
- (BOOL)isPersistent;
- (void)_didStartRequest;
- (void)_didEndRequest;
@end

