/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class UIImage;

@interface ABImage : NSObject
{
}

+ (id)imageNamed:(id)arg1;
+ (id)imageWithData:(id)arg1;
+ (id)imageWithCGImage:(struct CGImage *)arg1;
+ (id)imageWithUIImage:(id)arg1;
@property(readonly, nonatomic) struct CGSize size;
@property(readonly, nonatomic) struct CGImage *CGImage;
@property(readonly, nonatomic) UIImage *uiImage;
- (id)imageData;
- (id)stretchableImageWithLeftCapWidth:(int)arg1 topCapHeight:(int)arg2;
- (int)leftCapWidth;
- (int)topCapHeight;
- (void)drawInContext:(struct CGContext *)arg1 inRect:(struct CGRect)arg2 flipped:(BOOL)arg3;
- (void)drawInContext:(struct CGContext *)arg1 inRect:(struct CGRect)arg2;

@end

