/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDateFormatter, NSMutableArray, NSNumber, NSString;

@interface ABJSONParser : NSObject
{
    NSMutableArray *callbacks;
    BOOL canPushCallback;
    BOOL didPushCallback;
    NSString *key;
    int type;
    id value;
    NSDateFormatter *jsonTwitterDateFormatter;
    NSDateFormatter *httpLikeDateFormatter;
}

+ (id)parseDataToPrimitives:(id)arg1;
+ (id)handleJSONObject:(id)arg1;
+ (void)parseArray:(id)arg1 info:(id)arg2;
+ (void)parseDictionary:(id)arg1 info:(id)arg2;
+ (void)parseToPrimitive:(id)arg1 info:(id)arg2;
+ (id)parseData:(id)arg1 withCallback:(id)arg2;
- (id)init;
- (void)dealloc;
- (void)_triggerDelegate;
- (void)ignoreTag;
- (void)pushCallback:(id)arg1 repeatElement:(BOOL)arg2;
- (void)_copyTopCallback;
- (void)_popCallback;
- (id)parseData:(id)arg1 withCallback:(id)arg2;
@property(readonly, nonatomic) NSString *stringValue;
@property(readonly, nonatomic) NSNumber *boolValue;
- (id)numberValue;
- (id)jsonTwitterDate;
- (id)httpLikeDate;
@property(nonatomic) BOOL didPushCallback; // @synthesize didPushCallback;
@property(nonatomic) BOOL canPushCallback; // @synthesize canPushCallback;
@property(nonatomic) id value; // @synthesize value;
@property(nonatomic) int type; // @synthesize type;
@property(copy, nonatomic) NSString *key; // @synthesize key;

@end

