/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface ABKeychain : NSObject
{
}

+ (id)setPassword:(id)arg1 forUsername:(id)arg2 serviceName:(id)arg3;
+ (id)passwordForUsername:(id)arg1 serviceName:(id)arg2 error:(id *)arg3;

@end

