/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class ABCallback, CLLocation, CLLocationManager, NSDate, NSError;

@interface ABLocation : NSObject <CLLocationManagerDelegate>
{
    ABCallback *callback;
    CLLocationManager *locationManager;
    CLLocation *location;
    NSError *error;
    NSDate *startLocatingDate;
}

- (void)dealloc;
- (void)requestCurrentLocation;
- (void)invokeCallback;
- (void)locationTimeout:(id)arg1;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
@property(retain, nonatomic) NSError *error; // @synthesize error;
@property(retain, nonatomic) CLLocation *location; // @synthesize location;
@property(retain, nonatomic) ABCallback *callback; // @synthesize callback;

@end

