/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "ABUITextRendererDelegate-Protocol.h"

@class NSArray, NSAttributedString, NSMutableArray, NSMutableAttributedString;

@interface ABMarkupText : NSObject <ABUITextRendererDelegate>
{
    NSMutableAttributedString *_attributedString;
    NSMutableArray *_attributesStack;
    NSMutableArray *_activeRanges;
    struct _NSRange _currentRange;
    BOOL inActiveRange;
    int activeRangeTagDepth;
    int tagDepth;
}

- (void)dealloc;
@property(readonly, nonatomic) NSAttributedString *attributedString;
@property(readonly, nonatomic) NSArray *activeRanges;
- (struct _NSRange)rangeOfHREF:(id)arg1;
- (id)activeRangesOffsetBy:(int)arg1;
- (id)activeRangesForTextRenderer:(id)arg1;
- (id)currentAttribute:(id)arg1;
- (void)startElement:(id)arg1 attributes:(id)arg2;
- (void)endElement:(id)arg1;
- (void)characters:(id)arg1;
- (void)error:(id)arg1;
- (void)parseString:(id)arg1;
- (id)initWithMarkup:(id)arg1;

@end

