/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIScrollView.h"

@interface ABNetworkImageDisplayControllerScrollView : UIScrollView
{
    id networkImageDelegate;
}

- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
@property(nonatomic) id networkImageDelegate; // @synthesize networkImageDelegate;

@end

