/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIImageView.h"

@interface ABNetworkImageView : UIImageView
{
    id <ABNetworkImageViewDelegate> delegate;
}

- (id)initWithPlaceholderImage:(id)arg1 forImageURL:(id)arg2;
- (void)dealloc;
- (void)errorLoadingImage:(id)arg1;
- (void)imageResponse:(id)arg1 info:(id)arg2;
- (void)progress:(id)arg1 info:(id)arg2;
@property(nonatomic) id <ABNetworkImageViewDelegate> delegate; // @synthesize delegate;

@end

