/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@interface AboutSettingsViewController : ABStaticTableViewController
{
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)loadTableView;
- (void)tos:(id)arg1;
- (void)privacy:(id)arg1;
- (void)viewUser:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;

@end

