/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABRowView.h"

@class NSString, UIColor;

@interface ABPlainRowCell : ABRowView
{
    NSString *text;
    NSString *altText;
    int style;
    UIColor *textColor;
}

- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) NSString *text; // @synthesize text;
- (id)textFont;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor;
@property(nonatomic) int style; // @synthesize style;
@property(retain, nonatomic) NSString *altText; // @synthesize altText;

@end

