/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class UIImageView, UISearchDisplayController, UITableView;

@interface ABSearchableTableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchDisplayDelegate, UISearchBarDelegate>
{
    UITableView *_tableView;
    UIImageView *_tableHeader;
    UISearchDisplayController *searchDisplayController;
    BOOL activateSearchDisplayImmediately;
}

- (void)dealloc;
- (id)placeholderSearchStringForFilterBar;
- (id)appropriateSearchDisplayContentsController;
- (void)loadView;
- (void)viewDidUnload;
- (id)searchField;
- (void)viewWillAppear:(BOOL)arg1;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (BOOL)isSearchTableView:(id)arg1;
- (BOOL)searchDisplayIsActive;
@property(readonly, nonatomic) UISearchDisplayController *searchDisplayController;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)searchDisplayControllerDidBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)searchDisplayControllerDidEndSearch:(id)arg1;
- (void)searchDisplayController:(id)arg1 didLoadSearchResultsTableView:(id)arg2;
@property(readonly, nonatomic) UITableView *tableView;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
@property(nonatomic) BOOL activateSearchDisplayImmediately; // @synthesize activateSearchDisplayImmediately;

@end

