/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABSimpleSearchViewController.h"

@class NSMutableArray;

@interface ABSimplePersistentRecentSearchViewController : ABSimpleSearchViewController
{
    NSMutableArray *recentSearches;
}

- (id)defaultsKey;
- (id)recentSearches;
- (id)recentsMatching:(id)arg1;
- (void)saveRecent:(id)arg1;
- (BOOL)removeRecent:(id)arg1;

@end

