/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class ABCallback, NSString, UINavigationController, UITextField;

@interface ABSingleTextFieldViewController : ABStaticTableViewController <UITextFieldDelegate>
{
    BOOL modal;
    BOOL didChange;
    NSString *text;
    NSString *placeholderText;
    UITextField *textField;
    NSString *footerText;
    UINavigationController *navigationController;
    ABCallback *callback;
}

+ (id)showSingleTextFieldWithText:(id)arg1 placeholder:(id)arg2 title:(id)arg3 fromNavigationController:(id)arg4 modal:(BOOL)arg5 callback:(id)arg6;
- (void)_present;
- (void)_dismiss;
- (void)dealloc;
- (void)loadTableView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (BOOL)textFieldShouldClear:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)cancel:(id)arg1;
- (void)save:(id)arg1;
@property(copy, nonatomic) NSString *footerText; // @synthesize footerText;
@property(nonatomic) BOOL modal; // @synthesize modal;
@property(nonatomic) UINavigationController *navigationController; // @synthesize navigationController;
@property(nonatomic) BOOL didChange; // @synthesize didChange;
@property(retain, nonatomic) ABCallback *callback; // @synthesize callback;
@property(copy, nonatomic) NSString *placeholderText; // @synthesize placeholderText;
@property(copy, nonatomic) NSString *text; // @synthesize text;

@end

