/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class NSArray, NSString, UIButton, UITableView, UITextField;

@interface ABSimpleSearchViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate>
{
    UITableView *_tableView;
    UITextField *_searchField;
    UIButton *_overlayView;
    UIButton *_clearButton;
    BOOL faded;
    NSString *searchText;
    NSArray *matchingSearches;
}

- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (id)placeholderText;
- (id)unmatchedResultFormatText;
- (int)returnKeyType;
- (void)loadView;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)_refade;
- (void)_unfade;
- (id)recentsMatching:(id)arg1;
- (void)_updateMatchingSearches;
- (BOOL)enforceHashtagPrefix;
- (void)_textDidUpdate;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)clear:(id)arg1;
- (void)saveRecent:(id)arg1;
- (void)search:(id)arg1;
- (void)performSearch:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)cancel:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (BOOL)removeRecent:(id)arg1;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
@property(retain, nonatomic) NSString *searchText; // @synthesize searchText;

@end

