/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface ABSound : NSObject
{
    unsigned int soundID;
}

+ (id)soundNamed:(id)arg1;
+ (void)playSoundNamed:(id)arg1;
+ (void)vibrate;
- (id)initWithSoundID:(unsigned long)arg1;
- (void)dealloc;
- (void)play;

@end

