/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ABTableView, NSIndexPath, NSMutableArray, NSString, UITableView;

@interface ABStaticTableViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    BOOL disableScroll;
    ABTableView *_tableView;
    NSString *defaultTitle;
    NSMutableArray *sections;
    NSIndexPath *lastIndexPath;
    id _currentSection;
}

@property(nonatomic) BOOL disableScroll;
- (void)dealloc;
- (int)tableViewStyle;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidUnload;
@property(readonly, nonatomic) UITableView *tableView;
- (void)loadTableView;
- (void)reloadTableView;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)currentSection;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(int)arg2;
- (id)elementForRowAtIndexPath:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (BOOL)automaticallyDeselect;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (id)_addSection;
- (id)addSection;
- (void)setSectionTitle:(id)arg1;
- (id)addSection:(id)arg1;
- (id)addExpandingSection:(id)arg1;
- (void)_reloadSection:(id)arg1 animated:(BOOL)arg2;
- (void)reloadSection:(id)arg1 animated:(BOOL)arg2;
- (void)reloadSection:(id)arg1 withCallback:(id)arg2 animated:(BOOL)arg3;
- (void)reloadSection:(id)arg1 withCallback:(id)arg2;
- (id)sectionContaining:(id)arg1;
- (void)replaceElement:(id)arg1 withElement:(id)arg2;
- (void)_scrollToIndexPath:(id)arg1;
- (void)reloadSectionAndKeepBottomRowOnScreen:(id)arg1;
- (void)setSectionFooterText:(id)arg1;
- (id)addDisclosureRow:(id)arg1 subtitle:(id)arg2 target:(id)arg3 action:(SEL)arg4 info:(id)arg5;
- (id)addDisclosureRow:(id)arg1 target:(id)arg2 action:(SEL)arg3 info:(id)arg4;
- (id)addDisclosureRow:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)addDisclosureRow:(id)arg1 viewControllerClass:(Class)arg2;
- (void)addButtonRow:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)addCheckmarkRow:(id)arg1 checked:(BOOL)arg2;
- (void)addMultiValueRow:(id)arg1 userDefaultsKey:(id)arg2 titles:(id)arg3 values:(id)arg4 defaultValue:(id)arg5 additionalOptions:(id)arg6 callback:(id)arg7;
- (void)addMultiValueRow:(id)arg1 userDefaultsKey:(id)arg2 titles:(id)arg3 values:(id)arg4 defaultValue:(id)arg5 footerText:(id)arg6 callback:(id)arg7;
- (void)_setupFooterText:(id)arg1 info:(id)arg2;
- (void)addLabelRow:(id)arg1 value:(id)arg2 target:(id)arg3 action:(SEL)arg4 info:(id)arg5;
- (void)addLabelRow:(id)arg1 value:(id)arg2;
- (void)addSubtitleLabelRow:(id)arg1 subtitle:(id)arg2 target:(id)arg3 action:(SEL)arg4 info:(id)arg5;
- (void)addSubtitleLabelRow:(id)arg1 subtitle:(id)arg2;
- (void)addContactStyleLabelRow:(id)arg1 value:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (void)addContactStyleLabelRow:(id)arg1 value:(id)arg2 target:(id)arg3 action:(SEL)arg4 info:(id)arg5;
- (void)addContactStyleLabelRow:(id)arg1 value:(id)arg2;
- (void)addSwitchRow:(id)arg1 userDefaultsKey:(id)arg2 invertValue:(BOOL)arg3;
- (void)addSliderRowWithKey:(id)arg1 defaultValue:(id)arg2 leftImage:(id)arg3 rightImage:(id)arg4;
- (void)addTextFieldRow:(id)arg1 title:(id)arg2;
- (id)addMultilineLabelRow:(id)arg1 target:(id)arg2 action:(SEL)arg3;
- (id)addLoadingRow:(id)arg1;
- (id)addCenteredSpinnerRow;
- (void)addCustomCellRow:(id)arg1 height:(float)arg2 target:(id)arg3 action:(SEL)arg4 info:(id)arg5;
- (void)addCustomCellRow:(id)arg1 height:(float)arg2;
- (id)addLargeLeftImageRow:(id)arg1 title:(id)arg2 target:(id)arg3 action:(SEL)arg4;
- (void)didCheckmarkElement:(id)arg1;
- (void)addTextFieldRequestRow:(id)arg1 forKey:(id)arg2 modal:(BOOL)arg3;
- (void)_textFieldRequest:(id)arg1;
- (void)_textFieldDismiss:(id)arg1 info:(id)arg2;
@property(copy, nonatomic) NSString *defaultTitle; // @synthesize defaultTitle;

@end

