/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class ABStaticTableViewMultiValueElement;

@interface ABStaticMultiValueViewController : ABStaticTableViewController
{
    ABStaticTableViewMultiValueElement *multiValueElement;
}

- (void)dealloc;
- (void)viewDidLoad;
- (void)loadTableView;
- (void)didCheckmarkElement:(id)arg1;
@property(retain, nonatomic) ABStaticTableViewMultiValueElement *multiValueElement; // @synthesize multiValueElement;

@end

