/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewElement.h"

@interface ABStaticTableViewCheckmarkElement : ABStaticTableViewElement
{
    BOOL checked;
    BOOL canOnlyCheck;
}

- (void)dealloc;
- (id)cellForTableView:(id)arg1;
- (void)didSelectInTableView:(id)arg1;
@property(nonatomic) BOOL canOnlyCheck; // @synthesize canOnlyCheck;
@property(nonatomic) BOOL checked; // @synthesize checked;

@end

