/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewElement.h"

@interface ABStaticTableViewDisclosureElement : ABStaticTableViewElement
{
    Class viewControllerClass;
}

- (id)cellForTableView:(id)arg1;
- (void)didSelectInTableView:(id)arg1;
@property(nonatomic) Class viewControllerClass; // @synthesize viewControllerClass;

@end

