/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewElement.h"

@class UIImage;

@interface ABStaticTableViewLargeLeftImageElement : ABStaticTableViewElement
{
    UIImage *image;
}

- (void)dealloc;
- (id)cellForTableView:(id)arg1;
- (float)heightInTableView:(id)arg1;
@property(retain, nonatomic) UIImage *image; // @synthesize image;

@end

