/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol ABSubTabBarDelegate

@optional
- (int)numberOfTabsInSubTabBar:(id)arg1;
- (id)subTabBar:(id)arg1 barItemForIndex:(int)arg2;
- (void)subTabBar:(id)arg1 didSelectTabAtIndex:(int)arg2;
- (void)subTabBar:(id)arg1 doubleTapTabAtIndex:(int)arg2;
- (BOOL)subTabBar:(id)arg1 drawGlowForTabAtIndex:(int)arg2;
- (id)subTabBar:(id)arg1 accessibilityLabelForTabAtIndex:(int)arg2;
@end

