/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class UIImage;

@interface ABSubTabBarItem : NSObject
{
    UIImage *image;
    BOOL drawGlow;
}

+ (id)itemWithImage:(id)arg1;
- (void)dealloc;
- (BOOL)drawGlow;
- (BOOL)setDrawGlow:(BOOL)arg1;
@property(retain, nonatomic) UIImage *image; // @synthesize image;

@end

