/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol ABSubTabBarControllerDelegate
- (int)numberOfTabsInSubTabController:(id)arg1;
- (id)subTabBarController:(id)arg1 barItemForIndex:(int)arg2;
- (id)subTabBarController:(id)arg1 viewControllerForIndex:(int)arg2;
- (BOOL)subTabBarController:(id)arg1 drawGlowForIndex:(int)arg2;
- (void)subTabBarController:(id)arg1 didSelectViewControllerAtIndex:(int)arg2;
- (void)subTabBarController:(id)arg1 doubleTapTabItemAtIndex:(int)arg2;
- (id)subTabBarController:(id)arg1 accessibilityLabelForIndex:(int)arg2;
@end

