/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "ABSubTabBarDelegate-Protocol.h"

@class ABSubTabBar, NSString, UIView;

@interface ABSubTabBarController : UIViewController <ABSubTabBarDelegate>
{
    id <ABSubTabBarControllerDelegate> subTabBarControllerDelegate;
    ABSubTabBar *_tabBar;
    UIViewController *_selectedViewController;
    UIView *_visibleView;
    UIViewController *ab_parentViewController;
    NSString *_referringEvent;
}

- (struct CGRect)_tabBarFrame;
- (id)init;
- (void)setInitialSelectedIndex:(int)arg1;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)selectedViewController;
- (void)setSelectedViewController:(id)arg1;
- (void)_updateSelectedWithCurrentSelection;
- (void)reloadTabs;
- (void)updateBadges;
@property(readonly, nonatomic) unsigned int selectedIndex;
- (void)setSelectedIndex:(int)arg1;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (int)numberOfTabsInSubTabBar:(id)arg1;
- (id)subTabBar:(id)arg1 barItemForIndex:(int)arg2;
- (void)subTabBar:(id)arg1 didSelectTabAtIndex:(int)arg2;
- (void)subTabBar:(id)arg1 doubleTapTabAtIndex:(int)arg2;
- (BOOL)subTabBar:(id)arg1 drawGlowForTabAtIndex:(int)arg2;
- (id)subTabBar:(id)arg1 accessibilityLabelForTabAtIndex:(int)arg2;
- (void)setSelectedIndex:(int)arg1 animated:(BOOL)arg2;
- (void)ab_attemptToRecordImpressionFromReferringEvent:(id)arg1;
- (void)ab_resetImpression;
@property(nonatomic) id <ABSubTabBarControllerDelegate> subTabBarControllerDelegate; // @synthesize subTabBarControllerDelegate;

@end

