/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class NSTimer, UIGestureRecognizer;

@interface ABSwipeColumnScrollView : UIView
{
    id <ABSwipeColumnScrollViewDelegate> delegate;
    struct CGSize contentSize;
    UIGestureRecognizer *r;
    NSTimer *timer;
    float dx;
    int steps;
    float friction;
    float springiness;
    struct CGRect workingBounds;
    float destinationOffset;
    id beganInteractionOnItem;
    struct {
        unsigned int disableSpring:1;
        unsigned int throwing:1;
        unsigned int startedOverScrollView:1;
    } _swipeFlags;
    BOOL didHesitate;
}

+ (Class)layerClass;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
@property(nonatomic) struct CGPoint contentOffset;
- (void)_beginTouch:(struct CGPoint)arg1;
- (void)_didScroll:(struct CGPoint)arg1;
- (void)_animateToDestinationOffset;
- (void)jiggle;
- (void)_endScroll:(float)arg1;
- (void)disableSpring;
- (void)animate;
@property(nonatomic) struct CGSize contentSize;
- (void)setContentOffset:(struct CGPoint)arg1 animated:(BOOL)arg2;
- (void)scrollRectToVisible:(struct CGRect)arg1 animated:(BOOL)arg2;
- (void)_invalidateTimer;
- (void)swipeView:(id)arg1 willBeginTouches:(id)arg2 withEvent:(id)arg3;
- (void)_didReset;
@property(readonly, nonatomic) BOOL didHesitate; // @synthesize didHesitate;
@property(nonatomic) id <ABSwipeColumnScrollViewDelegate> delegate; // @synthesize delegate;

@end

