/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABMasterViewController.h"

#import "ABSwipeColumnScrollViewDelegate-Protocol.h"

@class ABSwipeColumnScrollView, CALayer, NSArray, NSMutableArray, UIImageView, UIToolbar, UIView, UIViewController;

@interface ABSwipeColumnViewController : ABMasterViewController <ABSwipeColumnScrollViewDelegate>
{
    id <ABSwipeColumnViewControllerDelegate> delegate;
    NSMutableArray *viewControllers;
    UIViewController *overViewController;
    UIView *_masterContainer;
    ABSwipeColumnScrollView *_scrollView;
    UIImageView *_pullTab;
    UIImageView *sidebarShadow;
    UIImageView *otherSidebarShadow;
    UIView *leftColumnDimmer;
    int currentOrientation;
    UIView *throwawayContainer;
    CALayer *page1;
    CALayer *page2;
    UIViewController *_updatingWidthViewController;
    float _updatingWidthOriginalWidth;
    float _updatingWidthDesiredWidth;
    UIToolbar *_fullScreenToolbar;
    UIView *_fullScreenView;
    struct {
        unsigned int pushing:1;
        unsigned int tracking:1;
        unsigned int sidebarImage:3;
        unsigned int throwawayState:2;
    } _flags;
    int lastSnapOffset;
}

+ (void)_viewControllerDoneAnimatingAway:(id)arg1 info:(id)arg2;
- (id)init;
- (void)dealloc;
@property(readonly, nonatomic) NSArray *viewControllers;
- (void)_setThrowawayState:(int)arg1;
- (void)_updateLayout:(BOOL)arg1;
- (void)loadView;
- (id)swipeView:(id)arg1 willBeginTouches:(id)arg2 withEvent:(id)arg3;
- (void)_reveal:(id)arg1 animated:(BOOL)arg2;
- (void)swipeView:(id)arg1 shouldRevealItem:(id)arg2;
- (id)swipePointsForSwipeView:(id)arg1 proposedOffset:(float)arg2;
- (int)bestOffsetForPossibleOffsets:(id)arg1 fromOffset:(int)arg2 toOffset:(int)arg3 inDirection:(int)arg4;
- (int)nearestOffsetForPossibleOffsets:(id)arg1 fromOffset:(int)arg2 toOffset:(int)arg3;
- (float)swipeView:(id)arg1 willSwipeToOffset:(float)arg2 throwing:(BOOL)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewControllerNeedsToUpdateWidth:(id)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (id)popToRootViewControllerAnimated:(BOOL)arg1;
- (id)_superestColumn:(id)arg1;
@property(readonly, nonatomic) UIViewController *topViewController;
- (void)pushViewController:(id)arg1 afterViewController:(id)arg2 animated:(BOOL)arg3;
- (void)_finishPush:(id)arg1;
- (id)viewControllerAfter:(id)arg1;
- (void)showOverViewAnimationDidEnd:(id)arg1 finished:(id)arg2 context:(void *)arg3;
@property(readonly, nonatomic) UIViewController *overViewController;
- (void)showOverViewController:(id)arg1 animated:(BOOL)arg2;
- (void)ignore:(id)arg1 context:(void *)arg2;
- (void)hideOverViewAnimationDidEnd:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)hideOverViewControllerAnimated:(BOOL)arg1;
- (id)beginFullScreenForView:(id)arg1 animated:(BOOL)arg2;
- (void)beginFullScreenAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (id)endFullScreenAnimated:(BOOL)arg1;
- (id)visibleViewControllers;
- (void)tapStatusBar:(struct CGPoint)arg1;
@property(nonatomic) id <ABSwipeColumnViewControllerDelegate> delegate; // @synthesize delegate;

@end

