/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol ABSwipeColumnViewControllerDelegate
- (void)swipeColumnController:(id)arg1 willBeginInteractionOnViewController:(id)arg2;
- (void)swipeColumnControllerDidHideOverViewController:(id)arg1;
@end

