/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol ABTableViewPullToRefreshDelegate

@optional
- (BOOL)isLoadingNewer;
- (void)pullToRefreshController:(id)arg1 didActivate:(BOOL)arg2;
@end

