/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class UIImageView, UITableView, UIView, UIViewController;

@interface ABTableViewStayOnScreenController : NSObject
{
    UIViewController *_contentsController;
    UITableView *_tableView;
    UIView *_selected;
    UIImageView *shadow;
    id _selectedItem;
    BOOL shadowState;
    BOOL enabled;
}

- (id)initWithTableView:(id)arg1 contentsController:(id)arg2;
- (void)dealloc;
- (void)updateSelectedCellFrame:(BOOL)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)stayOnScreenCellForPoint:(struct CGPoint)arg1;
- (void)tableView:(id)arg1 didSelectItem:(id)arg2;
@property(nonatomic) BOOL enabled; // @synthesize enabled;

@end

