/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol ABTableViewPinchPreview
- (BOOL)pinchPreviewController:(id)arg1 willStartPreviewForCell:(id)arg2;
- (id)pinchPreviewController:(id)arg1 viewControllerForCell:(id)arg2;
- (id)pinchPreviewController:(id)arg1 containerViewForPinchedCell:(id)arg2;
- (id)pinchPreviewController:(id)arg1 headerFlapForPinchedCell:(id)arg2;
- (id)pinchPreviewController:(id)arg1 footerFlapControllerForPinchedCell:(id)arg2;
@end

