/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class ABTableViewCell;

@interface ABTableViewCellView : UIView
{
    ABTableViewCell *_cell;
    struct {
        unsigned int highlighted:1;
        unsigned int isAlwaysOnScreen:1;
        unsigned int animatesNextFrameChange:1;
    } _flags;
}

- (id)initWithFrame:(struct CGRect)arg1 cell:(id)arg2;
@property(readonly, nonatomic) ABTableViewCell *cell;
@property(nonatomic, getter=isHighlighted) BOOL highlighted;
- (void)animatesNextFrameChange;
- (void)setIsAlwaysOnScreen:(BOOL)arg1;
- (BOOL)canAnimateFrameChanges;
- (void)setFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

