/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface ABTextRange : NSObject
{
    struct _NSRange range;
    id userInfo;
}

- (void)dealloc;
- (id)description;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo;
@property(nonatomic) struct _NSRange range; // @synthesize range;

@end

