/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class ABUITextRenderer;

@interface ABTextView : UIView
{
    ABUITextRenderer *renderer;
    id <ABUITextViewDelegate> delegate;
    struct {
        unsigned int animateNextUpdate:1;
    } _flags;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
@property(retain, nonatomic) ABUITextRenderer *renderer; // @synthesize renderer;
- (void)setFrame:(struct CGRect)arg1;
@property(nonatomic) id <ABUITextViewDelegate> delegate; // @synthesize delegate;
- (void)drawRect:(struct CGRect)arg1;
- (void)animateNextUpdate;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;
- (float)heightThatFits;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;

@end

