/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIResponder.h"

@class NSAttributedString, UIView;

@interface ABUITextRenderer : UIResponder
{
    NSAttributedString *attributedString;
    struct CGRect frame;
    UIView *view;
    struct __CTFramesetter *_ct_framesetter;
    struct CGPath *_ct_path;
    struct __CTFrame *_ct_frame;
    struct CGSize _size;
    int _selectionStart;
    int _selectionEnd;
    int _selectionAffinity;
    id <ABUITextRendererDelegate> delegate;
    id <ABActiveTextRange> hitRange;
    struct CGPoint hitPoint;
    id drawHighlight;
    struct {
        unsigned int validSize:1;
    } _flags;
}

@property(copy, nonatomic) id drawHighlight; // @synthesize drawHighlight;
- (void)_resetFramesetter;
- (void)dealloc;
- (void)_buildFramesetter;
- (struct __CTFramesetter *)ctFramesetter;
- (struct __CTFrame *)ctFrame;
- (struct CGPath *)ctPath;
- (long)_clampToValidRange:(long)arg1;
- (struct _NSRange)_wordRangeAtIndex:(long)arg1;
- (struct _NSRange)_lineRangeAtIndex:(long)arg1;
- (struct _NSRange)_paragraphRangeAtIndex:(long)arg1;
- (CDStruct_1ef3fb1f)_selectedRange;
- (id)selectedString;
- (void)draw;
- (struct CGSize)size;
@property(retain, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString;
@property(nonatomic) struct CGRect frame; // @synthesize frame;
- (struct CGRect)firstRectForCharacterRange:(CDStruct_1ef3fb1f)arg1;
- (void)rectsForRange:(CDStruct_1ef3fb1f)arg1 rects:(struct CGRect *)arg2 rectCount:(int *)arg3;
@property(nonatomic) struct CGPoint hitPoint; // @synthesize hitPoint;
@property(retain, nonatomic) id <ABActiveTextRange> hitRange; // @synthesize hitRange;
@property(nonatomic) UIView *view; // @synthesize view;

@end

