/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABUITextRenderer.h"

@interface ABUITextRenderer (Event)
@property(nonatomic) id <ABUITextRendererDelegate> delegate;
- (long)stringIndexForPoint:(struct CGPoint)arg1;
- (struct CGRect)convertRect:(struct CGRect)arg1;
- (id)hitTestRanges:(id)arg1 forPoint:(struct CGPoint)arg2 padding:(float)arg3;
- (id)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (id)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (id)touchesCancelled:(id)arg1 withEvent:(id)arg2;
@end

