/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UIWebViewDelegate-Protocol.h"

@class NSArray, NSURL, UIActivityIndicatorView, UIBarButtonItem, UIWebView, UIWindow;

@interface ABWebViewController : UIViewController <UIWebViewDelegate>
{
    NSURL *rootURL;
    NSURL *currentURL;
    UIWebView *_webView;
    UIBarButtonItem *backItem;
    UIBarButtonItem *forwardItem;
    UIBarButtonItem *statusItem;
    UIBarButtonItem *reloadItem;
    UIBarButtonItem *actionItem;
    NSArray *loadingItemsSet;
    NSArray *loadedItemsSet;
    UIActivityIndicatorView *spinner;
    UIWindow *originalWindow;
    struct {
        unsigned int needsToLoadRequest:1;
        unsigned int showingAlertView:1;
    } _flags;
}

- (void)_updateToolbar;
- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)back:(id)arg1;
- (void)forward:(id)arg1;
- (void)refresh:(id)arg1;
- (void)action:(id)arg1;
- (void)openLatitude:(double)arg1 longitude:(double)arg2;
- (void)openExternalURL:(id)arg1;
- (void)shouldOpenExternalURL:(id)arg1 info:(id)arg2;
- (BOOL)shouldStartLoadWithURL:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(unsigned int)arg3;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
@property(copy, nonatomic) NSURL *currentURL; // @synthesize currentURL;
@property(copy, nonatomic) NSURL *rootURL; // @synthesize rootURL;

@end

