/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface ADBook : NSObject
{
    void *addressBook;
    NSMutableArray *records;
    NSMutableArray *_records;
    NSMutableDictionary *_canonicalIdentitiesToPeople;
}

+ (id)sharedBook;
+ (id)localizedLabel:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)_ab_improved_description_body;
- (id)description;
- (BOOL)save:(id *)arg1;
- (BOOL)hasUnsavedChanges;
- (void *)addressBook;
- (BOOL)addRecord:(id)arg1 error:(id *)arg2;
- (BOOL)removeRecord:(id)arg1 error:(id *)arg2;
- (id)commonRecord:(id)arg1;
- (void)_addPersonsCanonicalIdentitiesToMapping:(id)arg1;
- (id)_mapNewRecords:(struct __CFArray *)arg1;
- (void)noteNewABRecordRef:(void *)arg1;
- (id)people;
- (id)groups;
- (id)peopleWithName:(id)arg1;
- (id)phones;
- (id)emails;
- (id)personWithCanonicalIdentity:(id)arg1;

@end

