/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface ADLabelValue : NSObject
{
    NSString *label;
    id value;
}

+ (id)labelValueArrayForMultiValue:(void *)arg1;
- (id)initWithLabel:(id)arg1 value:(id)arg2;
- (void)dealloc;
- (id)_ab_improved_description_body;
- (id)description;
@property(readonly, nonatomic) id value; // @synthesize value;
@property(readonly, nonatomic) NSString *label; // @synthesize label;

@end

