/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ADRecord.h"

@class NSArray, NSData, NSString, UIImage;

@interface ADPerson : ADRecord
{
    NSData *imageData;
    UIImage *profileImage;
    struct {
        unsigned int didLoadImageData:1;
    } _flags;
}

+ (id)localizedPropertyName:(int)arg1;
- (void *)createRecord;
- (void)dealloc;
- (BOOL)matchesSomeIdentitiesWith:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)_ab_improved_description_body;
- (id)description;
- (id)displayName;
@property(copy, nonatomic) NSString *firstName;
@property(copy, nonatomic) NSString *lastName;
@property(copy, nonatomic) NSString *middleName;
@property(copy, nonatomic) NSString *nickname;
@property(copy, nonatomic) NSString *note;
- (void)setFullName:(id)arg1;
@property(readonly, nonatomic) NSArray *phones;
@property(readonly, nonatomic) NSArray *emails;
@property(readonly, nonatomic) NSArray *urls;
- (id)canonicalIdentities;
- (void)addPhoneNumber:(id)arg1 label:(id)arg2;
- (void)addEmail:(id)arg1 label:(id)arg2;
- (void)addURL:(id)arg1 label:(id)arg2;
- (id)imageData;
- (void)setImageData:(id)arg1;
- (id)profileImage;
- (int)multiValueIdentifierForURLString:(id)arg1;

@end

