/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ADBook;

@interface ADRecord : NSObject
{
    ADBook *book;
    void *record;
}

- (void *)createRecord;
- (id)initWithRecord:(void *)arg1 book:(id)arg2;
- (void)dealloc;
- (id)_ab_improved_description_body;
- (id)description;
@property(readonly, nonatomic) int recordID;
- (BOOL)isInAddressBook;
- (BOOL)isEqual:(id)arg1;
- (void *)ABRecordRef;
- (void)addValue:(id)arg1 label:(id)arg2 forPropertyID:(int)arg3;
- (void)removeValueForPropertyID:(int)arg1;
- (void)setValue:(id)arg1 forPropertyID:(int)arg2;
- (id)valueForPropertyID:(int)arg1 matchPropertyType:(unsigned int)arg2;
- (id)stringForPropertyID:(int)arg1;
- (id)labelValueStringArrayForPropertyID:(int)arg1;

@end

