/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@interface AdvancedSettingsViewController : ABStaticTableViewController
{
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)autorotationOptions:(id)arg1 info:(id)arg2;
- (void)loadTableView;
- (void)readLaterServiceUpdate:(id)arg1 info:(id)arg2;
- (void)imageServiceUpdate:(id)arg1 info:(id)arg2;
- (void)customImageService:(id)arg1 info:(id)arg2;
- (void)quoteStyleDidChange:(id)arg1 info:(id)arg2;
- (void)installBookmarklet:(id)arg1;
- (void)installBookmarklet:(id)arg1 info:(id)arg2;

@end

