/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "BirdhouseBridge.h"

@interface BirdhouseBridge (TweetieAdditions)
+ (BOOL)saveCompositionToBirdhouse:(id)arg1;
+ (BOOL)isInstalled;
+ (void)sendCompositionToBirdhouse:(id)arg1;
@end

