/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface BirdhouseBridge : NSObject
{
}

+ (BOOL)canSaveToBirdhouse;
+ (id)pasteboard;
+ (BOOL)saveTweetToBirdhouse:(id)arg1;
+ (id)tweetsOnPasteboard;
+ (void)clearTweetsOnPasteboard;

@end

