/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface BirdhouseBridgeTweet : NSObject <NSCoding>
{
    NSString *text;
    NSString *inReplyToStatusID;
}

- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)pasteboardRepresentation;
@property(copy, nonatomic) NSString *inReplyToStatusID; // @synthesize inReplyToStatusID;
@property(copy, nonatomic) NSString *text; // @synthesize text;

@end

