/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@class NSError;

#pragma mark Named Structures

struct CGAffineTransform {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
    float _field5;
    float _field6;
};

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    float width;
    float height;
};

struct JKConstBuffer {
    struct JKConstPtrRange bytes;
};

struct JKConstPtrRange {
    char *ptr;
    unsigned int length;
};

struct JKHashTableEntry {
    unsigned int _field1;
    id _field2;
    id _field3;
};

struct JKManagedBuffer {
    struct JKPtrRange bytes;
    unsigned int flags;
    unsigned int roundSizeUpToMultipleOf;
};

struct JKObjCImpCache {
    Class NSNumberClass;
    void *NSNumberAlloc;
    void *NSNumberInitWithUnsignedLongLong;
};

struct JKObjectStack {
    void **objects;
    void **keys;
    unsigned int *cfHashes;
    unsigned int count;
    unsigned int index;
    unsigned int roundSizeUpToMultipleOf;
    unsigned int flags;
};

struct JKParseState {
    unsigned int _field1;
    struct JKConstBuffer _field2;
    unsigned int _field3;
    unsigned int _field4;
    unsigned int _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    struct JKParseToken _field9;
    struct JKObjectStack _field10;
    struct JKTokenCache _field11;
    struct JKObjCImpCache _field12;
    NSError *_field13;
    int _field14;
    char _field15;
};

struct JKParseToken {
    struct JKConstPtrRange tokenPtrRange;
    unsigned int type;
    struct JKTokenValue value;
    struct JKManagedBuffer tokenBuffer;
};

struct JKPtrRange {
    char *ptr;
    unsigned int length;
};

struct JKTokenCache {
    struct JKTokenCacheItem *items;
    unsigned int count;
    unsigned int prng_lfsr;
    unsigned char age[1024];
};

struct JKTokenCacheItem;

struct JKTokenValue {
    struct JKConstPtrRange ptrRange;
    unsigned int type;
    unsigned int hash;
    union {
        long long longLongValue;
        unsigned long long unsignedLongLongValue;
        double doubleValue;
    } number;
    struct JKTokenCacheItem *cacheItem;
};

struct UIEdgeInsets {
    float _field1;
    float _field2;
    float _field3;
    float _field4;
};

struct _NSRange {
    unsigned int location;
    unsigned int length;
};

struct in_addr {
    unsigned int _field1;
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned long _field1;
    id *_field2;
    unsigned long *_field3;
    unsigned long _field4[5];
} CDStruct_11f37819;

typedef struct {
    double latitude;
    double longitude;
} CDStruct_2c43369c;

typedef struct {
    int _field1;
    int _field2;
    void *_field3;
} CDStruct_da23731b;

typedef struct {
    int _field1;
    int _field2;
} CDStruct_1ef3fb1f;

typedef struct {
    CDStruct_2c43369c _field1;
    CDStruct_2c43369c _field2;
} CDStruct_2f492f29;

// Ambiguous groups
typedef struct {
    unsigned int hasRecordedImpression:1;
} CDStruct_daa5b662;

typedef struct {
    unsigned int loadingImage:1;
} CDStruct_1b8233f7;

typedef struct {
    unsigned int once:1;
} CDStruct_8c7a4130;

