/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol ChooseUserViewControllerDelegate
- (void)chooseUserViewController:(id)arg1 didChooseUser:(id)arg2;
- (void)chooseUserViewController:(id)arg1 didChooseUsername:(id)arg2;
- (void)chooseUserViewControllerDidCancel:(id)arg1;
@end

