/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieUserListViewController.h"

@interface ChooseUserViewController : TweetieUserListViewController
{
    id <ChooseUserViewControllerDelegate> delegate;
}

- (id)init;
- (void)viewDidLoad;
- (id)arbitraryUserFormatString;
- (void)selectUser:(id)arg1;
- (void)selectUsername:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
@property(nonatomic) id <ChooseUserViewControllerDelegate> delegate; // @synthesize delegate;

@end

