/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol FollowCostDelegate
- (void)followCost:(id)arg1 didUpdateForUser:(id)arg2;
- (void)followCost:(id)arg1 failedToUpdateForUser:(id)arg2 withError:(id)arg3;
@end

