/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "MKAnnotation-Protocol.h"
#import "NSCoding-Protocol.h"

@interface GeoRSSPoint : NSObject <NSCoding, MKAnnotation>
{
    BOOL didDecodePoint;
    double latitude;
    double longitude;
}

+ (id)geoPointWithDictionary:(id)arg1;
- (void)parseDictionary:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)parseXMLCallback;
- (id)parseJSONCallback;
- (void)parseXML:(id)arg1 info:(id)arg2;
- (void)parseJSON:(id)arg1 info:(id)arg2;
- (void)parseJSONCoordinates:(id)arg1 info:(id)arg2;
- (CDStruct_2f492f29)region;
@property(readonly, nonatomic) CDStruct_2c43369c coordinate;
- (id)annotationViewForMapView:(id)arg1;
- (id)title;
@property(readonly, nonatomic) BOOL didDecodePoint; // @synthesize didDecodePoint;
@property(nonatomic) double longitude; // @synthesize longitude;
@property(nonatomic) double latitude; // @synthesize latitude;

@end

