/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface GoogleStaticMap : NSObject
{
}

+ (id)apiKey;
+ (id)mapImageURLForLatitude:(double)arg1 longitude:(double)arg2 width:(int)arg3 height:(int)arg4;

@end

