/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieUserListViewController.h"

@interface GoToUserViewController : TweetieUserListViewController
{
}

- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (id)arbitraryUserFormatString;
- (void)selectUser:(id)arg1;
- (void)selectUsername:(id)arg1;
- (void)foundUsers:(id)arg1 info:(id)arg2;

@end

