/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSEnumerator.h"

@interface JKDictionaryEnumerator : NSEnumerator
{
    id collection;
    unsigned int nextObject;
}

- (id)initWithJKDictionary:(id)arg1;
- (void)dealloc;
- (id)allObjects;
- (id)nextObject;

@end

