/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface JSONDecoder : NSObject
{
    struct JKParseState *parseState;
}

+ (void)load;
+ (id)decoder;
+ (id)decoderWithParseOptions:(unsigned int)arg1;
- (id)init;
- (id)initWithParseOptions:(unsigned int)arg1;
- (void)dealloc;
- (void)clearCache;
- (id)parseUTF8String:(const char *)arg1 length:(unsigned long)arg2;
- (id)parseUTF8String:(const char *)arg1 length:(unsigned long)arg2 error:(id *)arg3;
- (id)parseJSONData:(id)arg1;
- (id)parseJSONData:(id)arg1 error:(id *)arg2;
- (id)objectWithUTF8String:(const char *)arg1 length:(unsigned int)arg2;
- (id)objectWithUTF8String:(const char *)arg1 length:(unsigned int)arg2 error:(id *)arg3;
- (id)objectWithData:(id)arg1;
- (id)objectWithData:(id)arg1 error:(id *)arg2;
- (id)mutableObjectWithUTF8String:(const char *)arg1 length:(unsigned int)arg2;
- (id)mutableObjectWithUTF8String:(const char *)arg1 length:(unsigned int)arg2 error:(id *)arg3;
- (id)mutableObjectWithData:(id)arg1;
- (id)mutableObjectWithData:(id)arg1 error:(id *)arg2;

@end

