/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface LinkQueue : NSObject
{
    NSString *username;
    NSString *password;
}

+ (Class)preferredLinkQueueClass;
+ (id)defaultLinkQueue;
+ (id)defaultLinkQueueName;
+ (id)defaultLinkQueueURLString;
+ (id)defaultLinkQueueLoginTitle;
+ (id)defaultLinkQueueLoginPlaceholder;
+ (id)defaultLinkQueuePasswordPlaceholder;
- (id)initWithUsername:(id)arg1 password:(id)arg2;
- (void)dealloc;
- (void)verifyCredentials:(id)arg1;
- (void)addURL:(id)arg1 summary:(id)arg2 status:(id)arg3 callback:(id)arg4;
- (int)defaultsIntegerValue;
- (void)saveAsDefault;

@end

