/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MKMapViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class ABHUD, GeoRSSPoint, MKMapView, NSArray, NSString, TwitterPlace, UIActionSheet, UIBarButtonItem;

@interface LocationViewController : UIViewController <MKMapViewDelegate, UIActionSheetDelegate>
{
    TwitterPlace *place;
    GeoRSSPoint *location;
    NSString *locationName;
    UIBarButtonItem *openInMapsItem;
    MKMapView *_mapView;
    ABHUD *hud;
    NSArray *geocodedLocations;
    struct {
        unsigned int shouldDropPinWhenAnimationCompletes:1;
    } _flags;
    UIActionSheet *_chooseLocationSheet;
    UIActionSheet *_openInMapsSheet;
}

+ (id)locationViewControllerWithLatitude:(double)arg1 longitude:(double)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)initWithPlace:(id)arg1 location:(id)arg2 locationName:(id)arg3;
- (void)dealloc;
- (BOOL)ab_shouldShowPullTab;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)loadView;
- (void)viewDidUnload;
- (void)_goToLocation:(BOOL)arg1 span:(double)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)_dropPinAtLocation;
- (void)viewDidAppear:(BOOL)arg1;
- (void)_hideHUD;
- (void)goToGeocodedLocation:(id)arg1;
- (void)geocodeResponse:(id)arg1 info:(id)arg2;
- (void)dismissError:(id)arg1 info:(id)arg2;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)openMaps:(id)arg1;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 didAddAnnotationViews:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
@property(copy, nonatomic) NSString *locationName; // @synthesize locationName;
@property(retain, nonatomic) TwitterPlace *place; // @synthesize place;
@property(retain, nonatomic) GeoRSSPoint *location; // @synthesize location;

@end

