/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MKAnnotation <NSObject>
@property(readonly, nonatomic) CDStruct_2c43369c coordinate;

@optional
- (id)title;
- (id)subtitle;
- (void)setCoordinate:(CDStruct_2c43369c)arg1;
@end

