/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (ABAdditions)
+ (id)arrayByConcatenatingArrays:(id)arg1;
- (id)ab_firstObjectThat:(SEL)arg1;
- (id)map:(SEL)arg1;
- (id)map:(SEL)arg1 withObject:(id)arg2;
- (id)map:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)mapFunction:(void *)arg1 context:(void *)arg2;
- (id)filter:(SEL)arg1;
- (id)filter:(SEL)arg1 withObject:(id)arg2;
- (void)apply:(SEL)arg1;
- (void)apply:(SEL)arg1 withObject:(id)arg2;
- (void)apply:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (void)applyFunction:(void *)arg1 context:(void *)arg2;
- (id)arrayWithoutDuplicates;
- (id)sortedArray;
- (id)reverseSortedArray;
- (id)arrayByRemovingDuplicates;
- (BOOL)hasCommonObjectWithArray:(id)arg1;
- (id)subarrayWithAtMost:(int)arg1;
- (id)subarrayWithAtMostFromEnd:(int)arg1;
- (id)reversedArray;
- (BOOL)ab_containsIndex:(int)arg1;
- (BOOL)ab_isSubsetOfArray:(id)arg1;
- (id)ab_slice:(struct _NSRange)arg1;
@end

