/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSArray.h"

@interface NSArray (ABSimpleArchive)
- (const char *)ab_classNameForSimpleEncoding;
- (void)ab_simpleEncode:(CDStruct_da23731b *)arg1;
- (id)ab_initWithSimpleDecoder:(CDStruct_da23731b *)arg1;
@end

