/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSDate.h"

@interface NSDate (ABAdditions)
- (BOOL)isBefore:(id)arg1;
- (BOOL)isAfter:(id)arg1;
- (id)mediumDateString;
- (id)longDateString;
- (id)_hour_minute_string;
- (void)_US_messagesStyleBoldString:(id *)arg1 normalString:(id *)arg2;
- (void)messagesStyleBoldString:(id *)arg1 normalString:(id *)arg2;
- (void)relativeStyleBoldString:(id *)arg1 normalString:(id *)arg2;
- (id)tinyRelativeTimeAgoString;
- (id)relativeTimeAgoString;
- (id)ISO8601String;
- (id)ab_beginningOfDay;
@end

