/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (CommonHMAC)
- (id)HMACWithAlgorithm:(unsigned int)arg1;
- (id)HMACWithAlgorithm:(unsigned int)arg1 key:(id)arg2;
@end

