/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (CommonDigest)
- (id)MD2Sum;
- (id)MD4Sum;
- (id)MD5Sum;
- (id)SHA1Hash;
- (id)SHA224Hash;
- (id)SHA256Hash;
- (id)SHA384Hash;
- (id)SHA512Hash;
@end

