/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSError.h"

@interface NSError (ABAdditions)
+ (id)errorWithDomain:(id)arg1 code:(int)arg2 description:(id)arg3;
- (id)errorString;
@end

