/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSMutableAttributedString.h"

@class UIColor, UIFont;

@interface NSMutableAttributedString (ABUIAdditions)
- (struct _NSRange)_stringRange;
- (void)setFont:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)setColor:(id)arg1 inRange:(struct _NSRange)arg2;
@property(retain, nonatomic) UIFont *font;
@property(retain, nonatomic) UIColor *color;
@property(nonatomic) int alignment;
@end

