/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (RegexKitLiteAdditions)
+ (void)clearStringCache;
+ (int)captureCountForRegex:(id)arg1;
+ (int)captureCountForRegex:(id)arg1 options:(unsigned int)arg2 error:(id *)arg3;
- (id)componentsSeparatedByRegex:(id)arg1;
- (id)componentsSeparatedByRegex:(id)arg1 range:(struct _NSRange)arg2;
- (id)componentsSeparatedByRegex:(id)arg1 options:(unsigned int)arg2 range:(struct _NSRange)arg3 error:(id *)arg4;
- (BOOL)isMatchedByRegex:(id)arg1;
- (BOOL)isMatchedByRegex:(id)arg1 inRange:(struct _NSRange)arg2;
- (BOOL)isMatchedByRegex:(id)arg1 options:(unsigned int)arg2 inRange:(struct _NSRange)arg3 error:(id *)arg4;
- (struct _NSRange)rangeOfRegex:(id)arg1;
- (struct _NSRange)rangeOfRegex:(id)arg1 capture:(int)arg2;
- (struct _NSRange)rangeOfRegex:(id)arg1 inRange:(struct _NSRange)arg2;
- (struct _NSRange)rangeOfRegex:(id)arg1 options:(unsigned int)arg2 inRange:(struct _NSRange)arg3 capture:(int)arg4 error:(id *)arg5;
- (id)stringByMatching:(id)arg1;
- (id)stringByMatching:(id)arg1 capture:(int)arg2;
- (id)stringByMatching:(id)arg1 inRange:(struct _NSRange)arg2;
- (id)stringByMatching:(id)arg1 options:(unsigned int)arg2 inRange:(struct _NSRange)arg3 capture:(int)arg4 error:(id *)arg5;
- (id)stringByReplacingOccurrencesOfRegex:(id)arg1 withString:(id)arg2;
- (id)stringByReplacingOccurrencesOfRegex:(id)arg1 withString:(id)arg2 range:(struct _NSRange)arg3;
- (id)stringByReplacingOccurrencesOfRegex:(id)arg1 withString:(id)arg2 options:(unsigned int)arg3 range:(struct _NSRange)arg4 error:(id *)arg5;
@end

