/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSEnumerator.h"

@class NSString;

@interface RKLMatchEnumerator : NSEnumerator
{
    NSString *string;
    NSString *regex;
    unsigned int location;
}

- (id)initWithString:(id)arg1 regex:(id)arg2;
- (id)nextObject;
- (void)dealloc;

@end

