/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "URLShorteningService.h"

@interface TCOURLShortener : URLShorteningService
{
}

- (void)shortenURLString:(id)arg1 fromAccount:(id)arg2 callback:(id)arg3;

@end

