/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class TIComposeAttachmentsView, TwitterCompositionAttachment, UIButton;

@interface TIAttachmentView : UIView
{
    TIComposeAttachmentsView *attachmentsView;
    TwitterCompositionAttachment *attachment;
    UIButton *deleteButton;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
- (void)delete:(id)arg1;
@property(nonatomic) TIComposeAttachmentsView *attachmentsView; // @synthesize attachmentsView;
@property(retain, nonatomic) TwitterCompositionAttachment *attachment; // @synthesize attachment;

@end

