/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableArray, UIButton, UIScrollView;

@interface TIComposeAttachmentsView : UIView
{
    id <TIComposeAttachmentsViewDelegate> delegate;
    UIScrollView *_scrollView;
    NSMutableArray *attachmentViews;
    UIButton *cameraButton;
    UIButton *libraryButton;
    struct {
        unsigned int hasLoaded:1;
    } _flags;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)camera:(id)arg1;
- (void)photoLibrary:(id)arg1;
- (id)attachmentViewForAttachment:(id)arg1;
- (void)didDelete:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_updateAddMoreButtonState;
- (void)deleteAttachment:(id)arg1;
- (void)reload;
- (struct CGRect)buttonFrame:(int)arg1;
- (void)layoutSubviews;
@property(nonatomic) id <TIComposeAttachmentsViewDelegate> delegate; // @synthesize delegate;

@end

