/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterUser.h"

@interface TListsPerson : TwitterUser
{
    float tweetsPerDay;
}

- (void)parseSearchTweeter:(id)arg1 info:(id)arg2;
@property(nonatomic) float tweetsPerDay; // @synthesize tweetsPerDay;

@end

