/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class TwitterStatus;

@interface TopTweetCell : UIView
{
    TwitterStatus *status;
}

- (id)initWithStatus:(id)arg1;
- (void)dealloc;
- (void)userDidUpdate:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)railView;
- (void)singleTap;
- (void)doubleTap;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) TwitterStatus *status; // @synthesize status;

@end

