/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIActionSheetDelegate-Protocol.h"

@class NSMutableIndexSet, NSString, TwitterAccount, UIActionSheet, UINavigationController;

@interface TweetieShowLinksForStringHelper : NSObject <UIActionSheetDelegate>
{
    TwitterAccount *account;
    UIActionSheet *sheet;
    UINavigationController *navigationController;
    NSString *sourceString;
    NSMutableIndexSet *linksSet;
    NSMutableIndexSet *usernamesSet;
    NSMutableIndexSet *hashtagsSet;
    NSMutableIndexSet *emailAddressesSet;
    NSMutableIndexSet *stockSymbolsSet;
}

- (id)init;
- (void)dealloc;
- (BOOL)showForString:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)dismissSheet;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

