/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class ABCallback, NSString;

@interface TweetieUserProfile4WayCornerView : UIView
{
    NSString *bigText;
    NSString *littleText;
    int cornerMask;
    ABCallback *callback;
    BOOL highlighted;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)_updateAX;
@property(copy, nonatomic) NSString *bigText; // @synthesize bigText;
@property(copy, nonatomic) NSString *littleText; // @synthesize littleText;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted;
- (void)drawRect:(struct CGRect)arg1;
- (id)buttonView;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) ABCallback *callback; // @synthesize callback;
@property(nonatomic) int cornerMask; // @synthesize cornerMask;

@end

