/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitPicCompatibleImageService.h"

@interface TweetPhoto : TwitPicCompatibleImageService
{
}

+ (id)thumbnailImageURLForURL:(id)arg1;
+ (id)fullSizeImageURLForURL:(id)arg1;
- (id)OAuthEchoServiceProvider;
- (void)addMoarStuff:(id)arg1;
- (id)apiRoot;
- (id)apiKeyParameterName;
- (id)apiKey;
- (id)mediaURLResponseTag;

@end

