/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABSearchableTableViewController.h"

#import "UIActionSheetDelegate-Protocol.h"

@class NSArray, TwitterAccount;

@interface TweetieMessagesViewController : ABSearchableTableViewController <UIActionSheetDelegate>
{
    TwitterAccount *account;
    NSArray *filteredConversations;
    struct {
        unsigned int didLogImpression:1;
    } _flags;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (id)backBarButtonItemTitle;
- (void)showActionSheet;
- (void)doubleTappedRepresentativeTabItem;
- (void)markAllAsRead:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)ab_attemptToRecordImpressionFromReferringEvent:(id)arg1;
- (void)ab_resetImpression;
- (void)viewWillSwitchToAnotherSubTab;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)searchDisplayController:(id)arg1 didLoadSearchResultsTableView:(id)arg2;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (id)selectedConversation;
- (void)selectConversation:(id)arg1;
- (void)conversationsDidUpdate:(id)arg1;
- (id)conversationAtIndex:(int)arg1 inTableView:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)updateVisibleUnreadBits:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

