/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class NSString, TwitterAccount;

@interface TweetieUnknownListViewController : ABStaticTableViewController
{
    TwitterAccount *account;
    NSString *listName;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)loadTableView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (void)listResponse:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSString *listName; // @synthesize listName;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

