/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface TweetieProtocolHandling : NSObject
{
}

+ (BOOL)isSupportedScheme:(id)arg1;
+ (void)_jumpToMainScreen:(int)arg1 account:(id)arg2 navigationController:(id)arg3;
+ (id)legacyURL:(id)arg1;
+ (id)desiredAccountForAccount:(id)arg1 url:(id)arg2;
+ (BOOL)handleURL:(id)arg1 account:(id)arg2 navigationController:(id)arg3 animated:(BOOL)arg4;

@end

