/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABSubTabBarController.h"

#import "ABSubTabBarControllerDelegate-Protocol.h"
#import "TweetieEditProfileViewControllerDelegate-Protocol.h"
#import "TweetieUserProfileViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class NSString, TweetieUserFavoritesViewController, TweetieUserMentionsViewController, TweetieUserProfileViewController, TweetieUserRecentsViewController, TwitterAccount, TwitterUser, UIBarButtonItem;

@interface TweetieUserViewController : ABSubTabBarController <ABSubTabBarControllerDelegate, TweetieEditProfileViewControllerDelegate, TweetieUserProfileViewControllerDelegate, UIActionSheetDelegate>
{
    TwitterAccount *account;
    TwitterUser *user;
    NSString *username;
    NSString *userID;
    UIBarButtonItem *actionItem;
    TweetieUserProfileViewController *profileViewController;
    TweetieUserRecentsViewController *recentsViewController;
    TweetieUserMentionsViewController *mentionsViewController;
    TweetieUserFavoritesViewController *favoritesViewController;
    struct {
        unsigned int didTryToResolveWithCachedUsers:1;
    } _flags;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
- (BOOL)isMe;
- (void)_updateTitle;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (BOOL)userIsLoaded;
- (void)_updateNavigationBar;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)_tryToResolveWithCachedUsers;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;
- (void)viewWillAppear:(BOOL)arg1;
- (void)fullUserResponse:(id)arg1 info:(id)arg2;
- (void)dismissError:(id)arg1 info:(id)arg2;
- (void)reply:(id)arg1;
- (void)_loadConversation;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)edit:(id)arg1;
- (void)editProfileControllerWillCancel:(id)arg1;
- (void)editProfileControllerDidSave:(id)arg1;
- (int)numberOfTabsInSubTabController:(id)arg1;
- (id)subTabBarController:(id)arg1 accessibilityLabelForIndex:(int)arg2;
- (id)subTabBarController:(id)arg1 barItemForIndex:(int)arg2;
- (id)subTabBarController:(id)arg1 viewControllerForIndex:(int)arg2;
- (BOOL)subTabBarController:(id)arg1 drawGlowForIndex:(int)arg2;
- (void)subTabBarController:(id)arg1 didSelectViewControllerAtIndex:(int)arg2;
- (void)subTabBarController:(id)arg1 doubleTapTabItemAtIndex:(int)arg2;
- (void)profileViewControllerSelectFollowing;
- (void)profileViewControllerSelectFollowers;
- (void)_profileViewControllerSelectTweets;
- (void)_profileViewControllerSelectFavorites;
- (void)profileViewControllerSelectTweets;
- (void)profileViewControllerSelectFavorites;
@property(copy, nonatomic) NSString *userID; // @synthesize userID;
@property(copy, nonatomic) NSString *username; // @synthesize username;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

