/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieSearchResultsViewController.h"

#import "MKMapViewDelegate-Protocol.h"
#import "TweetiePlaceMapTapDetectorDelegate-Protocol.h"

@class GeoRSSPoint, MKMapView, TwitterPlace, UIActivityIndicatorView, UIView;

@interface TweetiePlaceSearchResultsViewController : TweetieSearchResultsViewController <MKMapViewDelegate, TweetiePlaceMapTapDetectorDelegate>
{
    TwitterPlace *place;
    GeoRSSPoint *location;
    UIActivityIndicatorView *mapSpinner;
    UIView *mapViewContainer;
    MKMapView *mapView;
    UIView *shadowView;
}

- (id)initWithPlace:(id)arg1 location:(id)arg2 account:(id)arg3;
- (id)autosaveName;
- (void)_updateTitle;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (float)_headerExtraOffset;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_loadFullPlace;
- (void)didLoadFullPlace:(id)arg1 info:(id)arg2;
- (void)loadHeaderView;
- (void)viewDidUnload;
- (id)mapView:(id)arg1 viewForOverlay:(id)arg2;
- (void)tapDetector:(id)arg1 didReceiveTap:(id)arg2;
- (void)dealloc;
@property(retain, nonatomic) GeoRSSPoint *location; // @synthesize location;
@property(retain, nonatomic) TwitterPlace *place; // @synthesize place;

@end

