/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "ABAutocompleteControllerDelegate-Protocol.h"
#import "TIComposeAttachmentsViewDelegate-Protocol.h"
#import "TIComposeMapViewDelegate-Protocol.h"
#import "TweetieComposeSwitchAccountViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class ABHUD, NSMutableArray, NSURL, SMTEDelegateController, TIComposeAttachmentsView, TIComposeMapView, TweetieComposeAttachmentsViewController, TweetieComposeTitleView, TwitterAccount, TwitterAutocompleteController, TwitterComposition, UIActionSheet, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIImageView, UILabel, UIScrollView, UITextView, UIView;

@interface TweetieComposeViewController : UIViewController <UIActionSheetDelegate, UIAlertViewDelegate, UITextViewDelegate, UIScrollViewDelegate, TIComposeMapViewDelegate, TIComposeAttachmentsViewDelegate, TweetieComposeSwitchAccountViewControllerDelegate, ABAutocompleteControllerDelegate>
{
    id <TweetieComposeViewControllerDelegate> delegate;
    TwitterAccount *account;
    TwitterComposition *composition;
    NSURL *remoteCallback;
    UILabel *remainingCharactersLabel;
    UIButton *disclosureButton;
    UIActivityIndicatorView *disclosureSpinner;
    UIImageView *disclosurePin;
    UIButton *buttonBarPlaceButton;
    UIButton *buttonBarPhotoButton;
    UIBarButtonItem *sendButton;
    UIView *header;
    UILabel *peekTextLabel;
    TweetieComposeTitleView *titleView;
    UIActionSheet *cancelActionSheet;
    UIActionSheet *tooLongActionSheet;
    UIActionSheet *geotagActionSheet;
    UIButton *placeBar;
    UIButton *geoButton;
    UIActivityIndicatorView *locationSpinner;
    UILabel *placeBarLoadingLabel;
    ABHUD *hud;
    NSMutableArray *places;
    struct _NSRange preUndoOrRedoSelection;
    BOOL menuWillAppear;
    int autocompleteStartIndex;
    struct _NSRange selection;
    UIImageView *nipple;
    TIComposeMapView *mapView;
    TIComposeAttachmentsView *attachmentsView;
    TweetieComposeAttachmentsViewController *attachmentsViewController;
    TwitterAutocompleteController *autocompleteController;
    SMTEDelegateController *textExpanderController;
    int saveButtonIndex;
    int saveToBirdhouseButtonIndex;
    int dontSaveButtonIndex;
    struct _NSRange lastSelectionRange;
    id _locationRequestToken;
    BOOL foundCoursePlaces;
    BOOL automaticallyPickGeo;
    BOOL userClickedGeo;
    UIScrollView *underKeyboardView;
    UITextView *textView;
    UIView *textViewWrapper;
    UIView *buttonBarContainer;
    UIView *centeredButtonsContainer;
    struct {
        unsigned int headerVisible:1;
        unsigned int animationCount:5;
        unsigned int once:1;
    } _flags;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;
- (void)accountConfigurationDidChange:(id)arg1;
@property(retain, nonatomic) TwitterComposition *composition; // @synthesize composition;
- (void)dealloc;
- (void)_updateHeaderFrame;
- (void)loadView;
- (void)_typeText:(id)arg1;
- (void)prepareForForcedAutoComplete;
- (void)buttonBarAt:(id)arg1;
- (void)buttonBarHash:(id)arg1;
- (void)buttonBarPlace:(id)arg1;
- (void)autocompleteControllerDidBegin:(id)arg1;
- (void)autocompleteControllerDidEnd:(id)arg1;
- (void)pushLoading;
- (void)popLoading;
- (void)_updateTitle;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (struct CGRect)_nippleFrame;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)didSelectPlaceEntity:(id)arg1;
- (void)didUndoOrRedo:(id)arg1;
- (void)willUndoOrRedo:(id)arg1;
- (void)willShowMenu:(id)arg1;
- (void)didShowMenu:(id)arg1;
- (int)visibleUnderKeyboardViewIndex;
- (void)scrollToUnderKeyboardViewIndex:(int)arg1 animated:(BOOL)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)_saveDraftAndDismiss;
- (void)cancel:(id)arg1;
- (void)forceDismissAndSaveAsDraft;
- (void)_dismiss;
- (void)_send;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)_checkLengthAndSend;
- (void)send:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)selectAccount:(id)arg1;
- (void)dismissAccountSwitcher:(id)arg1;
- (BOOL)_keyboardIsUp;
- (void)_showKeyboard:(id)arg1;
- (void)_hideKeyboard:(id)arg1;
- (void)_toggleKeyboard:(id)arg1;
- (void)camera:(id)arg1;
- (void)photoLibrary:(id)arg1;
- (void)_textDidChange;
- (void)textViewDidChangeSelection:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (void)attachments:(id)arg1;
- (void)didRemoveAttachment:(id)arg1;
- (void)_updateGlowingButtonBarButtons;
- (void)_setupCounter;
@property(readonly, nonatomic) UIView *centeredButtonsContainer; // @synthesize centeredButtonsContainer;
@property(readonly, nonatomic) UIView *buttonBarContainer; // @synthesize buttonBarContainer;
@property(readonly, nonatomic) UIView *textViewWrapper; // @synthesize textViewWrapper;
@property(readonly, nonatomic) UITextView *textView; // @synthesize textView;
@property(readonly, nonatomic) UIScrollView *underKeyboardView; // @synthesize underKeyboardView;
@property(retain, nonatomic) NSURL *remoteCallback; // @synthesize remoteCallback;
@property(nonatomic) id <TweetieComposeViewControllerDelegate> delegate; // @synthesize delegate;

@end

