/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "MKAnnotationView.h"

@class CALayer;

@interface TweetieStatusAnnotationView : MKAnnotationView
{
    CALayer *funkmaster;
}

- (id)initWithAnnotation:(id)arg1 reuseIdentifier:(id)arg2;
- (void)showAnimation:(double)arg1;

@end

