/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "MKAnnotation-Protocol.h"

@class TwitterStatus;

@interface TweetieStatusAnnotation : NSObject <MKAnnotation>
{
    TwitterStatus *status;
    CDStruct_2c43369c coordinate;
}

- (void)dealloc;
@property(readonly, nonatomic) CDStruct_2c43369c coordinate;
- (id)title;
- (id)subtitle;
@property(retain, nonatomic) TwitterStatus *status; // @synthesize status;

@end

