/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SMSStyleMessageCell.h"

@class ABCallback, TweetieConversationViewController, TwitterAccount, UIButton;

@interface TweetieDirectMessageCell : SMSStyleMessageCell
{
    TwitterAccount *account;
    TweetieConversationViewController *conversationViewController;
    UIButton *profileImageButton;
    UIButton *errorButton;
    ABCallback *retryCallback;
}

+ (id)messageFont;
- (void)dealloc;
- (id)timeStampString;
- (void)layoutSubviews;
- (void)retrySend:(id)arg1;
- (void)userDetails:(id)arg1;
- (void)_updateImage;
- (BOOL)hasError;
- (void)updateErrorButton;
- (void)setMessage:(id)arg1;
- (void)didUpdate:(id)arg1;
- (void)drawContentView:(struct CGRect)arg1;
- (BOOL)canBecomeFirstResponder;
- (BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)copy:(id)arg1;
- (void)didTapActiveRange:(id)arg1;
@property(readonly, nonatomic) UIButton *errorButton; // @synthesize errorButton;
@property(retain, nonatomic) ABCallback *retryCallback; // @synthesize retryCallback;
@property(nonatomic) TweetieConversationViewController *conversationViewController; // @synthesize conversationViewController;
@property(nonatomic) TwitterAccount *account; // @synthesize account;

@end

