/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class ABCallback, TweetiePromotedButton, TwitterTrend;

@interface TweetieTrendCell : UITableViewCell
{
    TwitterTrend *trend;
    TweetiePromotedButton *promotedLabel;
    ABCallback *promotedLabelCallback;
}

+ (id)cellIdentifier;
+ (id)dequeueCellForTableView:(id)arg1;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)update;
- (void)didClickPromotedLabel:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) ABCallback *promotedLabelCallback; // @synthesize promotedLabelCallback;
@property(retain, nonatomic) TwitterTrend *trend; // @synthesize trend;

@end

