/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieSearchesViewController.h"

#import "TweetieAddAccountViewControllerDelegate-Protocol.h"
#import "TweetieSignUpViewControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class TweetieAccountsViewController;

@interface TweetieLoggedOutViewController : TweetieSearchesViewController <TweetieAddAccountViewControllerDelegate, TweetieSignUpViewControllerDelegate, UINavigationControllerDelegate>
{
    TweetieAccountsViewController *accountsViewController;
}

- (id)init;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)signIn:(id)arg1;
- (void)signUp:(id)arg1;
- (void)_handleAccount:(id)arg1;
- (void)signUpViewController:(id)arg1 didSignUpNewAccount:(id)arg2;
- (void)addAccountController:(id)arg1 didAddAccount:(id)arg2;
- (BOOL)viewControllerShouldBeHidden:(id)arg1;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)_recordImpression;
@property(nonatomic) TweetieAccountsViewController *accountsViewController; // @synthesize accountsViewController;

@end

