/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TweetieAddAccountViewControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class UIBarButtonItem, UITableView;

@interface TweetieAccountsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, TweetieAddAccountViewControllerDelegate>
{
    UITableView *accountsTableView;
    UIBarButtonItem *refreshAllItem;
    BOOL didAddAccountOnce;
    int noAnimationCount;
    BOOL showWelcomeScreen;
}

+ (float)tableRowHeight;
+ (id)tableView:(id)arg1 cellForAccount:(id)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
- (void)loadView;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)beginLoggedOutStateAnimated:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)settings:(id)arg1;
- (void)refreshAll:(id)arg1;
- (void)settingsDidComplete:(id)arg1;
- (void)userDidUpdate:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
- (id)accountForIndex:(int)arg1;
- (int)rowForAccount:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)beginNoAnimation;
- (void)endNoAnimation;
- (BOOL)shouldAnimate;
- (void)viewAccount:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)addAccountForced:(BOOL)arg1;
- (void)addAccount:(id)arg1;
- (void)addAccountController:(id)arg1 didAddAccount:(id)arg2;
- (void)welcomeDidEnd:(id)arg1;
@property(nonatomic) BOOL showWelcomeScreen; // @synthesize showWelcomeScreen;

@end

