/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class TwitterAccount, TwitterStatus, UIBarButtonItem, UIImageView, UILabel, UIView, UIWebView;

@interface TweetieTweetViewController : UIViewController <UIWebViewDelegate, UIActionSheetDelegate, MFMailComposeViewControllerDelegate>
{
    id <TweetieTweetViewControllerDelegate> tweetViewControllerDelegate;
    TwitterAccount *account;
    TwitterStatus *status;
    UIView *_headerView;
    UIView *_extenderView;
    UIWebView *_webView;
    UIBarButtonItem *replyItem;
    UIBarButtonItem *linkItem;
    UIBarButtonItem *deleteItem;
    UIBarButtonItem *favoriteItem;
    UIBarButtonItem *actionItem;
    UIBarButtonItem *retweetItem;
    UIImageView *_profileImageView;
    UILabel *_usernameLabel;
    UILabel *_usernameLabel2;
    BOOL _webViewHasContent;
    struct {
        unsigned int isLoadingTwitlonger:1;
        unsigned int isLoadingPlace:1;
    } _flags;
    CDStruct_daa5b662 _impressionFlags;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (int)headerHeight;
- (id)_renderPlaceMapJS;
- (void)didLoadFullPlace:(id)arg1 info:(id)arg2;
- (void)_loadFullPlace;
- (void)loadView;
- (void)_updateNavigationBar;
- (void)_updateToolbar;
- (void)_updateUserInfo;
- (void)userDidUpdate:(id)arg1;
- (void)setStatus:(id)arg1 animated:(BOOL)arg2 direction:(int)arg3;
@property(retain, nonatomic) TwitterStatus *status; // @synthesize status;
- (void)viewDidLoad;
- (void)_stretchedViewsMayNeedDisplay;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidUnload;
- (id)mediaString:(id)arg1;
- (id)attachmentsHTML;
- (id)footerHTML;
- (BOOL)canAccessReplyChain;
- (id)replyChainButtonHTML;
- (id)htmlString;
- (void)_updateStatusContent;
- (void)viewWillAppear:(BOOL)arg1;
- (void)reply:(id)arg1;
- (void)linkAction:(id)arg1;
- (void)delete:(id)arg1;
- (void)didDelete:(id)arg1 info:(id)arg2;
- (void)favorite:(id)arg1;
- (void)action:(id)arg1;
- (void)retweetConfirm:(id)arg1;
- (void)nextPrev:(id)arg1;
- (void)_nextPrev:(id)arg1;
- (void)userDetails:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(unsigned int)arg3;
- (void)ab_attemptToRecordImpressionFromReferringEvent:(id)arg1;
- (void)ab_resetImpression;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;
@property(nonatomic) id <TweetieTweetViewControllerDelegate> tweetViewControllerDelegate; // @synthesize tweetViewControllerDelegate;

@end

