/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieUserListViewController.h"

@class ADBook, NSArray, NSMutableArray, UIActivityIndicatorView, UIButton, UILabel;

@interface TweetieFindFriendsViewController : TweetieUserListViewController
{
    ADBook *_addressBook;
    NSArray *_emails;
    NSArray *_phones;
    NSMutableArray *_foundUsers;
    UILabel *_foundContactsLabel;
    UIButton *_followAllButton;
    UIActivityIndicatorView *_spinner;
    int _outstandingRequests;
    int _totalRequests;
    struct {
        unsigned int hasRequestedUsers:1;
        unsigned int doneWaiting:1;
        unsigned int doneWithRequests:1;
    } _findFriendsFlags;
}

- (id)initWithAccount:(id)arg1 addressBook:(id)arg2 simpleFollowSet:(id)arg3;
- (void)dealloc;
- (BOOL)showComposeButton;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)_requestMatchingUsers;
- (void)_didWaitEnough;
- (void)_showFollowAll;
- (void)_updateFollowAll;
- (id)_notFollowingUsers:(id)arg1;
- (BOOL)_shouldShowMatchingUsers;
- (void)_showMatchingUsers;
- (void)gotMatchingUsers:(id)arg1 info:(id)arg2;
- (void)followAll:(id)arg1;
- (void)handleError;
- (void)didFollowAll:(id)arg1 info:(id)arg2;
- (void)_finishFollowAll;
- (void)follow_unfollow:(id)arg1;
- (void)userDidUnfollow:(id)arg1;

@end

