/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieStatusListViewController.h"

@class TwitterStream;

@interface TweetieStatusStreamViewController : TweetieStatusListViewController
{
    CDStruct_8c7a4130 _streamFlags;
    CDStruct_daa5b662 _impressionFlags;
}

- (void)dealloc;
- (void)streamDidUpdate:(id)arg1;
- (void)streamError:(id)arg1;
- (void)ab_attemptToRecordImpressionFromReferringEvent:(id)arg1;
- (void)ab_resetImpression;
- (id)ab_referrerID;
- (void)recordImpressionFromReferringEvent:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)syncStreamPosition:(id)arg1;
- (void)requestTopStatusID;
- (void)noteNewTopStatusID:(id)arg1;
- (void)loadOlder:(id)arg1;
- (void)loadNewer:(id)arg1;
- (void)fillInGap:(id)arg1;
- (BOOL)isLoadingNewer;
- (id)lastUpdated;
- (id)autosaveName;

// Remaining properties
@property(readonly, nonatomic) TwitterStream *statusStream; // @dynamic statusStream;

@end

