/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface TweetieListViewControllerController : NSObject
{
}

+ (id)barButtonItemsForList:(id)arg1 account:(id)arg2 flipped:(BOOL)arg3 target:(id)arg4;
+ (void)flipButton:(id)arg1 transition:(int)arg2;

@end

