/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieAbstractSearchController.h"

@class NSArray;

@interface TweetieSearchAllTweetsController : TweetieAbstractSearchController
{
    NSArray *matchingSearches;
}

- (void)dealloc;
- (id)recentSearches;
- (id)recentSearchesMatching:(id)arg1;
- (id)matchingRecentSearches;
- (void)updateMatchingSearches;
- (id)matchingSearchAtIndex:(int)arg1;
- (void)saveRecentSearch:(id)arg1;
- (BOOL)removeRecentSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (BOOL)_isNearbySearch;
- (id)nearString;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)startSearch:(id)arg1;
- (void)doSearchFor:(id)arg1;
- (void)searchForSearchText;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;

@end

