/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieUserListViewController.h"

@class TwitterUser, TwitterUserList;

@interface TweetieUserStreamViewController : TweetieUserListViewController
{
    TwitterUser *user;
    TwitterUserList *userList;
    BOOL didFirstLoad;
}

- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (id)_userList;
- (id)userList;
- (void)_update;
- (void)loadMore:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)update:(id)arg1;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;

@end

