/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "MKMapViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class ABHUD, NSArray, NSString, TwitterAccount, TwitterPlace, UIBarButtonItem, UITableViewCell, UITextField;

@interface TweetieAddPlaceViewController : ABStaticTableViewController <MKMapViewDelegate, UITextFieldDelegate>
{
    TwitterPlace *pickedPlace;
    NSString *token;
    UITextField *nameField;
    UITextField *addressField;
    UIBarButtonItem *saveButton;
    UITableViewCell *mapView;
    id <ABPlacePickerDelegate> delegate;
    ABHUD *hud;
    TwitterAccount *account;
    NSArray *similarPlaces;
    NSString *initialText;
}

- (id)init;
- (void)dealloc;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)loadTableView;
- (void)viewDidLoad;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)save:(id)arg1;
- (void)didGetToken:(id)arg1 info:(id)arg2;
- (void)didFindContainer:(id)arg1 info:(id)arg2;
- (void)placeDidSave:(id)arg1 info:(id)arg2;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
@property(retain, nonatomic) NSArray *similarPlaces; // @synthesize similarPlaces;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;
@property(nonatomic) id <ABPlacePickerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSString *initialText; // @synthesize initialText;
@property(retain, nonatomic) NSString *token; // @synthesize token;
@property(retain, nonatomic) TwitterPlace *pickedPlace; // @synthesize pickedPlace;

@end

