/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol TweetBlockerDelegate
- (void)tweetBlocker:(id)arg1 error:(id)arg2;
- (void)tweetBlockerDidUpdate:(id)arg1;
@end

