/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableViewController.h"

@class TwitterAccount, TwitterComposition, UISegmentedControl;

@interface TweetieComposeSwitchAccountViewController : UITableViewController
{
    id <TweetieComposeSwitchAccountViewControllerDelegate> delegate;
    TwitterAccount *selectedAccount;
    TwitterComposition *composition;
    UISegmentedControl *segmented;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)done:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
@property(retain, nonatomic) TwitterComposition *composition; // @synthesize composition;
@property(retain, nonatomic) TwitterAccount *selectedAccount; // @synthesize selectedAccount;
@property(nonatomic) id <TweetieComposeSwitchAccountViewControllerDelegate> delegate; // @synthesize delegate;

@end

