/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class NSString, TwitterAccount;

@interface TweetieUnknownTweetViewController : ABStaticTableViewController
{
    TwitterAccount *account;
    NSString *statusID;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)loadTableView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)statusResponse:(id)arg1 info:(id)arg2;
- (void)dismissError:(id)arg1 info:(id)arg2;
@property(copy, nonatomic) NSString *statusID; // @synthesize statusID;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

