/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class TwitterList;

@interface TweetieListCell : UITableViewCell
{
    TwitterList *list;
}

- (id)initWithList:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) TwitterList *list; // @synthesize list;

@end

