/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABSearchableTableViewController.h"

#import "UIActionSheetDelegate-Protocol.h"

@class NSArray, NSString, TwitterAccount, UIBarButtonItem;

@interface TweetieDraftsViewController : ABSearchableTableViewController <UIActionSheetDelegate>
{
    id <TweetieDraftsViewControllerDelegate> delegate;
    TwitterAccount *account;
    NSString *filterString;
    NSArray *filteredDrafts;
    UIBarButtonItem *sendAllButton;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)_updateEditState;
- (void)viewDidLoad;
- (void)_updateFilteredDrafts;
- (void)viewWillAppear:(BOOL)arg1;
- (void)compose:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)draftAddedNotification:(id)arg1;
- (void)searchDisplayController:(id)arg1 didLoadSearchResultsTableView:(id)arg2;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)compositionAtIndex:(int)arg1 inTableView:(id)arg2;
- (void)_sendAll;
- (void)sendAll:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
@property(nonatomic) id <TweetieDraftsViewControllerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

