/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class NSMutableSet, TweetieFindFriendsViewController, TwitterAccount, UIImageView, UILabel, UIView;

@interface TweetieSULViewController : ABStaticTableViewController
{
    TwitterAccount *account;
    BOOL welcomeMode;
    int lastCounter;
    NSMutableSet *simpleFollowSet;
    UILabel *counterLabel;
    UIView *transitionCounterView;
    UIImageView *signupHeaderView;
    UIImageView *shadow;
    UIView *signupContainer;
    TweetieFindFriendsViewController *_findFriendsController;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (int)tableViewStyle;
- (void)loadTableView;
- (int)currentFollowCount;
- (void)_setupWelcomeHeader;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_showUsersInCategory:(id)arg1;
- (void)_findFriends:(id)arg1;
- (void)categoriesDidUpdate:(id)arg1;
- (BOOL)automaticallyDeselect;
@property(nonatomic) BOOL welcomeMode; // @synthesize welcomeMode;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

