/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TouchAndHoldCellDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class ABGrowingTextView, TweetieDirectMessageCell, TwitterAccount, TwitterComposition, TwitterDirectMessageConversation, UIActionSheet, UIBarButtonItem, UIImageView, UILabel, UITableView, UIView;

@interface TweetieConversationViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UIActionSheetDelegate, UITextViewDelegate, TouchAndHoldCellDelegate>
{
    TwitterAccount *account;
    TwitterDirectMessageConversation *conversation;
    UITableView *_tableView;
    UIBarButtonItem *sendButton;
    UIBarButtonItem *actionButton;
    UIActionSheet *_retrySheet;
    TwitterComposition *compositionToRetry;
    UIActionSheet *_deleteSheet;
    UIActionSheet *_actionSheet;
    UIView *composeBar;
    ABGrowingTextView *composeTextView;
    UILabel *counter;
    UIImageView *composeBubble;
    TwitterComposition *composition;
    id linkSheetHelper;
    float lastBottomOffset;
    struct CGRect keyboardFrame;
    TweetieDirectMessageCell *selectedCell;
    BOOL showLoadingSpinner;
    struct {
        unsigned int didRecordImpression:1;
    } _flags;
}

+ (id)controllerWithConversation:(id)arg1 account:(id)arg2;
+ (BOOL)recipient:(id)arg1 conversingWith:(id)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)scrollToBottomAnimated:(BOOL)arg1;
- (void)updateCounter;
- (void)refreshComposer;
- (void)textViewDidChange:(id)arg1;
- (void)fitTextView;
- (void)fitTableView;
- (void)fitComposeBar;
- (float)textViewWidthWithLabel:(BOOL)arg1;
- (void)setupComposeBar;
- (void)fitComposeBubble;
- (float)keyboardHeightForOrientation:(int)arg1;
- (float)keyboardHeight;
- (void)textViewDidBeginEditing:(id)arg1;
- (void)textViewDidEndEditing:(id)arg1;
- (void)loadView;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)arg1;
- (void)ab_attemptToRecordImpressionFromReferringEvent:(id)arg1;
- (void)ab_resetImpression;
- (void)updateSuggestiveLanguage;
- (void)keyboardLanguageDidChange:(id)arg1;
- (void)directMessageManagerDidUpdate:(id)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)deleteConversation:(id)arg1;
- (void)user:(id)arg1;
- (void)action:(id)arg1;
- (void)sendMessage:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)reply:(id)arg1;
- (void)conversationDidUpdate:(id)arg1;
- (id)messageAtIndex:(int)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)didTouchFailedSendButton:(id)arg1 info:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)didCopyDirectMessageText:(id)arg1;
- (void)viewUserDetails:(id)arg1;
- (void)didTouchAndHoldForCell:(id)arg1;
@property(nonatomic) BOOL showLoadingSpinner; // @synthesize showLoadingSpinner;
@property(retain, nonatomic) TwitterDirectMessageConversation *conversation; // @synthesize conversation;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

