/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class ABCallback, ABHUD, TwitterAccount, TwitterList, UIBarButtonItem, UITextField;

@interface TweetieNewListViewController : ABStaticTableViewController <UITextFieldDelegate>
{
    TwitterAccount *account;
    TwitterList *editList;
    UITextField *nameField;
    UITextField *descriptionField;
    UIBarButtonItem *saveButton;
    ABHUD *hud;
    ABCallback *dismissCallback;
    int privacySetting;
    CDStruct_8c7a4130 _flags;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (BOOL)shouldEdit;
- (void)loadTableView;
- (void)selectPrivacySetting:(id)arg1 info:(id)arg2;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (BOOL)canSave;
- (void)_update;
- (void)save:(id)arg1;
- (void)didCreateList:(id)arg1 info:(id)arg2;
- (void)didUpdateList:(id)arg1 info:(id)arg2;
- (void)cancel:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldClear:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
@property(retain, nonatomic) ABCallback *dismissCallback; // @synthesize dismissCallback;
@property(retain, nonatomic) TwitterList *editList; // @synthesize editList;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

