/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieComposeViewController.h"

#import "ABPlacePickerDelegate-Protocol.h"

@interface TweetieComposeViewController (Geo) <ABPlacePickerDelegate>
- (BOOL)shouldAutoGeoTag;
- (void)handleAutomaticGeoTagging;
- (void)_updateGeoButton;
- (void)promptToEnableGeo;
- (void)enableGeotag:(id)arg1 info:(id)arg2;
- (void)didEnableGeo:(id)arg1 info:(id)arg2;
- (void)startGeoTag;
- (void)gpsUpdate:(id)arg1 info:(id)arg2;
- (void)_disableGeotagging;
- (BOOL)geoEnabled;
- (void)enableGeo:(id)arg1;
- (void)disableGeo:(id)arg1;
- (void)setGeoEnabled:(BOOL)arg1;
- (void)toggleGeo:(id)arg1;
- (void)userDidFinishPickingPlace:(id)arg1;
@end

