/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UITextField;

@interface TweetieAddAccountAdvancedViewController : ABStaticTableViewController <UITextFieldDelegate>
{
    id <TweetieAddAccountAdvancedViewControllerDelegate> delegate;
    NSString *apiEndpointText;
    NSString *searchAPIEndpointText;
    UITextField *apiEndpointField;
    UITextField *searchAPIEndpointField;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)loadTableView;
- (void)viewDidLoad;
@property(copy, nonatomic) NSString *apiEndpointText; // @synthesize apiEndpointText;
@property(copy, nonatomic) NSString *searchAPIEndpointText; // @synthesize searchAPIEndpointText;
- (void)viewWillDisappear:(BOOL)arg1;
@property(nonatomic) id <TweetieAddAccountAdvancedViewControllerDelegate> delegate; // @synthesize delegate;

@end

