/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class NSMutableDictionary, TwitterUser;

@interface TweetieUserPerAccountToggleViewController : ABStaticTableViewController
{
    id <TweetieUserPerAccountToggleViewControllerDelegate> delegate;
    TwitterUser *user;
    NSMutableDictionary *perAccountToggleStateDictionary;
}

- (id)init;
- (void)dealloc;
- (id)keyForAccount:(id)arg1;
- (id)footerText;
- (void)loadTableView;
- (void)requestToggleStateForAccount:(id)arg1;
- (void)viewDidLoad;
- (void)isToggledResponse:(id)arg1 info:(id)arg2;
- (void)done:(id)arg1;
- (void)toggleOnFromAccount:(id)arg1;
- (void)toggleOffFromAccount:(id)arg1;
- (void)didCheckmarkElement:(id)arg1;
@property(nonatomic) id <TweetieUserPerAccountToggleViewControllerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;

@end

