/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "SMSStyleConversationCell.h"

@class TwitterDirectMessageConversation;

@interface TweetieConversationCell : SMSStyleConversationCell
{
    TwitterDirectMessageConversation *conversation;
}

- (void)dealloc;
@property(retain, nonatomic) TwitterDirectMessageConversation *conversation; // @synthesize conversation;
- (void)userDidUpdate:(id)arg1;

@end

