/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, TwitterScribe, UIBarButtonItem, UITextField;

@interface TweetieSignUpViewController : ABStaticTableViewController <UITextFieldDelegate>
{
    id <TweetieSignUpViewControllerDelegate> delegate;
    UITextField *fullNameField;
    UITextField *usernameField;
    UITextField *emailField;
    UITextField *passwordField;
    UIBarButtonItem *cancelButton;
    UIBarButtonItem *signUpButton;
    NSString *captchaToken;
    NSString *captchaSolution;
    int signupRetries;
    TwitterScribe *scribe;
    struct {
        unsigned int isCreatingAccount:1;
    } _flags;
}

- (void)dealloc;
- (void)loadTableView;
- (void)usernameInfo:(id)arg1;
- (void)cancel:(id)arg1;
- (void)termsOfService:(id)arg1;
- (void)privacyPolicy:(id)arg1;
- (BOOL)canSignup;
- (void)signUp:(id)arg1;
- (void)makeSignupCall;
- (void)enableButtons;
- (void)signupResponse:(id)arg1 info:(id)arg2;
- (void)captchaConfirm:(id)arg1 info:(id)arg2;
- (void)_updateSignUpButton;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
@property(retain, nonatomic) NSString *captchaSolution; // @synthesize captchaSolution;
@property(retain, nonatomic) NSString *captchaToken; // @synthesize captchaToken;
@property(nonatomic) id <TweetieSignUpViewControllerDelegate> delegate; // @synthesize delegate;

@end

