/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterCommonAppDelegate.h"

@class NSString, TweetieNavigationController, TwitterComposition, UIWindow;

@interface Tweetie2AppDelegate : TwitterCommonAppDelegate
{
    UIWindow *window;
    TweetieNavigationController *navigationController;
    TwitterComposition *currentComposition;
    NSString *lastComposeAccountUsername;
}

- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)_logLoadedViewController;
- (void)_resetImpressionLog;
- (void)_handleOpenURL:(id)arg1;
- (void)_saveState;
- (void)dealloc;
@property(retain, nonatomic) TweetieNavigationController *navigationController; // @synthesize navigationController;
@property(copy, nonatomic) NSString *lastComposeAccountUsername; // @synthesize lastComposeAccountUsername;
@property(retain, nonatomic) TwitterComposition *currentComposition; // @synthesize currentComposition;

@end

