/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@interface TweetiePlaceMapTapDetector : UIView
{
    id <TweetiePlaceMapTapDetectorDelegate> delegate;
}

- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
@property(nonatomic) id <TweetiePlaceMapTapDetectorDelegate> delegate; // @synthesize delegate;

@end

