/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIDocumentInteractionControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class TwitterCompositionAttachment;

@interface TweetieComposeAttachmentsViewController : UITableViewController <UIActionSheetDelegate, UINavigationControllerDelegate, UIDocumentInteractionControllerDelegate>
{
    TwitterCompositionAttachment *_selectedAttachment;
    id <TweetieComposeAttachmentsViewControllerDelegate> attachmentsDelegate;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)account;
- (id)composition;
- (void)_updateTitle;
- (void)viewDidLoad;
- (void)addAttachment:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)attachmentAtIndex:(int)arg1;
- (BOOL)promptForAddAttachment;
- (BOOL)isValidIndex:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)addAttachmentText;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)movieFinishedCallback:(id)arg1;
- (void)didEditVideo:(id)arg1 info:(id)arg2;
@property(nonatomic) id <TweetieComposeAttachmentsViewControllerDelegate> attachmentsDelegate; // @synthesize attachmentsDelegate;

@end

