/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "MKMapViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class ABHUD, NSArray, NSString, TweetieAddPlaceViewController, TwitterAccount, TwitterPlace;

@interface TweetieSimilarPlacesViewController : ABStaticTableViewController <MKMapViewDelegate, UITextFieldDelegate>
{
    TwitterPlace *pickedPlace;
    NSString *placeName;
    NSString *placeAddress;
    NSArray *similarPlaces;
    NSString *token;
    NSString *containedWithin;
    TweetieAddPlaceViewController *addPlaceController;
    ABHUD *hud;
    TwitterAccount *account;
}

- (id)init;
- (void)dealloc;
- (void)loadTableView;
- (void)viewDidLoad;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)save:(id)arg1;
- (void)didSelectSimilarPlace:(id)arg1;
- (void)placeDidSave:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSString *containedWithin; // @synthesize containedWithin;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;
@property(retain, nonatomic) TweetieAddPlaceViewController *addPlaceController; // @synthesize addPlaceController;
@property(retain, nonatomic) NSString *token; // @synthesize token;
@property(retain, nonatomic) NSArray *similarPlaces; // @synthesize similarPlaces;
@property(retain, nonatomic) NSString *placeAddress; // @synthesize placeAddress;
@property(retain, nonatomic) NSString *placeName; // @synthesize placeName;
@property(retain, nonatomic) TwitterPlace *pickedPlace; // @synthesize pickedPlace;

@end

