/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class TweetieStatusCell, UIButton;

@interface TweetieStatusCellContextView : UIView
{
    TweetieStatusCell *statusCell;
    UIButton *replyButton;
    UIButton *linkButton;
    UIButton *userButton;
    UIButton *retweetButton;
    UIButton *favoriteButton;
    UIButton *actionButton;
}

- (struct CGRect)frameForIndex:(int)arg1;
- (id)imageForButton:(int)arg1;
- (id)accessibilityLabelForButton:(int)arg1;
- (id)button:(int)arg1;
- (BOOL)shouldEnableLinkButton;
- (BOOL)shouldEnableRetweetButton;
- (id)initWithFrame:(struct CGRect)arg1 statusCell:(id)arg2;
- (void)setupButtons;
- (void)layoutSubviews;
- (void)animate:(id)arg1 delay:(float)arg2;
- (void)animateIn;
- (void)drawRect:(struct CGRect)arg1;
- (void)contextAction:(id)arg1;

@end

