/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABWebViewController.h"

@class ABCallback, TwitterAccount;

@interface TweetieConfigureGeotagViewController : ABWebViewController
{
    TwitterAccount *account;
    ABCallback *callback;
}

- (void)dealloc;
- (void)viewDidLoad;
- (void)done:(id)arg1;
@property(retain, nonatomic) ABCallback *callback; // @synthesize callback;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

