/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class ABActiveTextRanges, NSDate, NSString, TwitterComposition, TwitterUser;

@interface TwitterDirectMessage : NSObject <NSCoding>
{
    NSString *messageID;
    NSString *text;
    NSString *originalText;
    NSDate *date;
    TwitterUser *sender;
    TwitterUser *recipient;
    ABActiveTextRanges *originalTextRanges;
    ABActiveTextRanges *activeTextRanges;
    TwitterComposition *composition;
    struct {
        unsigned int didGlobalNotification:1;
        unsigned int read:1;
    } _flags;
}

+ (id)messageWithDictionary:(id)arg1;
+ (id)messageWithXML:(id)arg1;
+ (id)messagesWithXML:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (int)compare:(id)arg1;
@property(copy, nonatomic) NSString *originalText;
@property(copy, nonatomic) NSString *text; // @synthesize text;
@property(nonatomic) BOOL didGlobalNotification;
@property(nonatomic) BOOL read;
- (BOOL)matchesSearchString:(id)arg1;
@property(retain, nonatomic) TwitterComposition *composition; // @synthesize composition;
@property(readonly, nonatomic) ABActiveTextRanges *activeTextRanges; // @synthesize activeTextRanges;
@property(readonly, nonatomic) ABActiveTextRanges *originalTextRanges; // @synthesize originalTextRanges;
@property(retain, nonatomic) TwitterUser *recipient; // @synthesize recipient;
@property(retain, nonatomic) TwitterUser *sender; // @synthesize sender;
@property(copy, nonatomic) NSDate *date; // @synthesize date;
@property(copy, nonatomic) NSString *messageID; // @synthesize messageID;

@end

