/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "MKAnnotation-Protocol.h"
#import "NSCoding-Protocol.h"

@class NSDate, NSMutableArray, NSNumber, NSString;

@interface TwitterPlace : NSObject <NSCoding, MKAnnotation>
{
    NSString *placeID;
    NSString *fullName;
    NSString *name;
    NSString *streetAddress;
    NSDate *timestamp;
    int placeType;
    NSNumber *latitude;
    NSNumber *longitude;
    NSString *cityID;
    double accuracy;
    NSMutableArray *boundingBox;
    NSMutableArray *polylines;
    NSMutableArray *polygonPoints;
    NSMutableArray *containedWithin;
    int geometryType;
    struct {
        unsigned int fullPlace:1;
    } _flags;
}

+ (id)nearByPlaces;
+ (id)currentCoordinatePlace;
+ (void)refreshNearbyPlacesForAccount:(id)arg1;
+ (void)cancelRefreshNearbyPlaces;
+ (void)startGPSUpdatesForAccount:(id)arg1;
+ (void)endGPSUpdates;
+ (void)currentLocationResponse:(id)arg1 account:(id)arg2;
+ (void)requestNearbyPlacesForAccount:(id)arg1;
+ (void)findPlacesFromCurrentCoordinatePlaceForAccount:(id)arg1;
+ (void)topPlacesFromCurrentCoordinatePlace;
+ (void)topPlacesFromReverseGeocode:(id)arg1 info:(id)arg2;
+ (void)saveAutocompletePlaces:(id)arg1;
+ (void)placesDidLoad:(id)arg1 info:(id)arg2;
+ (void)nearbyPlacesDidLoad:(id)arg1 info:(id)arg2;
+ (void)_refreshNearbyPlacesTimeout;
+ (id)placesWithJSON:(id)arg1;
+ (id)placeWithJSON:(id)arg1;
+ (void)parseJSON:(id)arg1 info:(id)arg2;
+ (void)parsePlacesJSON:(id)arg1 info:(id)arg2;
+ (id)placeWithDictionary:(id)arg1;
+ (id)globalGeoSearchParams:(id)arg1;
- (void)saveAutocompletePlace;
- (id)init;
- (id)initCoordinateWithLatitude:(double)arg1 andLongitude:(double)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (double)distanceToLatitude:(double)arg1 longitude:(double)arg2;
- (double)distanceToPlace:(id)arg1;
- (void)parsePlaceXML:(id)arg1 info:(id)arg2;
- (void)parsePlaceJSON:(id)arg1 info:(id)arg2;
- (void)parsePolylines:(id)arg1 info:(id)arg2;
- (void)parseBoundingBoxJSON:(id)arg1 info:(id)arg2;
- (void)parseCoordinatesArrayJSON:(id)arg1 info:(id)arg2;
- (void)parseGeometryJSON:(id)arg1 info:(id)arg2;
- (void)prepare;
- (void)parseCoordinatesJSON:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *fullName; // @synthesize fullName;
- (id)description;
- (id)parseXMLCallback;
- (void)parseXML:(id)arg1 info:(id)arg2;
- (id)placeSubtext;
- (void)setCoordinate:(CDStruct_2c43369c)arg1;
- (id)annotationViewForMapView:(id)arg1;
@property(readonly, nonatomic) CDStruct_2c43369c coordinate;
- (id)title;
- (id)subtitle;
- (CDStruct_2f492f29)_POIRegion;
- (double)_latDelta;
- (double)_lonDelta;
- (CDStruct_2f492f29)_boundingBoxRegion;
- (double)boundingBoxRadius;
- (CDStruct_2c43369c)boundingBoxCenter;
- (CDStruct_2f492f29)region;
- (id)polygonOverlay;
- (id)geoSearchParams;
- (id)geoSearchParamsWithAutocompleteQuery:(id)arg1;
- (id)reverseGeocodeParams;
- (id)topPlacesParams;
@property(nonatomic) BOOL isFullPlace;
@property(retain, nonatomic) NSMutableArray *containedWithin; // @synthesize containedWithin;
@property(nonatomic) int geometryType; // @synthesize geometryType;
@property(retain, nonatomic) NSMutableArray *polygonPoints; // @synthesize polygonPoints;
@property(retain, nonatomic) NSMutableArray *polylines; // @synthesize polylines;
@property(retain, nonatomic) NSMutableArray *boundingBox; // @synthesize boundingBox;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp;
@property(nonatomic) double accuracy; // @synthesize accuracy;
@property(retain, nonatomic) NSNumber *longitude; // @synthesize longitude;
@property(retain, nonatomic) NSNumber *latitude; // @synthesize latitude;
@property(nonatomic) int placeType; // @synthesize placeType;
@property(retain, nonatomic) NSString *streetAddress; // @synthesize streetAddress;
@property(retain, nonatomic) NSString *placeID; // @synthesize placeID;

@end

