/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterEntity.h"

@class NSString;

@interface TwitterEntityPromotedContent : TwitterEntity
{
    NSString *impressionID;
}

- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (void)parseEntityJSON:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSString *impressionID; // @synthesize impressionID;

@end

