/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterPlace.h"

@interface TwitterPlace (TableViewCells)
+ (id)cellIdentifier;
+ (id)dequeueCellForTableView:(id)arg1;
- (id)cellForTableView:(id)arg1;
@end

