/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (SavedSearches)
- (BOOL)isLoadingSavedSearches;
- (void)updateSavedSearches;
- (void)savedSearchesResponse:(id)arg1 info:(id)arg2;
- (id)savedSearches;
- (BOOL)containsSavedSearch:(id)arg1;
- (void)addSavedSearch:(id)arg1;
- (void)addSavedSearchResponse:(id)arg1 info:(id)arg2;
- (void)removeSavedSearch:(id)arg1;
- (void)removeSavedSearchResponse:(id)arg1 info:(id)arg2;
@end

