/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABCallback, NSString, TwitterAccount;

@interface TwitterAPI : NSObject
{
    NSString *apiRoot;
    TwitterAccount *authenticateWithAccount;
    ABCallback *responseCallback;
}

+ (id)requestWithAPIRoot:(id)arg1 callback:(id)arg2;
+ (id)authenticatedRequestWithAPIRoot:(id)arg1 account:(id)arg2 callback:(id)arg3;
- (id)initWithAccount:(id)arg1 apiRoot:(id)arg2 callback:(id)arg3;
- (void)dealloc;

@end

