/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (PromotedContent)
- (void)logPromotedTweet:(id)arg1 event:(int)arg2;
- (void)didLogPromotedTweet:(id)arg1 info:(id)arg2;
- (void)searchForPromotedTweets:(id)arg1;
- (void)didReceivePromotedTweets:(id)arg1 info:(id)arg2;
- (void)logPromotedTrend:(id)arg1 event:(int)arg2;
- (void)logPromotedTrend:(id)arg1 event:(int)arg2 extraParameters:(id)arg3;
- (void)didLogPromotedTrend:(id)arg1 info:(id)arg2;
@end

