/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (FriendshipMethods)
- (void)followUserID:(id)arg1;
- (void)followUsername:(id)arg1;
- (void)followUsernames:(id)arg1;
- (void)lookupRelationships:(id)arg1;
- (void)unfollowUserID:(id)arg1;
- (void)unfollowUsername:(id)arg1;
- (void)relationshipsResponse:(id)arg1 info:(id)arg2;
- (id)relationshipsResponseCallback;
- (id)friendshipExistsCallback;
- (id)friendshipInfoCallback;
- (void)userID:(id)arg1 followsUserID:(id)arg2;
- (void)friendshipForSourceUserID:(id)arg1 targetUserID:(id)arg2;
- (void)friendshipForSourceUsername:(id)arg1 targetUsername:(id)arg2;
- (void)username:(id)arg1 followsUsername:(id)arg2;
- (void)friendshipInfo:(id)arg1 info:(id)arg2;
- (void)parseFriendshipInfoXML:(id)arg1 info:(id)arg2;
- (void)parseFriendshipInfoSourceXML:(id)arg1 info:(id)arg2;
- (void)friendshipExists:(id)arg1 info:(id)arg2;
@end

