/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (Private)
+ (id)platform;
+ (id)currentOSVersion;
+ (id)userAgent;
- (id)apiRoot;
- (id)baseURL;
- (id)apiRoot_v1;
- (id)username;
- (id)baseRequest;
- (id)baseRequestWithPartialURL:(id)arg1 apiRoot:(id)arg2;
- (void)attachCredentials:(id)arg1;
- (id)request:(id)arg1 apiRoot:(id)arg2 method:(id)arg3 body:(id)arg4 multiPartFormData:(id)arg5 persistent:(BOOL)arg6 callback:(id)arg7 start:(BOOL)arg8;
- (void)request:(id)arg1 method:(id)arg2 body:(id)arg3 multiPartFormData:(id)arg4 persistent:(BOOL)arg5 callback:(id)arg6;
- (void)POST:(id)arg1 multiPartFormData:(id)arg2 callback:(id)arg3;
- (void)POST:(id)arg1 body:(id)arg2 callback:(id)arg3;
- (void)persistentPOST:(id)arg1 body:(id)arg2 callback:(id)arg3;
- (void)GET:(id)arg1 callback:(id)arg2;
- (void)v1_request:(id)arg1 method:(id)arg2 body:(id)arg3 multiPartFormData:(id)arg4 persistent:(BOOL)arg5 callback:(id)arg6;
- (void)v1_POST:(id)arg1 body:(id)arg2 callback:(id)arg3;
- (void)v1_POST:(id)arg1 multiPartFormData:(id)arg2 callback:(id)arg3;
- (void)v1_persistentPOST:(id)arg1 body:(id)arg2 callback:(id)arg3;
- (void)v1_GET:(id)arg1 callback:(id)arg2;
- (void)v1_DELETE:(id)arg1 body:(id)arg2 callback:(id)arg3;
- (void)v1_DELETE:(id)arg1 callback:(id)arg2;
- (BOOL)fixBadClockSetting:(id)arg1;
- (void)requestResponse:(id)arg1 info:(id)arg2;
- (void)parseTwitterError:(id)arg1 info:(id)arg2;
- (void)invokeCallback:(id)arg1;
- (void)statusRequest:(id)arg1 sinceID:(id)arg2 maxID:(id)arg3 count:(id)arg4 page:(id)arg5;
- (id)statusesResponseCallback;
- (id)statusResponseCallback;
- (void)statusResponse:(id)arg1 info:(id)arg2;
- (void)statusesResponse:(id)arg1 info:(id)arg2;
- (id)usersResponseCallback;
- (id)userResponseCallback;
- (id)usersJSONResponseCallback;
- (void)userResponse:(id)arg1 info:(id)arg2;
- (void)_usersResponse:(id)arg1 info:(id)arg2 parser:(SEL)arg3;
- (void)usersResponse:(id)arg1 info:(id)arg2;
- (void)usersJSONResponse:(id)arg1 info:(id)arg2;
- (id)listsResponseCallback;
- (id)listResponseCallback;
- (void)listsResponse:(id)arg1 info:(id)arg2;
- (void)listResponse:(id)arg1 info:(id)arg2;
@end

