/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface TwitterPlaceResponse : NSObject
{
    NSString *token;
    NSMutableArray *places;
}

- (id)init;
- (void)dealloc;
@property(retain, nonatomic) NSMutableArray *places; // @synthesize places;
@property(retain, nonatomic) NSString *token; // @synthesize token;

@end

