/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABCallback, NSArray, NSString;

@interface TwitterAutocompleteResultsController : NSObject
{
    ABCallback *resultsCallback;
    NSString *lastPartialText;
    NSArray *lastResults;
    int lastType;
}

- (void)dealloc;
- (void)_returnResults:(id)arg1;
- (void)setLastPartialText:(id)arg1;
- (void)setLastResults:(id)arg1;
- (void)resetAutocompleteResults;
- (void)_appendSearchItem:(id)arg1 type:(int)arg2;
- (void)_appendSearchResultItems:(id)arg1 type:(int)arg2;
- (int)updateAutocompleteResults:(id)arg1 searchPlaces:(id)arg2;
- (int)updateAutocompleteResults:(id)arg1 type:(int)arg2 poiOnly:(BOOL)arg3;
@property(retain, nonatomic) ABCallback *resultsCallback; // @synthesize resultsCallback;

@end

