/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSArray, NSMutableArray, TwitterComposition, TwitterDirectMessage, TwitterUser;

@interface TwitterDirectMessageConversation : NSObject <NSCoding>
{
    TwitterUser *correspondent;
    NSMutableArray *_messages;
    NSMutableArray *_toRemove;
    TwitterComposition *composition;
    struct {
        unsigned int didAddMessage:1;
        unsigned int needsFullCorrespondant:1;
    } _flags;
}

- (id)init;
@property(nonatomic) BOOL needsFullCorrespondant;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) TwitterComposition *composition; // @synthesize composition;
@property(retain, nonatomic) NSArray *messages;
@property(readonly, nonatomic) TwitterDirectMessage *mostRecentMessage;
- (id)newestMessageNotFrom:(id)arg1;
- (int)compare:(id)arg1;
- (void)beginAddingMessages;
- (void)addMessage:(id)arg1;
- (void)endAddingMessages;
- (void)deleteMessage:(id)arg1;
- (BOOL)isRepliedTo;
- (BOOL)hasUnreadMessages;
- (void)markAsRead;
- (BOOL)matchesSearchString:(id)arg1;
- (void)sendFromAccount:(id)arg1;
- (void)_didSend:(id)arg1 info:(id)arg2;
- (void)replaceComposition:(id)arg1 withSentMessage:(id)arg2;
@property(retain, nonatomic) TwitterUser *correspondent; // @synthesize correspondent;

@end

