/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (AccountMethods)
- (void)verifyCredentials;
- (void)verifyCredentialsResponse:(id)arg1 info:(id)arg2;
- (void)getSettings;
- (void)updateSettings:(id)arg1;
- (void)settingsResponse:(id)arg1 info:(id)arg2;
- (void)updateProfileImage:(id)arg1;
- (void)rateLimitStatus;
- (void)rateLimitResponse:(id)arg1 info:(id)arg2;
- (void)updateProfileName:(id)arg1 email:(id)arg2 url:(id)arg3 location:(id)arg4 description:(id)arg5;
- (void)savedSearches;
- (void)savedSearchesResponse:(id)arg1 info:(id)arg2;
- (void)createSavedSearch:(id)arg1 named:(id)arg2;
- (void)createSavedSearchResponse:(id)arg1 info:(id)arg2;
- (void)removeSavedSearch:(id)arg1;
- (void)removeSavedSearchResponse:(id)arg1 info:(id)arg2;
@end

