/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSURL, TwitterAccount, TwitterStatus, UIActionSheet, UIActivityIndicatorView, UIBarButtonItem, UIButton, UIImageView, UILabel, UIWebView;

@interface TwitterPadWebViewController : UIViewController <UIWebViewDelegate, UIScrollViewDelegate, UIActionSheetDelegate>
{
    TwitterAccount *account;
    TwitterStatus *statusContext;
    NSURL *loadURL;
    NSURL *currentURL;
    UIWebView *_webView;
    UIBarButtonItem *back;
    UIBarButtonItem *forward;
    UIBarButtonItem *fullScreen;
    UIBarButtonItem *compose;
    UIBarButtonItem *action;
    UIBarButtonItem *pageTitle;
    UILabel *pageLabel;
    UIImageView *bg;
    UIActivityIndicatorView *spinner;
    UIButton *reloadButton;
    UIActionSheet *_actionSheet;
    BOOL hasProvidedReferer;
    struct {
        unsigned int iTunesLink:1;
        unsigned int disableBounceTillNextTrack:1;
    } _flags;
}

- (id)init;
- (void)_unlinkFromSharedWebView;
- (void)dealloc;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillBeginZooming:(id)arg1 withView:(id)arg2;
- (float)ab_swipeColumnWidth:(int)arg1;
- (BOOL)standalone;
- (void)loadView;
- (id)ab_tweetBarView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)_updateToolbar;
- (void)back:(id)arg1;
- (void)forward:(id)arg1;
- (void)reload:(id)arg1;
- (void)_beginFullscreen;
- (void)fullScreen:(id)arg1;
- (void)fullScreenDone:(id)arg1;
- (void)ab_scrollToTop;
- (void)action:(id)arg1;
- (void)actionSheet:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (void)setPageTitle:(id)arg1;
- (void)openExternalURL:(id)arg1;
- (void)shouldOpenExternalURL:(id)arg1 info:(id)arg2;
- (BOOL)shouldStartLoadWithURL:(id)arg1;
- (BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(unsigned int)arg3;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
@property(retain, nonatomic) NSURL *currentURL; // @synthesize currentURL;
@property(retain, nonatomic) NSURL *loadURL; // @synthesize loadURL;
@property(retain, nonatomic) TwitterStatus *statusContext; // @synthesize statusContext;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

