/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (NotificationMethods)
- (void)enableNotificationsForUserID:(id)arg1;
- (void)enableNotificationsForUsername:(id)arg1;
- (void)disableNotificationsForUserID:(id)arg1;
- (void)disableNotificationsForUsername:(id)arg1;
@end

