/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABCallback, NSString;

@interface TwitterSearchAPI : NSObject
{
    NSString *apiRoot;
    ABCallback *responseCallback;
}

+ (id)requestWithAPIRoot:(id)arg1 callback:(id)arg2;
- (id)initWithAPIRoot:(id)arg1 callback:(id)arg2;
- (void)dealloc;
- (id)apiRoot;
- (void)search:(id)arg1 count:(id)arg2 page:(id)arg3 sinceID:(id)arg4 geocode:(id)arg5 via:(id)arg6;
- (void)searchResponse:(id)arg1 info:(id)arg2;

@end

