/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccountStream.h"

@class TwitterUser;

@interface TwitterUserStream : TwitterAccountStream
{
    TwitterUser *user;
}

- (void)dealloc;
- (id)autosaveName;
- (id)emptyStreamMessage;
@property(nonatomic) TwitterUser *user; // @synthesize user;

@end

