/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class TwitterAccount;

@interface TwitterPadAccountDetailsViewController : ABStaticTableViewController
{
    TwitterAccount *account;
}

- (void)dealloc;
- (void)loadTableView;
- (void)removeAccount:(id)arg1;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

