/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSArray, NSMutableArray, TwitterReceivedDirectMessagesStream, TwitterSentDirectMessagesStream;

@interface TwitterDirectMessagesConversationManager : NSObject <NSCoding>
{
    TwitterReceivedDirectMessagesStream *receivedStream;
    TwitterSentDirectMessagesStream *sentStream;
    NSMutableArray *_conversations;
    struct {
        unsigned int hasUnreadMessages:1;
        unsigned int unreadBitIsFresh:1;
    } _flags;
}

- (void)_setupNotifications;
- (id)initWithAccount:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)setAccount:(id)arg1;
- (void)dealloc;
- (void)refresh;
- (void)loadOlder;
@property(readonly, nonatomic) NSArray *conversations;
- (id)conversationWith:(id)arg1;
- (void)_postDidUpdateNotification;
- (void)_addStubConversation:(id)arg1;
- (void)addMessages:(id)arg1 fromMe:(BOOL)arg2;
- (void)sentDidUpdate:(id)arg1;
- (void)receivedDidUpdate:(id)arg1;
- (id)newestMessageDate;
- (id)newestMessageNotFromMe;
- (id)newestMessageDateNotFromMe;
- (void)_deleteMessage:(id)arg1;
- (void)deleteMessage:(id)arg1;
- (void)didDeleteMessage:(id)arg1 info:(id)arg2;
- (void)deleteConversation:(id)arg1;
- (BOOL)hasUnreadMessages;
- (void)markAllAsRead;
- (void)clearCachedUnreadState;
- (id)conversationsMatching:(id)arg1;
@property(readonly, nonatomic) TwitterSentDirectMessagesStream *sentStream; // @synthesize sentStream;
@property(readonly, nonatomic) TwitterReceivedDirectMessagesStream *receivedStream; // @synthesize receivedStream;

@end

