/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterPadSidebarCell.h"

@interface TwitterPadSidebarAccountCell : TwitterPadSidebarCell
{
}

- (void)setAccount:(id)arg1;
- (void)accountDidUpdate:(id)arg1;
- (void)accountUserDidUpdate:(id)arg1;
- (BOOL)isFirst;
- (BOOL)isLast;
- (void)drawContentView:(struct CGRect)arg1;

@end

