/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStatusStreamFilter.h"

@class NSArray;

@interface TwitterStatusStreamFilterUserListFilter : TwitterStatusStreamFilter
{
    NSArray *users;
}

- (void)dealloc;
- (BOOL)validStatus:(id)arg1;
@property(copy, nonatomic) NSArray *users; // @synthesize users;

@end

