/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABImage, NSDate, NSNumber, NSString, NSURL;

@interface TwitterUser : NSObject
{
    NSDate *lastUpdated;
    NSString *userID;
    NSString *username;
    NSURL *profileImageURL;
    NSString *fullName;
    NSString *location;
    NSString *bio;
    NSURL *url;
    NSURL *expandedURL;
    NSNumber *protected;
    NSNumber *verified;
    NSNumber *numberOfFollowers;
    NSNumber *numberOfStatuses;
    NSNumber *numberOfFollowing;
    NSNumber *numberOfFavorites;
    NSDate *createdAt;
    NSNumber *following;
    ABImage *profileImage;
    struct {
        unsigned int isPartialUser:1;
        unsigned int isLoadingProfileImage:1;
        unsigned int geoEnabled:1;
    } _flags;
}

+ (id)userWithDictionary:(id)arg1;
+ (id)userWithXML:(id)arg1;
+ (id)userWithJSON:(id)arg1;
+ (id)usersWithXML:(id)arg1;
+ (id)parseUsersJSONCallback:(id)arg1;
+ (id)parseUsersXMLCallback:(id)arg1;
+ (id)usersWithJSON:(id)arg1;
+ (void)saveAutocompleteUsers:(id)arg1;
- (id)init;
- (id)parseUserXMLCallback;
- (void)dealloc;
- (id)_profileImage;
- (void)_assimilateUser:(id)arg1;
- (void)assimilateUser:(id)arg1;
- (id)description;
@property(copy, nonatomic) NSString *fullName; // @synthesize fullName;
- (int)compare:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) NSURL *largeProfileImageURL;
@property(nonatomic) BOOL isPartialUser;
- (id)lowercaseUsername;
- (BOOL)isNotADummyUser;
- (id)searchSpace;
- (BOOL)matchesSearchString:(id)arg1;
@property(readonly, nonatomic) NSURL *twitterURL;
@property(retain, nonatomic) NSNumber *following; // @synthesize following;
@property(retain, nonatomic) NSDate *createdAt; // @synthesize createdAt;
@property(retain, nonatomic) NSNumber *numberOfFavorites; // @synthesize numberOfFavorites;
@property(retain, nonatomic) NSNumber *numberOfFollowing; // @synthesize numberOfFollowing;
@property(retain, nonatomic) NSNumber *numberOfStatuses; // @synthesize numberOfStatuses;
@property(retain, nonatomic) NSNumber *numberOfFollowers; // @synthesize numberOfFollowers;
@property(retain, nonatomic) NSNumber *verified; // @synthesize verified;
@property(retain, nonatomic) NSNumber *protected; // @synthesize protected;
@property(retain, nonatomic) NSURL *expandedURL; // @synthesize expandedURL;
@property(retain, nonatomic) NSURL *url; // @synthesize url;
@property(copy, nonatomic) NSString *bio; // @synthesize bio;
@property(copy, nonatomic) NSString *location; // @synthesize location;
@property(retain, nonatomic) NSURL *profileImageURL; // @synthesize profileImageURL;
@property(copy, nonatomic) NSString *username; // @synthesize username;
@property(copy, nonatomic) NSString *userID; // @synthesize userID;
@property(retain, nonatomic) NSDate *lastUpdated; // @synthesize lastUpdated;

@end

