/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSDate;

@interface TwitterConfiguration : NSObject <NSCoding>
{
    int shortenedURLLength;
    float scribeInterval;
    NSDate *lastUpdate;
    BOOL scribeEnabled;
}

- (id)description;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)nextConfiguration;
@property(nonatomic) BOOL scribeEnabled; // @synthesize scribeEnabled;
- (void)loadMobileConfiguration:(id)arg1;
- (void)parseMobileConfiguration:(id)arg1 info:(id)arg2;
- (void)loadGlobalConfiguration:(id)arg1;
- (void)parseGlobalConfiguration:(id)arg1 info:(id)arg2;
@property(nonatomic) int shortenedURLLength; // @synthesize shortenedURLLength;
- (BOOL)needsRefresh;
- (void)finishedLoading;
- (void)dealloc;
@property(nonatomic) float scribeInterval; // @synthesize scribeInterval;
@property(readonly, nonatomic) NSDate *lastUpdate; // @synthesize lastUpdate;

@end

