/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABMasterViewController.h"

#import "ABUITextViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class ABTableViewPinchPreviewController, ABTextView, NSArray, NSMutableArray, NSString, TweetiePromotedButton, TwitterAccount, TwitterStatus, UIButton, UIImageView, UILabel, UIView, UIViewController;

@interface TwitterPadTweetViewController : ABMasterViewController <ABUITextViewDelegate, UIActionSheetDelegate>
{
    TwitterAccount *account;
    TwitterStatus *status;
    NSString *statusID;
    ABTableViewPinchPreviewController *pinchPreviewController;
    UIView *selectionBubbleContainer;
    ABTextView *textView;
    UILabel *usernameLabel;
    float textViewHeight;
    TweetiePromotedButton *promotedButton;
    id <ABActiveTextRange> selectRange;
    NSMutableArray *selectionBubbles;
    NSArray *metaActiveRanges;
    UIView *subViewBG;
    UIViewController *subViewController;
    UIImageView *shadow;
    UIView *header;
    UIImageView *avatar;
    UIView *bottomBar;
    UIView *_bottomBarSubview;
    struct {
        UIButton *reply;
        UIButton *favorite;
        UIButton *retweet;
        UIButton *action;
    } button;
    struct _NSRange _inReplyToRange;
    struct _NSRange _placeRange;
    struct _NSRange _retweeterRange;
    struct _NSRange _sourceRange;
    struct {
        unsigned int didShowFirstSubViewController:1;
        unsigned int actionSheetMode:3;
    } _flags;
}

+ (void)initialize;
+ (id)gradientButtonImage:(id)arg1 highlighted:(BOOL)arg2;
+ (void)translationResponse:(id)arg1 info:(id)arg2;
- (void)dealloc;
- (BOOL)isMediaLinkString:(id)arg1;
- (BOOL)rangeNeedsWideDisplay:(id)arg1;
- (void)_updateSelectionBubble;
- (void)_goSelected;
- (BOOL)needsWide;
- (void)_showEmailComposer:(id)arg1;
- (void)selectLink:(id)arg1;
- (void)userDetails:(id)arg1;
- (void)_updateRenderer:(BOOL)arg1;
- (id)fromPerson;
- (struct CGRect)subViewFrame;
- (id)buttonImageNamed:(id)arg1 highlighted:(BOOL)arg2;
- (void)_updateFavoritesButton;
- (void)loadView;
- (void)didClickPromotedLabel:(id)arg1 info:(id)arg2;
- (void)_updateLayout;
- (void)autoselect;
- (void)viewDidLoad;
- (void)profileImage73Response:(id)arg1 info:(id)arg2;
- (id)visibleViewControllers;
@property(retain, nonatomic) TwitterStatus *status; // @synthesize status;
- (id)activeRangesForTextRenderer:(id)arg1;
- (void)textView:(id)arg1 didTapActiveRange:(id)arg2;
- (void)ab_scrollToTop;
- (float)ab_swipeColumnWidth:(int)arg1;
- (void)_setupNewSubviewControllerView;
- (void)setSubViewController:(id)arg1 animated:(BOOL)arg2;
- (void)__replyAll;
- (void)_replyAll;
- (void)reply:(id)arg1;
- (void)retweet:(id)arg1;
- (void)favorite:(id)arg1;
- (void)action:(id)arg1;
- (void)_quoteTweet;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
@property(nonatomic) ABTableViewPinchPreviewController *pinchPreviewController; // @synthesize pinchPreviewController;
@property(retain, nonatomic) NSString *statusID; // @synthesize statusID;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

