/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "ABAutocompleteResultItem-Protocol.h"

@class NSString, NSURL;

@interface TwitterAutocompleteResultItem : NSObject <ABAutocompleteResultItem>
{
    NSString *autocompleteText;
    NSString *autocompleteSubtext;
    NSString *autocompleteImageName;
    NSURL *autocompleteImageURL;
    id userInfo;
    NSString *itemID;
    int autocompleteAction;
    int autocompleteType;
    int priority;
    NSString *_derivedSearchableText;
}

- (void)dealloc;
- (BOOL)isEqual:(id)arg1;
- (id)searchableSortableText;
@property(nonatomic) int priority; // @synthesize priority;
@property(nonatomic) int autocompleteType; // @synthesize autocompleteType;
@property(nonatomic) int autocompleteAction; // @synthesize autocompleteAction;
@property(retain, nonatomic) NSString *itemID; // @synthesize itemID;
@property(retain, nonatomic) id userInfo; // @synthesize userInfo;
@property(retain, nonatomic) NSURL *autocompleteImageURL; // @synthesize autocompleteImageURL;
@property(retain, nonatomic) NSString *autocompleteImageName; // @synthesize autocompleteImageName;
@property(retain, nonatomic) NSString *autocompleteSubtext; // @synthesize autocompleteSubtext;
@property(retain, nonatomic) NSString *autocompleteText; // @synthesize autocompleteText;

@end

