/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterPadSearchesViewController.h"

@interface TwitterPadLoggedOutViewController : TwitterPadSearchesViewController
{
}

- (BOOL)loggedOutMode;
- (void)addTopSectionTo:(id)arg1;
- (void)signIn:(id)arg1;
- (void)signUp:(id)arg1;

@end

