/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStream.h"

#import "NSCoding-Protocol.h"

@class NSArray, TwitterAccount;

@interface TwitterDirectMessagesStream : TwitterStream <NSCoding>
{
    TwitterAccount *account;
    NSArray *messages;
    int page;
    struct {
        unsigned int isLoadingNewer:1;
        unsigned int isLoadingOlder:1;
        unsigned int isAtEnd:1;
    } _flags;
}

- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)newestMessageID;
- (id)oldestMessageID;
@property(retain, nonatomic) NSArray *messages; // @synthesize messages;
- (BOOL)forceReadBit;
- (void)addMessages:(id)arg1;
- (void)deleteMessage:(id)arg1;
- (void)messagesResponse:(id)arg1 info:(id)arg2;
- (void)_loadNewer;
- (void)_loadOlder;
- (void)loadNewer;
- (void)loadOlder;
- (void)loadNewerResponse:(id)arg1 info:(id)arg2;
- (void)loadOlderResponse:(id)arg1 info:(id)arg2;
- (id)loadNewerResponseCallback;
- (id)loadOlderResponseCallback;
@property(nonatomic) TwitterAccount *account; // @synthesize account;

@end

