/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABTableViewCell.h"

@class TwitterList;

@interface TwitterPadSULCategoryCell : ABTableViewCell
{
    TwitterList *list;
}

- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;
- (void)drawContentView:(struct CGRect)arg1;
@property(retain, nonatomic) TwitterList *list; // @synthesize list;

@end

