/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterUserStream.h"

@interface TwitterUserFavoritesStream : TwitterUserStream
{
    int page;
}

- (void)_loadNewer;
- (void)_loadOlder;
- (void)didLoadOlder;
- (BOOL)supportsFillingInGaps;
- (id)autosaveName;
- (id)emptyStreamMessage;

@end

