/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString, TwitterAccount;

@interface TwitterSULCategory : NSObject
{
    NSString *slug;
    NSString *name;
    NSArray *users;
    TwitterAccount *account;
    struct {
        unsigned int loadingUsers:1;
    } _flags;
}

+ (id)parseCategoriesJSON:(id)arg1;
+ (void)parseCategoriesJSON:(id)arg1 info:(id)arg2;
- (void)dealloc;
- (void)parseCategoryJSON:(id)arg1 info:(id)arg2;
- (void)updateUsers;
- (void)didUpdateUsers:(id)arg1 info:(id)arg2;
@property(copy, nonatomic) NSArray *users; // @synthesize users;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *slug; // @synthesize slug;

@end

