/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface TwitterPlaceEntity : NSObject <NSCoding>
{
    NSString *_placeID;
    int _startIndex;
    int _endIndex;
}

- (id)initWithPlaceID:(id)arg1 startIndex:(int)arg2 endIndex:(int)arg3;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
@property(nonatomic) int endIndex; // @synthesize endIndex=_endIndex;
@property(nonatomic) int startIndex; // @synthesize startIndex=_startIndex;
@property(readonly, nonatomic) NSString *placeID; // @synthesize placeID=_placeID;

@end

