/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSMutableArray, NSTimer, TwitterAccount;

@interface Twitter : NSObject <NSCoding>
{
    NSMutableArray *accounts;
    TwitterAccount *duckie;
    NSTimer *scribeTimer;
    NSTimer *heartbeatTimer;
    double clockDelta;
}

+ (id)sharedTwitter;
- (void)heartbeat:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (void)saveStreams;
- (void)shutdown;
- (id)accounts;
- (void)signInWithUsername:(id)arg1 password:(id)arg2 callback:(id)arg3;
- (void)didSignIn:(id)arg1 info:(id)arg2;
- (void)addAccount:(id)arg1;
- (void)removeAccount:(id)arg1;
- (BOOL)containsAccount:(id)arg1;
- (id)accountWithUsername:(id)arg1;
- (id)defaultAccount;
- (void)reorderAccountFromIndex:(int)arg1 toIndex:(int)arg2;
- (void)flushScribe:(id)arg1;
- (void)flushScribeInBackground;
@property(readonly, nonatomic) TwitterAccount *duckie;
- (void)refresh;
- (BOOL)hasFreshMessages;
- (BOOL)hasFreshAnythingApplicableToStatusItem;
- (BOOL)hasFreshAnythingApplicableToDockBadge;
- (BOOL)hasAnythingUnread;
- (void)markAllAsRead;
- (id)cachedUsers;
- (BOOL)canBlock:(id)arg1;
@property(nonatomic) double clockDelta; // @synthesize clockDelta;

@end

