/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (Lists)
+ (id)SULUsernameForCurrentLanguage;
- (void)listsForUsername:(id)arg1;
- (void)lists;
- (void)listSubscriptionsForUsername:(id)arg1;
- (void)listSubscriptions;
- (void)listMembershipsForUsername:(id)arg1;
- (void)listMemberships;
- (void)createList:(id)arg1 description:(id)arg2 mode:(id)arg3;
- (void)updateList:(id)arg1 name:(id)arg2 description:(id)arg3 mode:(id)arg4;
- (void)deleteList:(id)arg1;
- (void)deleteListResponse:(id)arg1 info:(id)arg2;
- (void)listStatuses:(id)arg1 username:(id)arg2 sinceID:(id)arg3 maxID:(id)arg4 count:(id)arg5 page:(id)arg6;
- (void)listWithUsername:(id)arg1 slug:(id)arg2;
- (void)followList:(id)arg1 username:(id)arg2;
- (void)unfollowList:(id)arg1 username:(id)arg2;
- (void)list:(id)arg1 username:(id)arg2 followsUserID:(id)arg3;
- (void)listDoesFollowUser:(id)arg1 info:(id)arg2;
- (void)list:(id)arg1 username:(id)arg2 followUserID:(id)arg3;
- (void)didfollowfromlist:(id)arg1 info:(id)arg2;
- (void)list:(id)arg1 username:(id)arg2 unfollowUserID:(id)arg3;
- (void)didunfollowfromlist:(id)arg1 info:(id)arg2;
@end

