/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface TwitterChangelog : NSObject
{
}

+ (BOOL)shouldShowWhatsNew;
+ (void)didDismissWhatsNewAlert:(id)arg1 info:(id)arg2;
+ (void)showWhatsNewWithCallback:(id)arg1;
+ (void)showWhatsNewWithViewController:(id)arg1 account:(id)arg2;
+ (int)changelogVersion;
+ (void)updateChangelogVersionPreference;
+ (void)resetChangelogVersionPreference;

@end

