/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSMutableArray, TwitterAccount;

@interface TwitterScribe : NSObject <NSCoding>
{
    NSMutableArray *eventBuffer;
    TwitterAccount *account;
    int bufferSpinLock;
}

- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)logTweetSend:(id)arg1;
- (void)logTweetReply;
- (void)logTweetRetweet;
- (void)logTweetFavorite;
- (void)logTweetOpenLink:(id)arg1;
- (void)logUserFollow;
- (void)logUserUnfollow;
- (void)logNotificationOpen;
- (void)logHomeImpressionFromReferringEvent:(id)arg1 items:(id)arg2;
- (void)logAction:(id)arg1 page:(id)arg2 section:(id)arg3;
- (void)logCompositionImpression;
- (void)logFavoritesImpression;
- (void)logQuoteTweet;
- (void)logMessagesImpression;
- (void)logMessagesConversationImpression;
- (void)logMessageSend;
- (void)logUserProfileImpressionForUserID:(id)arg1;
- (void)logUserTimelineImpressionFromReferringEvent:(id)arg1 userID:(id)arg2;
- (void)logSearchesHomeImpression;
- (void)logLoggedOutHomepageImpression;
- (void)logSignUpImpression;
- (void)logSignUpFullnameFailure;
- (void)logSignUpScreenNameFailure;
- (void)logSignUpEmailFailure;
- (void)logSignUpPasswordFailure;
- (void)logSignUpTokenFailure;
- (void)logSignUpScreenNameValidationError;
- (void)logSignUpEmailValidationError;
- (void)logSignUpPasswordValidationError;
- (void)logSignUpCaptchaShow;
- (void)logSignUpServerError;
- (void)logSignUpFailure;
- (void)logSignUpSuccess;
- (void)logTweetDetailsImpressionFromReferringEvent:(id)arg1 items:(id)arg2;
- (void)logRequestResponseURL:(id)arg1 statusCode:(int)arg2 networkStatus:(int)arg3 errorMessage:(id)arg4 duration:(double)arg5;
- (void)logEvent:(id)arg1 keysAndValues:(id)arg2;
- (void)dealloc;
- (void)flush;
@property(nonatomic) TwitterAccount *account; // @synthesize account;

@end

