/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (Profile)
- (void)updateProfileImage:(id)arg1 callback:(id)arg2;
- (void)didUpdateProfileImage:(id)arg1 info:(id)arg2;
- (void)updateProfileName:(id)arg1 email:(id)arg2 url:(id)arg3 location:(id)arg4 description:(id)arg5 callback:(id)arg6;
- (void)didUpdateProfile:(id)arg1 info:(id)arg2;
@end

