/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterUser.h"

@class ABImage;

@interface TwitterUser (Avatar)
- (void)_requestProfileImage;
@property(readonly, nonatomic) ABImage *profileImage;
- (void)purgeCachedAvatar;
@property(readonly, nonatomic) ABImage *plainProfileImage;
- (void)profileImageResponsePostNotification;
- (void)profileImageResponse:(id)arg1 info:(id)arg2;
- (void)profileImage73Request:(id)arg1;
- (void)profileImage73Response:(id)arg1 info:(id)arg2;
@end

