/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABTableViewCell.h"

#import "ABUITextRendererDelegate-Protocol.h"

@class ABCallback, ABUITextRenderer, TwitterDirectMessage, TwitterPadDirectMessageConversationViewController, UIButton;

@interface TwitterPadDirectMessageCell : ABTableViewCell <ABUITextRendererDelegate>
{
    TwitterDirectMessage *message;
    ABUITextRenderer *renderer;
    TwitterPadDirectMessageConversationViewController *conversationViewController;
    UIButton *errorButton;
    ABCallback *errorCallback;
}

+ (void)initialize;
+ (float)heightForMessage:(id)arg1 inTableView:(id)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;
- (void)errorButtonTouch:(id)arg1;
@property(retain, nonatomic) TwitterDirectMessage *message; // @synthesize message;
- (void)userDidUpdate:(id)arg1;
- (struct CGRect)textRect;
- (struct CGRect)bubbleRect;
- (BOOL)drawRight;
- (void)drawContentView:(struct CGRect)arg1;
- (id)activeRanges;
- (id)activeRangesForTextRenderer:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
@property(readonly, nonatomic) UIButton *errorButton; // @synthesize errorButton;
@property(retain, nonatomic) ABCallback *errorCallback; // @synthesize errorCallback;
@property(nonatomic) TwitterPadDirectMessageConversationViewController *conversationViewController; // @synthesize conversationViewController;

@end

