/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class ABImage, NSError, NSString, NSURL;

@interface TwitterCompositionAttachment : NSObject <NSCoding>
{
    NSString *localFile;
    NSURL *localURL;
    BOOL ownsLocalFile;
    NSString *sourceDescription;
    NSURL *remoteURL;
    int size;
    struct {
        unsigned int isUploading:1;
    } _flags;
    ABImage *thumbnail;
    NSError *uploadError;
}

- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (void)setLocalFile:(id)arg1;
- (void)setLocalURL:(id)arg1;
- (void)setData:(id)arg1;
- (id)localFile;
- (id)data;
- (BOOL)isPendingUpload;
- (void)_uploadFromAccount:(id)arg1 associatedMessage:(id)arg2 callback:(id)arg3;
- (void)uploadFromAccount:(id)arg1 associatedMessage:(id)arg2 callback:(id)arg3;
- (void)didUpload:(id)arg1 info:(id)arg2;
- (void)cleanup;
- (id)title;
- (id)thumbnail;
- (int)type;
@property(retain, nonatomic) NSString *sourceDescription; // @synthesize sourceDescription;
@property(readonly, nonatomic) int size; // @synthesize size;
@property(retain, nonatomic) NSError *uploadError; // @synthesize uploadError;
@property(retain, nonatomic) NSURL *remoteURL; // @synthesize remoteURL;

@end

