/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterPadSidebarCell.h"

@interface TwitterPadSidebarItemCell : TwitterPadSidebarCell
{
}

- (BOOL)isLast;
- (id)itemTitle;
- (id)itemImageName;
- (id)itemImage;
- (id)highlightedItemImage;
- (BOOL)_isSubitem;
- (void)drawContentView:(struct CGRect)arg1;

@end

