/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate, TwitterUser;

@interface TwitterStreamEvent : NSObject
{
    TwitterUser *source;
    TwitterUser *target;
    id targetObject;
    int eventType;
    NSDate *date;
}

+ (id)keepAlive;
+ (id)eventFromDictionary:(id)arg1;
+ (id)retweetEvent:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSDate *date; // @synthesize date;
@property(retain, nonatomic) id targetObject; // @synthesize targetObject;
@property(retain, nonatomic) TwitterUser *target; // @synthesize target;
@property(retain, nonatomic) TwitterUser *source; // @synthesize source;
@property(nonatomic) int eventType; // @synthesize eventType;

@end

