/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIButton.h"

@class NSNumber, TwitterUser;

@interface TwitterUserListFollowUnfollowButton : UIButton
{
    TwitterUser *user;
    NSNumber *isFollowButton;
}

@property(copy, nonatomic) NSNumber *isFollowButton; // @synthesize isFollowButton;
@property(nonatomic) TwitterUser *user; // @synthesize user;

@end

