/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABImageService.h"

@interface TwitPicCompatibleImageService : ABImageService
{
}

+ (id)identifierForURL:(id)arg1 base:(id)arg2;
- (id)apiRoot;
- (id)apiKey;
- (id)apiKeyParameterName;
- (id)mediaParameterName;
- (id)mediaURLResponseTag;
- (id)messageParameterName;
- (BOOL)useBasicAuth;
- (BOOL)useOAuthEcho;
- (id)OAuthEchoServiceProvider;
- (id)OAuthEchoAuthorizationHeaderForAccount:(id)arg1;
- (void)addMoarStuff:(id)arg1;
- (BOOL)OAuthEchoInPOST;
- (void)postImage:(id)arg1 associatedMessage:(id)arg2 fromAccount:(id)arg3 callback:(id)arg4;
- (void)postVideo:(id)arg1 associatedMessage:(id)arg2 fromAccount:(id)arg3 callback:(id)arg4;
- (void)didPostImage:(id)arg1 info:(id)arg2;
- (void)parseYFrogXML:(id)arg1 info:(id)arg2;

@end

