/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIActionSheet.h"

@interface UIActionSheet (UIActionSheetAdditions)
+ (void)showActionSheetWithTitle:(id)arg1 button:(id)arg2 cancelButton:(id)arg3 fromView:(id)arg4 buttonCallback:(id)arg5;
@end

