/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIAlertView.h"

@interface UIAlertView (UIAlertViewAdditions)
+ (void)_setupAttributionTextForAlertView:(id)arg1;
+ (void)showAlertViewWithTitle:(id)arg1 message:(id)arg2 dismissButtonTitle:(id)arg3 dismissCallback:(id)arg4;
+ (void)showAlertViewWithTitle:(id)arg1 message:(id)arg2 buttonTitle:(id)arg3 cancelButtonTitle:(id)arg4 dismissCallback:(id)arg5;
+ (id)newMaliciousWarning:(id)arg1;
+ (void)showAlertViewWithTitle:(id)arg1 message:(id)arg2 dismissButtonTitle:(id)arg3;
+ (void)showAlertWithError:(id)arg1;
+ (void)showAlertWithError:(id)arg1 dismissCallback:(id)arg2;
@end

