/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class UILabel, UISlider, UISwitch, UITextField;

@interface UITableViewCell (ABAdditions)
@property(readonly, nonatomic) UISwitch *accessorySwitch;
@property(readonly, nonatomic) UITextField *accessoryTextField;
@property(readonly, nonatomic) UISlider *accessorySlider;
@property(readonly, nonatomic) UILabel *multilineLabel;
@end

