/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableView.h"

@interface UITableView (ABAdditions)
- (id)_dequeueCellStyle:(int)arg1 class:(Class)arg2 reuseIdentifier:(id)arg3;
- (id)dequeueCustomCellWithStyle:(int)arg1 class:(Class)arg2 reuseIdentifier:(id)arg3;
- (id)dequeueCustomCellWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)dequeueCustomDefaultCell:(id)arg1;
- (id)dequeueDefaultCell;
- (id)dequeueValue1Cell;
- (id)dequeueValue2Cell;
- (id)dequeueSubtitleCell;
- (id)dequeueLoadingCell;
- (id)dequeueProgressCell;
- (id)dequeueCenteredSpinnerCell;
- (id)dequeueSwitchCell;
- (id)dequeueSliderCell;
- (id)dequeueButtonCell;
- (id)dequeueTextFieldContainerCell;
- (id)dequeueMultilineLabelCell;
- (id)dequeueExpandingCell;
- (id)dequeueCollapsingCell;
@end

