/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

@class ABSwipeColumnViewController;

@interface UIViewController (ABColumnViewControllerAdditions)
@property(readonly, nonatomic) ABSwipeColumnViewController *ab_columnViewController;
- (void)_ab_setColumnViewController:(id)arg1;
@property(readonly, nonatomic) UIViewController *ab_superColumn;
- (void)_ab_setSuperColumn:(id)arg1;
- (void)ab_pushColumn:(id)arg1 animated:(BOOL)arg2;
@end

