/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSString;

@protocol ABActiveTextRange <NSObject, NSCopying>
@property(readonly, nonatomic) NSString *displayString;
@property(readonly, nonatomic) int rangeFlavor;
@property(readonly, nonatomic) struct _NSRange rangeValue;
@end

