/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABTableViewCell.h"

@class UIImage;

@interface ABAutocompleteTableViewCell : ABTableViewCell
{
    id <ABAutocompleteResultItem> autocompleteItem;
    UIImage *_loadedImage;
    BOOL _loadingImage;
}

- (void)dealloc;
@property(retain, nonatomic) id <ABAutocompleteResultItem> autocompleteItem; // @synthesize autocompleteItem;
- (void)drawContentView:(struct CGRect)arg1;
- (void)_loadedImageData:(id)arg1 forItem:(id)arg2;

@end

