/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableView.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray;

@interface ABAutocompleteTableView : UITableView <UITableViewDelegate, UITableViewDataSource>
{
    NSArray *autocompleteItems;
    id <ABAutocompleteTableViewDelegate> autocompleteDelegate;
}

- (id)initWithFrame:(struct CGRect)arg1 style:(int)arg2;
- (void)dealloc;
- (void)scrollViewDidScroll:(id)arg1;
@property(copy, nonatomic) NSArray *autocompleteItems; // @synthesize autocompleteItems;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
@property(nonatomic) id <ABAutocompleteTableViewDelegate> autocompleteDelegate; // @synthesize autocompleteDelegate;

@end

