/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@class NSString, NSURL;

@protocol ABAutocompleteResultItem <NSObject>
- (id)searchableSortableText;
@property(nonatomic) int priority;
@property(nonatomic) int autocompleteType;
@property(nonatomic) int autocompleteAction;
@property(retain, nonatomic) NSString *itemID;
@property(retain, nonatomic) id userInfo;
@property(retain, nonatomic) NSURL *autocompleteImageURL;
@property(retain, nonatomic) NSString *autocompleteImageName;
@property(retain, nonatomic) NSString *autocompleteSubtext;
@property(retain, nonatomic) NSString *autocompleteText;
@end

