/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABProxy.h"

@class ABReturnProxy;

@interface ABBackgroundProxy : ABProxy
{
    ABReturnProxy *returnProxy;
    int spinLock;
    BOOL invocationCount;
    BOOL hasReturnValue;
}

- (void)dealloc;
- (void)forwardInvocation:(id)arg1;
- (void)performInvocationInBackground:(id)arg1;

@end

