/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class ABColumnItem, NSArray, UIToolbar;

@interface ABColumnBar : UIView
{
    id delegate;
    NSArray *items;
    ABColumnItem *_dummyBackToRootItem;
    UIView *currentBackButtonView;
    UIView *currentLeftTitleView;
    UIView *currentRightTitleView;
    struct {
        NSArray *removeViews;
    } transition;
    UIView *divider;
    UIToolbar *toolbar;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)backItem;
- (id)leftItem;
- (id)rightItem;
- (struct CGRect)backButtonFrame:(struct CGRect)arg1;
- (struct CGRect)leftTitleFrame;
- (struct CGRect)dividerFrame;
- (struct CGRect)rightTitleFrame;
- (struct CGRect)toolbarFrame;
- (void)_updateLayout;
- (void)layoutSubviews;
- (void)pop:(id)arg1;
- (void)_updateToolbarItems:(id)arg1 animated:(BOOL)arg2;
- (void)_itemDidUpdate:(id)arg1;
- (void)setItems:(id)arg1 animated:(BOOL)arg2;
- (void)_finishTransition;
- (void)endSetItemsAnimation:(id)arg1 finished:(id)arg2 context:(void *)arg3;
@property(nonatomic) id delegate; // @synthesize delegate;

@end

