/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UIWebViewDelegate-Protocol.h"

@class UIWebView;

@interface ABDocumentDisplayController : UIViewController <UIWebViewDelegate>
{
    UIWebView *_webView;
}

- (void)dealloc;
- (void)loadView;
- (void)viewDidUnload;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)documentPath;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;

@end

