/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "ABActiveTextRange-Protocol.h"

@class NSString;

@interface ABFlavoredRange : NSObject <ABActiveTextRange>
{
    NSString *displayString;
    struct _NSRange rangeValue;
    int rangeFlavor;
}

+ (id)valueWithRange:(struct _NSRange)arg1;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(readonly, nonatomic) int rangeFlavor;
- (void)setRangeFlavor:(int)arg1;
@property(readonly, nonatomic) NSString *displayString;
- (void)setDisplayString:(id)arg1;
@property(nonatomic) struct _NSRange rangeValue; // @synthesize rangeValue;

@end

