/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSError;

@interface ABGeocode : NSObject
{
    NSError *error;
    NSArray *geocodedLocations;
}

+ (void)geocode:(id)arg1 callback:(id)arg2;
- (void)dealloc;
- (void)parseXML:(id)arg1 info:(id)arg2;
- (void)geocodeResponse:(id)arg1 info:(id)arg2;
@property(copy, nonatomic) NSArray *geocodedLocations; // @synthesize geocodedLocations;
@property(retain, nonatomic) NSError *error; // @synthesize error;

@end

