/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface ABGPSRequestInfo : NSObject <NSCopying, NSCoding>
{
    NSString *GUID;
    double created;
    double expires;
}

+ (id)token;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)description;
@property(nonatomic) double expires; // @synthesize expires;
@property(nonatomic) double created; // @synthesize created;
@property(retain, nonatomic) NSString *GUID; // @synthesize GUID;

@end

