/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocation, CLLocationManager;

@interface ABGPSSignificantLocationChangeMonitor : NSObject <CLLocationManagerDelegate>
{
    CLLocationManager *manager;
    CLLocation *lastLocation;
}

+ (id)sharedMonitor;
- (id)init;
- (void)start;
- (void)stop;
- (void)dealloc;
- (BOOL)supportsSignificantLocationChange;
@property(retain, nonatomic) CLLocation *lastLocation;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;

@end

