/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABHTTPRequest.h"

@interface ABHTTPRequest (ABAdditions)
+ (void)GET:(id)arg1 callback:(id)arg2;
+ (void)HEAD:(id)arg1 callback:(id)arg2;
@end

