/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIWindow.h"

@class NSString, UIActivityIndicatorView, UILabel;

@interface ABHUD : UIWindow
{
    UIActivityIndicatorView *activity;
    UILabel *label;
    UIWindow *blockingWindow;
    NSString *singletonKey;
    BOOL showBlockingWindow;
    BOOL showGrowlWindow;
}

+ (id)hudManager;
+ (void)growlImage:(id)arg1 text:(id)arg2;
+ (void)indicateSuccess:(id)arg1;
+ (void)indicateLongProgress:(id)arg1;
+ (void)indicateError:(id)arg1;
- (id)initWithText:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGAffineTransform)_currentTransform;
- (void)animateIn;
- (void)resignKeyWindow;
- (void)dealloc;
- (void)show;
- (void)statusBarOrientationDidChange:(id)arg1;
- (void)showBrieflyThenHide:(float)arg1;
- (void)hideAnimationDidStop:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)hide;
- (void)_swapInImageNamed:(id)arg1;
- (void)setLargeImage:(id)arg1;
- (void)indicateSuccessAndHide:(id)arg1;
- (void)indicateErrorAndHide:(id)arg1;
@property(retain, nonatomic) NSString *singletonKey; // @synthesize singletonKey;
@property(nonatomic) BOOL showGrowlWindow; // @synthesize showGrowlWindow;
@property(nonatomic) BOOL showBlockingWindow; // @synthesize showBlockingWindow;

@end

