/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSError, NSString;

@interface ABLanguageTranslator : NSObject
{
    NSString *translatedText;
    NSError *error;
}

+ (id)apiKey;
+ (id)apiRoot;
+ (void)translate:(id)arg1 from:(id)arg2 to:(id)arg3 callback:(id)arg4;
+ (void)translate:(id)arg1 from:(id)arg2 callback:(id)arg3;
+ (void)translate:(id)arg1 callback:(id)arg2;
- (void)dealloc;
- (void)translateResponse:(id)arg1 info:(id)arg2;
- (void)parseJSON:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSError *error; // @synthesize error;
@property(copy, nonatomic) NSString *translatedText; // @synthesize translatedText;

@end

