/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABProxy.h"

@interface ABMainThreadProxy : ABProxy
{
}

- (void)forwardInvocation:(id)arg1;
- (void)performInvocationOnMainThread:(id)arg1;
- (id)description;

@end

