/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class ABCallback, NSURL, UIImage, UINavigationController, UIView;

@interface ABMediaChooser : NSObject <UIActionSheetDelegate, UINavigationControllerDelegate, UIImagePickerControllerDelegate>
{
    int choices;
    UINavigationController *sourceNavigationController;
    ABCallback *callback;
    struct {
        int takePhoto;
        int chooseExistingPhoto;
        int recordVideo;
        int recordAudio;
    } buttonIndex;
    struct {
        unsigned int shouldSaveToLibrary:1;
    } _flags;
    UIImage *image;
    NSURL *movieURL;
    struct CGRect fromRect;
    UIView *inView;
}

+ (int)availableOptions:(int)arg1;
+ (BOOL)hasCamera;
+ (id)choose:(int)arg1 fromNavigationController:(id)arg2 callback:(id)arg3;
+ (id)choose:(int)arg1 rect:(struct CGRect)arg2 inView:(id)arg3 callback:(id)arg4;
+ (void)_showSuccessOrError:(id)arg1 forHUD:(id)arg2;
+ (void)_saveToPhotoAlbum:(id)arg1 context:(id)arg2;
+ (void)saveToPhotoAlbum:(id)arg1;
+ (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(id)arg3;
+ (void)_saveMovieToAlbum:(id)arg1 context:(id)arg2;
+ (void)saveMovieToAlbum:(id)arg1;
+ (void)video:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(id)arg3;
- (id)rootViewController;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)takePhotoOrVideo;
- (void)takePhoto;
- (void)chooseExistingPhoto;
- (void)chooseExistingVideo;
- (void)chooseExistingPhotoOrVideo;
- (void)recordVideo;
- (void)recordAudio;
- (void)showActionSheet;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)show;
- (id)initWithMediaChoices:(int)arg1 rect:(struct CGRect)arg2 inView:(id)arg3 callback:(id)arg4;
- (id)initWithMediaChoices:(int)arg1 navigationController:(id)arg2 callback:(id)arg3;
- (void)dealloc;
@property(retain, nonatomic) NSURL *movieURL; // @synthesize movieURL;
@property(retain, nonatomic) UIImage *image; // @synthesize image;

@end

