/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "UINavigationControllerDelegate-Protocol.h"
#import "UIVideoEditorControllerDelegate-Protocol.h"

@class ABCallback, NSURL, UINavigationController, UIVideoEditorController;

@interface ABMediaEditor : NSObject <UIVideoEditorControllerDelegate, UINavigationControllerDelegate>
{
    UIVideoEditorController *videoEditorController;
    UINavigationController *navigationController;
    ABCallback *callback;
    NSURL *videoURL;
}

+ (void)editVideo:(id)arg1 navigationController:(id)arg2 callback:(id)arg3;
- (void)dealloc;
- (void)show;
- (void)_dismiss;
- (void)videoEditorController:(id)arg1 didSaveEditedVideoToPath:(id)arg2;
- (void)videoEditorController:(id)arg1 didFailWithError:(id)arg2;
- (void)videoEditorControllerDidCancel:(id)arg1;
@property(retain, nonatomic) NSURL *videoURL; // @synthesize videoURL;
@property(retain, nonatomic) ABCallback *callback; // @synthesize callback;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController;

@end

