/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface ABNetworkCache : NSObject
{
}

+ (id)cachedDataForURL:(id)arg1 file:(id *)arg2;
+ (id)cachedDataForURL:(id)arg1;
+ (void)request:(id)arg1 callback:(id)arg2;
+ (void)response:(id)arg1 info:(id)arg2;

@end

