/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface ABProxy : NSObject
{
    id object;
}

+ (id)proxyForObject:(id)arg1;
- (id)initWithObject:(id)arg1;
- (void)dealloc;
- (id)proxiedObject;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;

@end

