/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIScrollView.h"

@class NSArray;

@interface ABRailView : UIScrollView
{
    id delegate;
    NSArray *items;
}

- (void)dealloc;
- (struct CGRect)frameForIndex:(int)arg1;
- (void)setItems:(id)arg1 animated:(BOOL)arg2;
@property(nonatomic) id delegate; // @synthesize delegate;

@end

