/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, UIImage;

@interface ABRailViewItem : NSObject
{
    NSString *title;
    UIImage *image;
}

- (id)initWithTitle:(id)arg1 image:(id)arg2;
- (id)_makeView;

@end

