/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABCallback, NSURL;

@interface ABRedirectFollower : NSObject
{
    NSURL *redirectURL;
    ABCallback *callback;
}

+ (void)followRedirectsForURL:(id)arg1 callback:(id)arg2;
- (void)dealloc;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)connectionDidFinishLoading:(id)arg1;

@end

