/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABCallback;

@interface ABReturnProxy : NSObject
{
    ABCallback *callback;
}

- (void)dealloc;
- (id)callback:(id)arg1;
- (void)returnValue:(id)arg1;
- (void)cancel;

@end

