/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "ABRowViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class ABRowView, UIScrollView;

@interface ABRowViewController : UIViewController <UIScrollViewDelegate, ABRowViewDelegate>
{
    ABRowView *_rowView;
}

- (void)loadRowView;
- (void)loadView;
- (void)reloadRowView;
@property(readonly, nonatomic) ABRowView *rowView;
- (void)scrollViewWillBeginDragging:(id)arg1;
@property(readonly, nonatomic) UIScrollView *scrollView;

@end

