/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIGestureRecognizer.h"

@class UIScrollView, UITouch;

@interface ABScrollGestureRecognizer : UIGestureRecognizer
{
    UITouch *_touch;
    struct CGPoint _firstPoint;
    struct CGPoint _lastPoint;
    double _lastTime;
    float _dx;
    float _dt;
    struct CGRect _originalBounds;
    UIScrollView *_startedOverScrollView;
    struct {
        unsigned int overHorizontallyScrollableView:1;
    } _flags;
}

- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)reset;
- (BOOL)canBePreventedByGestureRecognizer:(id)arg1;

@end

