/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewElement.h"

@class ABCallback, NSArray, NSString;

@interface ABStaticTableViewMultiValueElement : ABStaticTableViewElement
{
    NSString *key;
    NSArray *titles;
    NSArray *values;
    id defaultValue;
    ABCallback *additionalOptions;
}

- (void)dealloc;
- (id)currentValue;
- (id)selectedTitle;
- (BOOL)isSelectedValue:(id)arg1;
- (id)cellForTableView:(id)arg1;
- (void)didSelectInTableView:(id)arg1;
@property(retain, nonatomic) ABCallback *additionalOptions; // @synthesize additionalOptions;
@property(copy, nonatomic) id defaultValue; // @synthesize defaultValue;
@property(copy, nonatomic) NSArray *values; // @synthesize values;
@property(copy, nonatomic) NSArray *titles; // @synthesize titles;
@property(copy, nonatomic) NSString *key; // @synthesize key;

@end

