/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewElement.h"

@class UITableViewCell;

@interface ABStaticTableViewCustomCellElement : ABStaticTableViewElement
{
    UITableViewCell *cell;
}

- (void)dealloc;
- (id)cellForTableView:(id)arg1;
- (float)heightInTableView:(id)arg1;
@property(retain, nonatomic) UITableViewCell *cell; // @synthesize cell;

@end

