/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIControl.h"

@class CALayer, NSMutableArray;

@interface ABSubTabBar : UIControl
{
    id <ABSubTabBarDelegate> delegate;
    int selectedIndex;
    int numberOfTabs;
    NSMutableArray *tabViews;
    NSMutableArray *tabBarItems;
    CALayer *nippleLayer;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (struct CGRect)rectForIndex:(int)arg1;
- (id)accessibilityLabelForIndex:(int)arg1;
- (void)update;
- (void)updateGlows;
- (void)reallySetFrame:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
@property(nonatomic) int selectedIndex; // @synthesize selectedIndex;
- (void)drawRect:(struct CGRect)arg1;
- (void)tabBarSelected:(id)arg1;
- (void)tabBarDoubleTapped:(id)arg1;
@property(nonatomic) id <ABSubTabBarDelegate> delegate; // @synthesize delegate;

@end

