/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIControl.h"

@class ABSubTabBarItem;

@interface ABSubTabBarTabView : UIControl
{
    ABSubTabBarItem *item;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)setSelected:(BOOL)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (BOOL)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)cancelTrackingWithEvent:(id)arg1;
@property(retain, nonatomic) ABSubTabBarItem *item; // @synthesize item;

@end

