/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIScrollViewDelegate-Protocol.h"

@protocol ABSwipeColumnScrollViewDelegate <UIScrollViewDelegate>
- (id)swipeView:(id)arg1 willBeginTouches:(id)arg2 withEvent:(id)arg3;
- (void)swipeView:(id)arg1 shouldRevealItem:(id)arg2;
- (float)swipeView:(id)arg1 willSwipeToOffset:(float)arg2 throwing:(BOOL)arg3;
@end

