/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class UIActivityIndicatorView, UIImageView, UILabel, UITableView, UIView, UIViewController<ABTableViewPullToRefreshDelegate>;

@interface ABTableViewPullToRefreshController : NSObject
{
    UIViewController<ABTableViewPullToRefreshDelegate> *_contentsController;
    UITableView *_tableView;
    UIView *_headerView;
    UIImageView *loadNewerArrowView;
    UIActivityIndicatorView *loadNewerSpinner;
    UILabel *loadNewerLabel;
    UILabel *lastUpdatedLabel;
    struct {
        unsigned int loadNewerUIInReleaseState:2;
    } _flags;
}

- (id)initWithTableView:(id)arg1 contentsController:(id)arg2;
- (void)dealloc;
- (id)tableHeaderView;
- (void)_setLoadNewerState:(int)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)noteStateChanged:(int)arg1;

@end

