/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABCallback, ABTableViewStayOnScreenController, CADisplayLink, UIImageView, UITableView, UIView, UIViewController, UIViewController<ABTableViewPinchPreview>;

@interface ABTableViewPinchPreviewController : NSObject
{
    UIViewController<ABTableViewPinchPreview> *_contentsController;
    UITableView *_tableView;
    ABTableViewStayOnScreenController *stayOnScreenController;
    ABCallback *didDismissCallback;
    UIView *_blackView;
    UIViewController *_previewViewController;
    UIImageView *shadow1;
    UIImageView *shadow2;
    float originalCellHeight;
    struct CGRect cellRect;
    float pinchContainerHeight;
    float originalPinchFingerDistance;
    float lastPinchFingerDistance;
    UIView *_pinchContainer;
    UIView *_originalPinchBlocker;
    UIView *_pinchTopFlap;
    UIView *_pinchBottomFlap;
    UIView *_pinchTopFlapShade;
    UIView *_pinchBottomFlapShade;
    UIView *_pinchTopFlapContents;
    UIView *_pinchBottomFlapContents;
    UIImageView *_shadow;
    UIView *_pinchBlackout;
    UIViewController *flapContentsController;
    float filteredPinchT;
    float pinchLastT;
    float pinchLastDT;
    struct CGPoint pinchLastA;
    struct CGPoint pinchLastB;
    struct CGPoint pinchLastCenter;
    double startAnimateOutPinch;
    int twoFingerState;
    struct CGPoint a_;
    struct CGPoint b_;
    struct CGPoint center_;
    CADisplayLink *displayLink;
    BOOL needsUpdate;
    BOOL tracking;
    BOOL pinching;
}

- (id)initWithTableView:(id)arg1 contentsController:(id)arg2;
- (void)dealloc;
- (id)_interactionCell:(id)arg1;
- (void)_startWindowShade:(id)arg1;
- (void)_continueWindowShade:(id)arg1;
- (void)_endWindowShade:(id)arg1;
- (void)_finishEndWindowShade;
- (void)_finishWindowShadeAnimationDidEnd:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_startPinch:(id)arg1;
- (float)_pinchDelta:(float)arg1;
- (void)_updatePinch:(struct CGPoint)arg1:(struct CGPoint)arg2:(struct CGPoint)arg3;
- (void)_continuePinch:(id)arg1;
- (void)displayLink:(id)arg1;
- (void)_dismiss;
- (void)dismiss:(id)arg1;
- (void)_endPinch:(id)arg1;
- (void)pinchOut:(id)arg1;
- (void)pinchTapDismiss:(id)arg1;
- (void)_finishEndPinch;
- (void)animateOpenPinch:(id)arg1;
- (void)animateOutPinch:(id)arg1;
- (void)fadeOutPinch:(id)arg1;
- (void)twoFingerGesture:(id)arg1;
- (void)cancel;
@property(readonly, nonatomic) BOOL pinching; // @synthesize pinching;
@property(retain, nonatomic) ABCallback *didDismissCallback; // @synthesize didDismissCallback;
@property(nonatomic) ABTableViewStayOnScreenController *stayOnScreenController; // @synthesize stayOnScreenController;

@end

