/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableViewCell.h"

@class UIView;

@interface ABTableViewCell : UITableViewCell
{
    UIView *contentView;
}

- (Class)cellViewClass;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)dealloc;
- (void)setBackgroundColor:(id)arg1;
- (void)setEditing:(BOOL)arg1 animated:(BOOL)arg2;
@property(readonly, nonatomic) struct CGRect contentViewBounds;
@property(readonly, nonatomic) BOOL contentViewHighlighted;
- (void)setNeedsDisplay;
- (void)drawContentView:(struct CGRect)arg1;
- (id)primaryContentView;

@end

