/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIGestureRecognizer.h"

@class UITouch;

@interface ABTwoFingerDragDownGestureRecognizer : UIGestureRecognizer
{
    struct CGPoint aStart;
    struct CGPoint bStart;
    UITouch *a;
    UITouch *b;
    int twoFingerState;
}

- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)reset;
@property(readonly, nonatomic) int twoFingerState; // @synthesize twoFingerState;

@end

