/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, UIScrollView;

@interface ABVerticalFlowView : UIView <UIScrollViewDelegate>
{
    id <ABVerticalFlowViewDelegate> delegate;
    UIScrollView *_scrollView;
    NSMutableArray *_items;
    struct CGPoint lastOffset;
    float velocity;
    struct CGContext *scratchContext;
    int disableUpdate;
    struct CGRect fullscreenOriginalRect;
    UIView *fullscreenContainer;
    UIView *fullscreenImage;
}

- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)drawItem:(id)arg1 inContext:(struct CGContext *)arg2;
- (void)updateItemContents:(id)arg1;
- (void)setImage:(id)arg1 forIndex:(int)arg2;
- (void)setSubtext:(id)arg1 forIndex:(int)arg2;
- (void)beginDisableUpdate;
- (void)endDisableUpdate;
- (float)_updateItem:(id)arg1 withIndex:(int)arg2;
- (void)_updateItems;
- (void)_updateContentSize;
- (void)setFrame:(struct CGRect)arg1;
- (void)reloadData;
- (float)offsetForIndex:(int)arg1;
- (int)indexForOffset:(float)arg1;
- (void)selectIndex:(int)arg1 animated:(BOOL)arg2;
- (int)selectedIndex;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)tap:(id)arg1;
- (void)doubleTap:(id)arg1;
- (void)pinch:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)fullscreen:(int)arg1;
- (void)_endFullscreen;
- (void)endFullScreenDidEnd:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)pinchClose:(id)arg1;
- (void)tapClose:(id)arg1;
@property(nonatomic) id <ABVerticalFlowViewDelegate> delegate; // @synthesize delegate;

@end

