/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class NSString, UIImage;

@interface ABVerticalFlowViewItem : UIView
{
    NSString *subtext;
    UIImage *image;
}

- (void)dealloc;
@property(retain, nonatomic) NSString *subtext; // @synthesize subtext;
@property(retain, nonatomic) UIImage *image; // @synthesize image;

@end

