/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABProxy.h"

@interface ABWeakProxy : ABProxy
{
}

+ (id)_weakProxyMap;
+ (id)proxyForObject:(id)arg1;
+ (void)dissociateWeakProxyForObject:(id)arg1;
- (id)initWithObject:(id)arg1;
- (void)dissociate;
- (id)description;

@end

