/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class ABCallback;

@interface AlertViewHelper : NSObject <UIActionSheetDelegate, UIAlertViewDelegate>
{
    ABCallback *callback;
}

- (void)dealloc;
- (void)alertView:(id)arg1 willDismissWithButtonIndex:(int)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
@property(retain, nonatomic) ABCallback *callback; // @synthesize callback;

@end

