/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class TweetieSignUpCaptchaViewController, UIActivityIndicatorView;

@interface CustomCaptchaHeader : UIView
{
    UIActivityIndicatorView *spinner;
    TweetieSignUpCaptchaViewController *controller;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;

@end

