/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABImageService.h"

@interface EmberImageService : ABImageService
{
}

+ (id)apiKey;
+ (void)requestUserTokenForUsername:(id)arg1 password:(id)arg2 callback:(id)arg3;
+ (void)requestUserTokenResponse:(id)arg1 info:(id)arg2;
+ (void)parseEmberUserToken:(id)arg1 info:(id)arg2;
- (void)postImage:(id)arg1 associatedMessage:(id)arg2 fromAccount:(id)arg3 callback:(id)arg4;
- (void)didPostImage:(id)arg1 info:(id)arg2;

@end

