/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface FMDatabase : NSObject
{
    struct sqlite3 *db;
    NSString *databasePath;
    BOOL logsErrors;
    BOOL crashOnErrors;
    BOOL inUse;
    BOOL inTransaction;
    BOOL traceExecution;
    BOOL checkedOut;
    int busyRetryTimeout;
    BOOL shouldCacheStatements;
    NSMutableDictionary *cachedStatements;
}

+ (id)databaseWithPath:(id)arg1;
+ (id)sqliteLibVersion;
- (id)initWithPath:(id)arg1;
- (void)dealloc;
- (id)databasePath;
- (struct sqlite3 *)sqliteHandle;
- (BOOL)open;
- (BOOL)openWithFlags:(int)arg1;
- (BOOL)close;
- (void)clearCachedStatements;
- (id)cachedStatementForQuery:(id)arg1;
- (void)setCachedStatement:(id)arg1 forQuery:(id)arg2;
- (BOOL)rekey:(id)arg1;
- (BOOL)setKey:(id)arg1;
- (BOOL)goodConnection;
- (void)compainAboutInUse;
- (id)lastErrorMessage;
- (BOOL)hadError;
- (int)lastErrorCode;
- (long long)lastInsertRowId;
- (void)bindObject:(id)arg1 toColumn:(int)arg2 inStatement:(struct sqlite3_stmt *)arg3;
- (id)executeQuery:(id)arg1 withArgumentsInArray:(id)arg2 orVAList:(void *)arg3;
- (id)executeQuery:(id)arg1;
- (id)executeQuery:(id)arg1 withArgumentsInArray:(id)arg2;
- (BOOL)executeUpdate:(id)arg1 withArgumentsInArray:(id)arg2 orVAList:(void *)arg3;
- (BOOL)executeUpdate:(id)arg1;
- (BOOL)executeUpdate:(id)arg1 withArgumentsInArray:(id)arg2;
- (BOOL)rollback;
- (BOOL)commit;
- (BOOL)beginDeferredTransaction;
- (BOOL)beginTransaction;
- (BOOL)logsErrors;
- (void)setLogsErrors:(BOOL)arg1;
- (BOOL)crashOnErrors;
- (void)setCrashOnErrors:(BOOL)arg1;
- (BOOL)inUse;
- (void)setInUse:(BOOL)arg1;
- (BOOL)inTransaction;
- (void)setInTransaction:(BOOL)arg1;
- (BOOL)traceExecution;
- (void)setTraceExecution:(BOOL)arg1;
- (BOOL)checkedOut;
- (void)setCheckedOut:(BOOL)arg1;
- (int)busyRetryTimeout;
- (void)setBusyRetryTimeout:(int)arg1;
- (BOOL)shouldCacheStatements;
- (void)setShouldCacheStatements:(BOOL)arg1;
- (id)cachedStatements;
- (void)setCachedStatements:(id)arg1;
- (int)changes;

@end

