/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class FMDatabase, FMStatement, NSMutableDictionary, NSString;

@interface FMResultSet : NSObject
{
    FMDatabase *parentDB;
    FMStatement *statement;
    NSString *query;
    NSMutableDictionary *columnNameToIndexMap;
    BOOL columnNamesSetup;
}

+ (id)resultSetWithStatement:(id)arg1 usingParentDatabase:(id)arg2;
- (void)dealloc;
- (void)close;
- (void)setupColumnNames;
- (void)kvcMagic:(id)arg1;
- (id)resultDict;
- (BOOL)next;
- (BOOL)hasAnotherRow;
- (int)columnIndexForName:(id)arg1;
- (int)intForColumn:(id)arg1;
- (int)intForColumnIndex:(int)arg1;
- (long)longForColumn:(id)arg1;
- (long)longForColumnIndex:(int)arg1;
- (long long)longLongIntForColumn:(id)arg1;
- (long long)longLongIntForColumnIndex:(int)arg1;
- (BOOL)boolForColumn:(id)arg1;
- (BOOL)boolForColumnIndex:(int)arg1;
- (double)doubleForColumn:(id)arg1;
- (double)doubleForColumnIndex:(int)arg1;
- (id)stringForColumnIndex:(int)arg1;
- (id)stringForColumn:(id)arg1;
- (id)dateForColumn:(id)arg1;
- (id)dateForColumnIndex:(int)arg1;
- (id)dataForColumn:(id)arg1;
- (id)dataForColumnIndex:(int)arg1;
- (id)dataNoCopyForColumn:(id)arg1;
- (id)dataNoCopyForColumnIndex:(int)arg1;
- (BOOL)columnIndexIsNull:(int)arg1;
- (BOOL)columnIsNull:(id)arg1;
- (const char *)UTF8StringForColumnIndex:(int)arg1;
- (const char *)UTF8StringForColumnName:(id)arg1;
- (id)columnNameForIndex:(int)arg1;
- (void)setParentDB:(id)arg1;
- (id)query;
- (void)setQuery:(id)arg1;
- (id)columnNameToIndexMap;
- (void)setColumnNameToIndexMap:(id)arg1;
- (id)statement;
- (void)setStatement:(id)arg1;

@end

