/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface FMStatement : NSObject
{
    struct sqlite3_stmt *statement;
    NSString *query;
    long useCount;
}

- (void)dealloc;
- (void)close;
- (void)reset;
- (struct sqlite3_stmt *)statement;
- (void)setStatement:(struct sqlite3_stmt *)arg1;
- (id)query;
- (void)setQuery:(id)arg1;
- (long)useCount;
- (void)setUseCount:(long)arg1;
- (id)description;

@end

