/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "FollowCostDelegate-Protocol.h"

@class FollowCost, TwitterAccount, TwitterUser;

@interface FollowCostViewController : ABStaticTableViewController <FollowCostDelegate>
{
    TwitterAccount *account;
    TwitterUser *user;
    FollowCost *followCost;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)loadTableView;
- (void)viewDidLoad;
- (void)followCost:(id)arg1 didUpdateForUser:(id)arg2;
- (void)followCost:(id)arg1 failedToUpdateForUser:(id)arg2 withError:(id)arg3;
- (void)dismissError:(id)arg1 info:(id)arg2;
- (void)viewOnWeb:(id)arg1;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

