/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, TwitterUser;

@interface FollowCost : NSObject
{
    id <FollowCostDelegate> delegate;
    BOOL loading;
    TwitterUser *user;
    NSString *averageTweetsPerDay;
    NSString *averageTweetsPerDayRecently;
    NSString *atReplyIndex;
    NSString *goldenIndex;
    NSString *politicalIndex;
}

- (void)_load;
- (void)_didLoad:(id)arg1 info:(id)arg2;
- (id)initWithTwitterUser:(id)arg1;
- (void)dealloc;
- (void)parseJSON:(id)arg1 info:(id)arg2;
@property(copy, nonatomic) NSString *politicalIndex; // @synthesize politicalIndex;
@property(copy, nonatomic) NSString *goldenIndex; // @synthesize goldenIndex;
@property(copy, nonatomic) NSString *atReplyIndex; // @synthesize atReplyIndex;
@property(copy, nonatomic) NSString *averageTweetsPerDayRecently; // @synthesize averageTweetsPerDayRecently;
@property(copy, nonatomic) NSString *averageTweetsPerDay; // @synthesize averageTweetsPerDay;
@property(readonly, nonatomic) BOOL loading; // @synthesize loading;
@property(nonatomic) id <FollowCostDelegate> delegate; // @synthesize delegate;

@end

