/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface Foursquare : NSObject
{
}

+ (void)venueDetailsFor4SQURL:(id)arg1 callback:(id)arg2;
+ (void)venueDetails4SQResponse:(id)arg1 info:(id)arg2;
+ (void)venueDetailsResponse:(id)arg1 info:(id)arg2;

@end

