/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, NSURL;

@interface FoursquareUser : NSObject
{
    NSString *userID;
    NSString *firstName;
    NSString *lastName;
    NSString *gender;
    NSURL *photoURL;
}

- (void)dealloc;
- (id)_ab_improved_description_body;
- (id)description;
- (void)parseXML:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSURL *photoURL; // @synthesize photoURL;
@property(retain, nonatomic) NSString *gender; // @synthesize gender;
@property(retain, nonatomic) NSString *lastName; // @synthesize lastName;
@property(retain, nonatomic) NSString *firstName; // @synthesize firstName;
@property(retain, nonatomic) NSString *userID; // @synthesize userID;

@end

