/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class FoursquareVenue, NSURL, TwitterAccount;

@interface FoursquareVenueViewController : ABStaticTableViewController
{
    TwitterAccount *account;
    NSURL *url;
    FoursquareVenue *venue;
    struct {
        unsigned int loading:1;
    } _flags;
}

- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)loadTableView;
- (void)twitterUser:(id)arg1;
- (void)call:(id)arg1;
- (void)showMap:(id)arg1;
- (void)openInFoursquare:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)venueDetailsResponse:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) FoursquareVenue *venue; // @synthesize venue;
@property(retain, nonatomic) NSURL *url; // @synthesize url;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

