/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABImage, NSString, NSURL;

@interface FusionAd : NSObject
{
    NSString *text;
    NSURL *imageURL;
    NSURL *link;
    ABImage *image;
    CDStruct_1b8233f7 _flags;
}

- (void)dealloc;
- (id)init;
- (void)adResponse:(id)arg1 info:(id)arg2;
@property(readonly, nonatomic) ABImage *image;
- (void)imageResponse:(id)arg1 info:(id)arg2;
- (void)parseAdXML_1_0:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSURL *link; // @synthesize link;
@property(retain, nonatomic) NSURL *imageURL; // @synthesize imageURL;
@property(copy, nonatomic) NSString *text; // @synthesize text;

@end

