/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSArray.h"

#import "NSCopying-Protocol.h"
#import "NSFastEnumeration-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@interface JKArray : NSArray <NSCopying, NSMutableCopying, NSFastEnumeration>
{
    id *objects;
    unsigned int count;
    unsigned int capacity;
    unsigned int mutations;
}

+ (void)load;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (unsigned int)count;
- (void)getObjects:(id *)arg1 range:(struct _NSRange)arg2;
- (id)objectAtIndex:(unsigned int)arg1;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;

@end

