/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSDictionary.h"

#import "NSCopying-Protocol.h"
#import "NSFastEnumeration-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@interface JKDictionary : NSDictionary <NSCopying, NSMutableCopying, NSFastEnumeration>
{
    unsigned int count;
    unsigned int capacity;
    unsigned int mutations;
    struct JKHashTableEntry *entry;
}

+ (void)load;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (unsigned int)count;
- (id)objectForKey:(id)arg1;
- (void)getObjects:(id *)arg1 andKeys:(id *)arg2;
- (unsigned int)countByEnumeratingWithState:(CDStruct_11f37819 *)arg1 objects:(id *)arg2 count:(unsigned int)arg3;
- (id)keyEnumerator;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;

@end

