/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "UITextFieldDelegate-Protocol.h"

@class ABHUD, UITextField;

@interface LinkQueueAddAccountViewController : ABStaticTableViewController <UITextFieldDelegate>
{
    id <LinkQueueAddAccountViewControllerDelegate> delegate;
    UITextField *usernameField;
    UITextField *passwordField;
    ABHUD *hud;
    BOOL hideHUDImmediatelyAfterVerifyingAccount;
}

- (void)dealloc;
- (void)loadTableView;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)save:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)didVerify:(id)arg1 info:(id)arg2;
- (void)cancel:(id)arg1;
@property(nonatomic) BOOL hideHUDImmediatelyAfterVerifyingAccount; // @synthesize hideHUDImmediatelyAfterVerifyingAccount;
@property(nonatomic) id <LinkQueueAddAccountViewControllerDelegate> delegate; // @synthesize delegate;

@end

