/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "LinkQueueAddAccountViewControllerDelegate-Protocol.h"

@class ABCallback, ABHUD, NSString, UINavigationController;

@interface LinkQueueController : NSObject <LinkQueueAddAccountViewControllerDelegate>
{
    UINavigationController *navigationController;
    ABCallback *showLoginPanelCallback;
    NSString *link;
    NSString *summary;
    id refStatus;
    ABHUD *hud;
}

+ (id)controller;
- (void)dealloc;
- (void)_addLinkTo:(id)arg1;
- (void)_showLoginPanel;
- (void)didAddLink:(id)arg1 info:(id)arg2;
- (void)addLink:(id)arg1 summary:(id)arg2 status:(id)arg3 navigationController:(id)arg4;
- (void)didLoginInPreparationForAddingLink:(id)arg1 info:(id)arg2;
- (void)showLoginPanel:(id)arg1 callback:(id)arg2;
- (void)linkQueueAddAccountViewControllerDismiss:(id)arg1 withLinkQueue:(id)arg2;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController;

@end

