/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class FMDatabase;

@interface LocalAutocompleteDB : NSObject
{
    FMDatabase *db;
}

+ (void)verifyDatabase;
+ (id)databasePath;
+ (id)sharedAutocompleteDB;
+ (void)resetDatabase;
+ (void)shutdown;
- (id)initWithPath:(id)arg1;
- (void)seedAccount:(id)arg1;
- (void)didReceiveFriends:(id)arg1 info:(id)arg2;
- (void)loadFromDisk;
- (void)saveToDisk;
- (id)execute:(id)arg1;
- (void)loadSchema;
- (void)close;
- (void)dealloc;
- (void)setSynchronize:(BOOL)arg1;
- (void)beginTransaction;
- (void)endTransaction;
- (void)addUser:(id)arg1;
- (void)addUsername:(id)arg1 fullName:(id)arg2 avatarURL:(id)arg3;
- (void)addHashtag:(id)arg1 description:(id)arg2;
- (void)addPlace:(id)arg1 placeType:(int)arg2 name:(id)arg3 address:(id)arg4 latitude:(id)arg5 longitude:(id)arg6;
- (void)prioritizeUsername:(id)arg1;
- (void)prioritizeHashtag:(id)arg1;
- (void)prioritizePlace:(id)arg1;
- (void)assimilateFromStatuses:(id)arg1;
- (void)compact;
- (id)defaultResultsForType:(int)arg1;
- (id)resultsForPartialText:(id)arg1 type:(int)arg2;
- (id)placeAutocompletePrefixesNearPlace:(id)arg1;
@property(readonly, nonatomic) FMDatabase *db; // @synthesize db;

@end

