/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "MKAnnotation-Protocol.h"

@class NSString;

@interface LocationPinAnnotation : NSObject <MKAnnotation>
{
    CDStruct_2c43369c coordinate;
    NSString *title;
    NSString *subtitle;
}

- (void)dealloc;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title;
@property(nonatomic) CDStruct_2c43369c coordinate; // @synthesize coordinate;

@end

