/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (ABAdditions)
- (id)ab_UTF8String;
- (id)gzipInflate;
- (id)gzipDeflate;
- (id)_ab_sha1Digest;
- (id)_ab_hexString;
@end

