/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (ABEncryption)
- (id)encryptWithKey:(id)arg1 hmacKey:(id)arg2 initializationVector:(id *)arg3 hmac:(id *)arg4;
@end

