/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSData.h"

@interface NSData (Base64)
+ (id)dataFromBase64String:(id)arg1;
- (id)initWithBase64String:(id)arg1;
- (id)base64EncodedString;
@end

