/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSDictionary.h"

@interface NSDictionary (JSONKit)
- (id)JSONData;
- (id)JSONDataWithOptions:(unsigned int)arg1 error:(id *)arg2;
- (id)JSONString;
- (id)JSONStringWithOptions:(unsigned int)arg1 error:(id *)arg2;
@end

