/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSNumber.h"

@interface NSNumber (ABAdditions)
+ (id)formattedDecimalStringForNumberString:(id)arg1;
+ (id)formattedSizeOfBytes:(int)arg1;
- (id)URLEncodedString;
- (id)formattedDecimalString;
@end

