/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (ABAdditions)
- (id)delayProxy;
- (id)backgroundProxy;
- (id)mainThreadProxy;
- (id)weakProxy;
- (void)dissociateWeakProxy;
- (id)weakMainThreadProxy;
- (id)callback:(id)arg1;
- (id)isError;
- (void)_ab_setClass:(Class)arg1;
- (id)applicationSupportFolder;
@end

