/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (YAJL)
- (id)ab_JSONString;
- (id)ab_JSONStringWithOptions:(unsigned int)arg1 indentString:(id)arg2;
@end

