/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (ABAssociatedObjectAdditions)
- (void)ab_setAssignedAssociatedObject:(id)arg1 forKey:(void *)arg2;
- (void)ab_setNonAtomicRetainedAssociatedObject:(id)arg1 forKey:(void *)arg2;
- (id)ab_associatedObjectForKey:(void *)arg1;
@end

