/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface NSObject (GoActiveTextRange)
- (void)navigateWithViewController:(id)arg1 account:(id)arg2 animated:(BOOL)arg3;
@end

