/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (ABAdditions)
+ (id)GUID;
- (id)base64EncodedString;
- (id)_ab_sha1Digest;
- (id)ab_UTF8String;
- (id)stringByRot13ingString;
- (BOOL)ab_containsRange:(struct _NSRange)arg1;
- (id)ab_dictionaryFromParams;
- (BOOL)containsSubstring:(id)arg1;
- (int)numberOfOccurrencesOfSubstring:(id)arg1;
- (BOOL)containsSubstringIgnoringCase:(id)arg1;
- (BOOL)matchesPartialsSearchString:(id)arg1;
- (int)ab_editDistance:(id)arg1;
- (BOOL)ab_fuzzyPrefixMatch:(id)arg1;
- (id)stringByUnescapingXMLEntities;
- (id)stringByEscapingXMLEntities;
- (int)caseInsensitiveCompare:(id)arg1;
- (id)URLEncodedString;
- (id)ab_URLDecodedString:(BOOL)arg1;
- (id)dateValueFromHTTPLikeDate;
- (id)dateValueFromJSONTwitterDate;
- (int)ab_lengthAssumingRangesForRegex:(id)arg1 areReplacedByFixedLength:(int)arg2;
- (id)arrayOfRangesForRegex:(id)arg1 class:(Class)arg2;
- (id)arrayOfRangesForRegex:(id)arg1;
- (int)activeStringType;
@end

