/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSString.h"

@interface NSString (JSONKit)
- (id)objectFromJSONString;
- (id)objectFromJSONStringWithParseOptions:(unsigned int)arg1;
- (id)objectFromJSONStringWithParseOptions:(unsigned int)arg1 error:(id *)arg2;
- (id)mutableObjectFromJSONString;
- (id)mutableObjectFromJSONStringWithParseOptions:(unsigned int)arg1;
- (id)mutableObjectFromJSONStringWithParseOptions:(unsigned int)arg1 error:(id *)arg2;
@end

