/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface OAuth : NSObject
{
}

+ (void)requestRequestToken:(id)arg1 consumerKey:(id)arg2 consumerSecret:(id)arg3 oAuthCallback:(id)arg4 callback:(id)arg5;
+ (void)requestTokenResponse:(id)arg1 info:(id)arg2;
+ (void)requestAccessToken:(id)arg1 consumerKey:(id)arg2 consumerSecret:(id)arg3 unauthorizedToken:(id)arg4 unauthorizedSecret:(id)arg5 verifier:(id)arg6 callback:(id)arg7;
+ (void)requestAccessResponse:(id)arg1 info:(id)arg2;

@end

