/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "MKAnnotation-Protocol.h"

@interface PinAnnotation : NSObject <MKAnnotation>
{
    CDStruct_2c43369c coordinate;
}

@property(nonatomic) CDStruct_2c43369c coordinate; // @synthesize coordinate;

@end

