/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "LinkQueue.h"

@interface ReadItLater : LinkQueue
{
}

+ (id)defaultLinkQueueName;
+ (id)defaultLinkQueueURLString;
+ (id)defaultLinkQueueLoginTitle;
+ (id)defaultLinkQueueLoginPlaceholder;
+ (id)defaultLinkQueuePasswordPlaceholder;
- (int)defaultsIntegerValue;
- (void)verifyCredentials:(id)arg1;
- (void)verifyCredentialsResponse:(id)arg1 info:(id)arg2;
- (void)addURL:(id)arg1 summary:(id)arg2 status:(id)arg3 callback:(id)arg4;
- (void)addURLResponse:(id)arg1 info:(id)arg2;

@end

