/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class NSArray;

@interface SearchTabs : UIView
{
    id <SearchTabsDelegate> delegate;
    NSArray *titles;
    int selectedIndex;
}

- (void)dealloc;
- (struct CGRect)frameForIndex:(int)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
@property(nonatomic) int selectedIndex; // @synthesize selectedIndex;
@property(copy, nonatomic) NSArray *titles; // @synthesize titles;
@property(nonatomic) id <SearchTabsDelegate> delegate; // @synthesize delegate;

@end

