/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABRowView.h"

#import "SearchTabsDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class ABPlainRowCell, CLLocation, MKPlacemark, NSString, SearchTabs, UIButton, UITextField;

@interface SearchRowView : ABRowView <UITextFieldDelegate, SearchTabsDelegate>
{
    id <SearchRowViewDelegate> searchDelegate;
    int context;
    UITextField *textField;
    UIButton *cancelButton;
    SearchTabs *tabs;
    ABRowView *resultsGroup;
    ABRowView *_highlightOnReturn;
    ABPlainRowCell *nearbySection;
    ABPlainRowCell *gotouserRow;
    ABPlainRowCell *searchNearbyRow;
    id gpsRequestToken;
    MKPlacemark *mostRecentPlacemark;
    CLLocation *mostRecentLocation;
    NSString *findUsersSearchToken;
    BOOL active;
    struct {
        unsigned int allTweets;
        unsigned int nearby;
        unsigned int people;
    } tabIndex;
}

- (void)_updateZ;
- (id)init;
- (void)dealloc;
- (void)setActive:(BOOL)arg1;
- (id)strippedToUsername;
- (id)nearbyString;
- (void)_updateResults;
- (void)gpsUpdate:(id)arg1 info:(id)arg2;
- (void)searchTabs:(id)arg1 didSelectIndex:(int)arg2;
- (void)textFieldDidBeginEditing:(id)arg1;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldClear:(id)arg1;
- (void)cancel:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)searchAllTweets:(id)arg1;
- (void)searchNearbyTweets:(id)arg1;
- (void)searchPeople:(id)arg1;
- (void)findUsersResponse:(id)arg1 info:(id)arg2;
- (void)selectUser:(id)arg1;
- (void)gotoUser:(id)arg1;
- (BOOL)textFieldShouldReturn:(id)arg1;
@property(nonatomic) int context; // @synthesize context;
@property(retain, nonatomic) NSString *findUsersSearchToken; // @synthesize findUsersSearchToken;
@property(retain, nonatomic) MKPlacemark *mostRecentPlacemark; // @synthesize mostRecentPlacemark;
@property(retain, nonatomic) CLLocation *mostRecentLocation; // @synthesize mostRecentLocation;
@property(nonatomic) id <SearchRowViewDelegate> searchDelegate; // @synthesize searchDelegate;

@end

