/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABPlainRowCell.h"

@class NSArray;

@interface SideBySideRowView : ABPlainRowCell
{
    int sections;
    int highlightedSection;
    int selectedSection;
    NSArray *titles;
    NSArray *subtitles;
    NSArray *images;
    NSArray *callbacks;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (struct CGRect)rectForSection:(int)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (int)sectionForTouches:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) NSArray *callbacks; // @synthesize callbacks;
@property(retain, nonatomic) NSArray *images; // @synthesize images;
@property(retain, nonatomic) NSArray *subtitles; // @synthesize subtitles;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles;
@property(nonatomic) int selectedSection; // @synthesize selectedSection;
@property(nonatomic) int sections; // @synthesize sections;

@end

