/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABTableViewCell.h"

@class NSString, UIImage;

@interface SMSStyleConversationCell : ABTableViewCell
{
    UIImage *image;
    NSString *nameText;
    NSString *messageText;
    NSString *boldWhenText;
    NSString *normalWhenText;
    BOOL unread;
    BOOL replied;
    BOOL groupMessage;
}

- (void)dealloc;
- (void)drawContentView:(struct CGRect)arg1;
@property(nonatomic) BOOL groupMessage; // @synthesize groupMessage;
@property(nonatomic) BOOL replied; // @synthesize replied;
@property(nonatomic) BOOL unread; // @synthesize unread;
@property(retain, nonatomic) NSString *normalWhenText; // @synthesize normalWhenText;
@property(retain, nonatomic) NSString *boldWhenText; // @synthesize boldWhenText;
@property(retain, nonatomic) NSString *messageText; // @synthesize messageText;
@property(retain, nonatomic) NSString *nameText; // @synthesize nameText;
@property(retain, nonatomic) UIImage *image; // @synthesize image;

@end

