/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface StatusIDSync : NSObject
{
}

+ (void)setValue:(id)arg1 forKey:(id)arg2;
+ (void)setResponse:(id)arg1 info:(id)arg2;
+ (void)requestValueForKey:(id)arg1 callback:(id)arg2;
+ (void)requestResponse:(id)arg1 info:(id)arg2;
+ (void)parseResponseXML:(id)arg1 info:(id)arg2;

@end

