/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSError, NSString;

@interface Tagalus : NSObject
{
    NSString *hashtag;
    NSString *definition;
    NSError *error;
}

+ (id)_hashtag:(id)arg1;
+ (void)define:(id)arg1 callback:(id)arg2;
+ (id)apiKey;
+ (void)define:(id)arg1 as:(id)arg2;
+ (void)defineDefinitionResponse:(id)arg1 info:(id)arg2;
- (void)dealloc;
- (void)defineResponse:(id)arg1 info:(id)arg2;
- (void)parseJSON:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSError *error; // @synthesize error;
@property(copy, nonatomic) NSString *definition; // @synthesize definition;
@property(copy, nonatomic) NSString *hashtag; // @synthesize hashtag;

@end

