/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

#import "MKMapViewDelegate-Protocol.h"

@class MKMapView, UIButton, UIImageView, UILabel, UISwitch;

@interface TIComposeMapView : UIView <MKMapViewDelegate>
{
    id <TIComposeMapViewDelegate> delegate;
    MKMapView *_mapView;
    UIImageView *_outline;
    UISwitch *_switch;
    UILabel *_label;
    UIButton *_toggleButton;
    UILabel *_fromLabel;
    CDStruct_2c43369c _lastLocation;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)layoutSubviews;
- (void)toggleGeo:(id)arg1;
- (void)reload;
- (CDStruct_2c43369c)coordinate;
- (void)updateMap;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)updateMapLabel:(id)arg1;
@property(nonatomic) id <TIComposeMapViewDelegate> delegate; // @synthesize delegate;

@end

