/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol TIComposeAttachmentsViewDelegate <NSObject>
- (id)account;
- (id)composition;
- (void)camera:(id)arg1;
- (void)photoLibrary:(id)arg1;
- (void)didRemoveAttachment:(id)arg1;
@end

