/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class UILabel, UIProgressView;

@interface TISendProgressView : UIView
{
    UILabel *label;
    UIProgressView *progressBar;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) UIProgressView *progressBar; // @synthesize progressBar;
@property(readonly, nonatomic) UILabel *label; // @synthesize label;

@end

