/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class UIActivityIndicatorView, UIImageView, UIScrollView;

@interface TopTweetsRailView : UIView
{
    id delegate;
    UIScrollView *scrollView;
    UIImageView *border;
    UIActivityIndicatorView *spinner;
    int numberOfTopTweets;
}

- (struct CGRect)frameForTag:(int)arg1;
- (void)updateBlocks;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)setTopTweets:(id)arg1;
@property(nonatomic) id delegate; // @synthesize delegate;

@end

