/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieStatusStreamViewController.h"

@interface TweetieTimelineViewController : TweetieStatusStreamViewController
{
}

- (id)scribePage;
- (id)scribeSection;
- (void)recordImpressionFromReferringEvent:(id)arg1;
- (id)backBarButtonItemTitle;
- (id)statusStream;
- (id)placeholderSearchStringForFilterBar;
- (void)viewedMostRecent:(id)arg1;

@end

