/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABSimplePersistentRecentSearchViewController.h"

@interface TweetieRecentHashtagsViewController : ABSimplePersistentRecentSearchViewController
{
    id <TweetieRecentHashtagsViewControllerDelegate> delegate;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)defaultsKey;
- (id)placeholderText;
- (id)unmatchedResultFormatText;
- (BOOL)enforceHashtagPrefix;
- (void)cancel:(id)arg1;
- (void)search:(id)arg1;
- (int)returnKeyType;
@property(nonatomic) id <TweetieRecentHashtagsViewControllerDelegate> delegate; // @synthesize delegate;

@end

