/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface TweetieSettings : NSObject
{
    int fontSize;
    int displayName;
    SEL displayNameSelector;
    int quoteSyntax;
    int dateFormatStyle;
}

+ (id)sharedSettings;
- (id)init;
- (void)setupInitialSettings;
- (void)recacheFontSize;
@property(nonatomic) int fontSize; // @synthesize fontSize;
- (void)recacheDisplayName;
- (void)recacheQuoteSyntax;
- (void)recacheDateFormatStyle;
- (BOOL)soundEffectsEnabled;
@property(readonly, nonatomic) BOOL placeAutoComplete;
@property(readonly, nonatomic) int dateFormatStyle; // @synthesize dateFormatStyle;
@property(readonly, nonatomic) int quoteSyntax; // @synthesize quoteSyntax;
@property(readonly, nonatomic) SEL displayNameSelector; // @synthesize displayNameSelector;
@property(readonly, nonatomic) int displayName; // @synthesize displayName;

@end

