/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class TweetieUserProfile4WayCornerSelectionView, TweetieUserProfile4WayCornerView;

@interface TweetieUserProfile4WayButtonView : UIView
{
    TweetieUserProfile4WayCornerView *a;
    TweetieUserProfile4WayCornerView *b;
    TweetieUserProfile4WayCornerView *c;
    TweetieUserProfile4WayCornerView *d;
    TweetieUserProfile4WayCornerSelectionView *selectionHighlight;
}

- (id)initWithFrame:(struct CGRect)arg1 data:(id)arg2;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
- (void)didSelectCornerView:(id)arg1;
- (void)_removeSelection:(id)arg1;
- (void)didDeselectCornerView:(id)arg1 cancel:(BOOL)arg2;
- (void)unhighlight:(id)arg1;
- (void)animationDidStop:(id)arg1 finished:(id)arg2 context:(id)arg3;

@end

