/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, TopTweetsRailView, TwitterAccount, UIImageView, UISearchBar, UISearchDisplayController, UITableView, UIView;

@interface TweetieSearchesViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    TwitterAccount *account;
    UITableView *_tableView;
    NSArray *trends;
    NSArray *savedSearches;
    UIImageView *searchesHeaderView;
    TopTweetsRailView *trendsHeaderView;
    UIImageView *signupHeaderView;
    UIImageView *shadow;
    UIView *signupContainer;
    UISearchBar *fakeSearchBar;
    UISearchDisplayController *fakeSearchController;
    id searchingController;
    UIView *searchDivider;
    int SignupSection;
    int SavedSearchesSection;
    int TrendsSection;
    int BrowseUsersSection;
    int NumberOfSections;
    BOOL showSavedSearches;
    CDStruct_daa5b662 _impressionFlags;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (id)backBarButtonItemTitle;
- (void)_updateDivider;
- (void)loadView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)arg1;
- (void)topTweetsRailView:(id)arg1 selectedTweet:(id)arg2;
- (void)topTweetsRailViewShowAllTopTweets:(id)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)reloadSection:(int)arg1 animated:(BOOL)arg2;
- (void)trendsDidUpdate:(id)arg1;
- (void)savedSearchesDidUpdate:(id)arg1;
- (void)topTweetsDidUpdate:(id)arg1;
@property(retain, nonatomic) NSArray *trends; // @synthesize trends;
@property(retain, nonatomic) NSArray *savedSearches; // @synthesize savedSearches;
- (BOOL)hasTrends;
- (BOOL)hasSavedSearches;
- (id)trendAtIndex:(int)arg1;
- (id)savedSearchAtIndex:(int)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)radar:(id)arg1;
- (id)searchField;
- (void)_hideSearchBar;
- (void)viewWillSwitchToAnotherSubTab;
- (id)appropriateSearchDisplayContentsController;
- (void)startSearch:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)didTapPromotedLabel:(id)arg1 info:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)_findFriends;
- (void)sul:(id)arg1;
- (void)didLoadFullPlace:(id)arg1 info:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)ab_attemptToRecordImpressionFromReferringEvent:(id)arg1;
- (void)ab_resetImpression;
- (void)_recordImpression;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

