/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "ABTableViewPullToRefreshDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class ABTableViewPullToRefreshController, NSMutableArray, NSObject<ABPlacePickerDelegate>, NSString, TweetieGeoSearchDelegate, TwitterPlace, UISearchBar, UISearchDisplayController, UITableView, UIView;

@interface TweetiePickPlaceViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate, ABTableViewPullToRefreshDelegate>
{
    int pickPlaceMode;
    UISearchDisplayController *searchController;
    TwitterPlace *pickedPlace;
    TweetieGeoSearchDelegate *geoSearchDelegate;
    UITableView *_tableView;
    UISearchBar *searchBar;
    NSObject<ABPlacePickerDelegate> *delegate;
    NSString *token;
    ABTableViewPullToRefreshController *pullToRefreshController;
    NSMutableArray *places;
    UIView *loadingView;
    BOOL isSearching;
    BOOL isLoadingNewer;
    BOOL refreshOnLoad;
}

- (void)_refresh;
- (void)_endNotifications;
- (void)loadView;
- (void)viewDidLoad;
@property(readonly, nonatomic) NSMutableArray *places;
- (void)userDidTouchCancel:(id)arg1;
- (void)userDidTouchClear:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)pullToRefreshController:(id)arg1 didActivate:(BOOL)arg2;
- (void)updateList;
- (void)nearbyPlacesDidRefresh:(id)arg1;
- (void)nearbyPlacesDidError:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidUnload;
- (void)dealloc;
@property(nonatomic) BOOL refreshOnLoad; // @synthesize refreshOnLoad;
@property(nonatomic) BOOL isLoadingNewer; // @synthesize isLoadingNewer;
@property(retain, nonatomic) NSObject<ABPlacePickerDelegate> *delegate; // @synthesize delegate;
@property(retain, nonatomic) TwitterPlace *pickedPlace; // @synthesize pickedPlace;

@end

