/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class NSString, TwitterAccount, UIBarButtonItem, UIPopoverController;

@interface TweetieEditProfileViewController : ABStaticTableViewController <UIActionSheetDelegate, UIPopoverControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    id <TweetieEditProfileViewControllerDelegate> editProfileDelegate;
    TwitterAccount *account;
    UIBarButtonItem *saveButton;
    NSString *updatedProfileImageFile;
    NSString *updatedName;
    NSString *updatedURL;
    NSString *updatedLocation;
    NSString *updatedBio;
    UIPopoverController *imagePickerPopover;
}

+ (void)_showIfError:(id)arg1;
+ (void)updateProfileImageResponse:(id)arg1 info:(id)arg2;
+ (void)updateProfileResponse:(id)arg1 info:(id)arg2;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)loadTableView;
- (void)profileImage:(id)arg1;
- (BOOL)canUpdateImage;
- (BOOL)canUpdateProfile;
- (BOOL)canSave;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)name:(id)arg1;
- (void)setName:(id)arg1 info:(id)arg2;
- (void)url:(id)arg1;
- (void)setURL:(id)arg1 info:(id)arg2;
- (void)location:(id)arg1;
- (void)setLocation:(id)arg1 info:(id)arg2;
- (void)bio:(id)arg1;
- (void)setBio:(id)arg1 info:(id)arg2;
- (void)viewDidLoad;
- (void)choseMedia:(id)arg1 info:(id)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)cancel:(id)arg1;
- (void)save:(id)arg1;
@property(nonatomic) id <TweetieEditProfileViewControllerDelegate> editProfileDelegate; // @synthesize editProfileDelegate;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

