/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@interface TweetieUserProfile4WayCornerSelectionView : UIView
{
    int cornerMask;
}

- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) int cornerMask; // @synthesize cornerMask;

@end

