/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABSimplePersistentRecentSearchViewController.h"

@class TwitterAccount;

@interface TweetieNewSearchViewController : ABSimplePersistentRecentSearchViewController
{
    TwitterAccount *account;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (id)defaultsKey;
- (id)placeholderText;
- (id)unmatchedResultFormatText;
- (void)search:(id)arg1;
- (void)cancel:(id)arg1;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

