/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "TweetieAddAccountViewControllerDelegate-Protocol.h"

@class NSMutableDictionary;

@interface TweetieSettingsViewController : ABStaticTableViewController <TweetieAddAccountViewControllerDelegate>
{
    id delegate;
    NSMutableDictionary *accountSections;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)done:(id)arg1;
- (void)addAccount:(id)arg1;
- (void)addAccountController:(id)arg1 didAddAccount:(id)arg2;
- (void)accountDetails:(id)arg1;
- (void)loadPushSettings:(id)arg1;
- (void)didLoadPushSettings:(id)arg1 info:(id)arg2;
- (id)_pushRowForAccount:(id)arg1;
- (void)loadTableView;
- (void)fontSizeUpdate:(id)arg1 info:(id)arg2;
- (void)displayNameUpdate:(id)arg1 info:(id)arg2;
@property(nonatomic) id delegate; // @synthesize delegate;

@end

