/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, TweetieSearchAllTweetsController, TweetieSearchNearbyController, TweetieSearchPeopleController, TwitterAccount, UISearchDisplayController, UIViewController;

@interface TweetieSearchTopicOrNameViewController : NSObject <UISearchDisplayDelegate, UISearchBarDelegate, UITableViewDelegate, UITableViewDataSource>
{
    TwitterAccount *account;
    UIViewController *mainSearchViewController;
    TweetieSearchAllTweetsController *allTweets;
    TweetieSearchNearbyController *nearby;
    TweetieSearchPeopleController *people;
    UISearchDisplayController *searchController;
}

- (id)init;
- (void)dealloc;
- (int)currentMode;
- (id)currentSearchController;
@property(readonly, nonatomic) NSString *searchString;
- (void)searchAllTweets:(id)arg1;
- (void)searchNearby:(id)arg1 coordinates:(CDStruct_2c43369c)arg2;
- (void)findUsers:(id)arg1;
- (void)goToUser:(id)arg1;
- (void)locationDidUpdate;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchScope:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (BOOL)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
@property(readonly, nonatomic) UISearchDisplayController *searchController; // @synthesize searchController;
@property(nonatomic) UIViewController *mainSearchViewController; // @synthesize mainSearchViewController;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

