/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieStatusStreamViewController.h"

@class TwitterAccountStream;

@interface TweetieRetweetStreamViewController : TweetieStatusStreamViewController
{
    int streamType;
    TwitterAccountStream *stream;
}

- (void)dealloc;
- (void)_updateTitle;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)statusStream;
@property(nonatomic) int streamType; // @synthesize streamType;

@end

