/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABTableViewCell.h"

@class TwitterDummyGapStatus, UIActivityIndicatorView;

@interface TweetieStatusGapCell : ABTableViewCell
{
    TwitterDummyGapStatus *gapStatus;
    UIActivityIndicatorView *spinner;
}

- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;
- (void)drawContentView:(struct CGRect)arg1;
- (void)_updateSpinner;
@property(retain, nonatomic) TwitterDummyGapStatus *gapStatus; // @synthesize gapStatus;
- (void)gapStateNotification:(id)arg1;

@end

