/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieStatusCell.h"

@interface TweetieStatusCell (Drawing)
+ (void)initialize;
- (id)displayNameForUser:(id)arg1;
- (void)displayDate:(id *)arg1 alt:(id *)arg2;
- (void)drawContent_simple:(struct CGRect)arg1;
@end

