/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class ABStaticTableViewCheckmarkElement, ABStaticTableViewSectionElement, TwitterAccount;

@interface TweetiePushSettingsViewController : ABStaticTableViewController
{
    ABStaticTableViewSectionElement *mentionsSection;
    ABStaticTableViewCheckmarkElement *followerElement;
    ABStaticTableViewCheckmarkElement *allElement;
    TwitterAccount *account;
}

- (id)init;
- (void)updateServer;
- (void)switchedTweets:(id)arg1 info:(id)arg2;
- (void)switchedMessages:(id)arg1 info:(id)arg2;
- (void)checkedFollowers:(id)arg1 info:(id)arg2;
- (void)checkedAll:(id)arg1 info:(id)arg2;
- (void)expandMentionLevels;
- (void)hideMentionLevels;
- (void)switchedMentions:(id)arg1 info:(id)arg2;
- (void)refreshMentionLevels;
- (void)loadTableView;
- (void)dealloc;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

