/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UINavigationController.h"

@interface TweetieNavigationController : UINavigationController
{
    BOOL didRegisterForCompositionUpdates;
}

- (void)dealloc;
- (id)originatingTweet;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (BOOL)isWorthPoppingToMainScreen;
- (void)pushViewController:(id)arg1 animated:(BOOL)arg2;
- (id)popViewControllerAnimated:(BOOL)arg1;
- (id)accountMainViewController;
- (void)_doPop;
- (void)navigationGesture:(id)arg1;
- (void)compositionWillSend:(id)arg1;
- (void)compositionDidSend:(id)arg1;
- (void)compositionDidUploadAttachment:(id)arg1;
- (void)ab_attemptToRecordImpressionFromReferringEvent:(id)arg1;
- (void)ab_resetImpression;

@end

