/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "TweetieTweetViewControllerDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, TwitterAccount, TwitterStatus, UIActivityIndicatorView, UIImageView, UILabel, UISearchBar, UISearchDisplayController, UITableView, UITableViewCell, UIView;

@interface TweetieStatusListViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UISearchDisplayDelegate, TweetieTweetViewControllerDelegate>
{
    TwitterAccount *account;
    UITableView *_tableView;
    UILabel *lastUpdatedLabel;
    UILabel *loadNewerLabel;
    UIImageView *loadNewerArrowView;
    UIActivityIndicatorView *loadNewerSpinner;
    UIView *headerExtra;
    UISearchBar *searchBar;
    UISearchDisplayController *searchDisplayController;
    NSArray *newStatuses;
    NSArray *statuses;
    NSArray *filteredStatuses;
    UITableViewCell *currentContextModeCell;
    TwitterStatus *flyToStatusUponReturningToView;
    struct {
        unsigned int updateWithNewStatusesOnScrollingEnd:1;
        unsigned int loadNewerUIInReleaseState:2;
        unsigned int forceSearchBarOffscreen:1;
        unsigned int isLoadingNewer:1;
        unsigned int disruptorDidActivate:1;
        unsigned int extraDisruptorInset:1;
        unsigned int needToActivateState:2;
        unsigned int activateDisruptorOnScrollingEnd:1;
        unsigned int activateDisruptorWhenContentIsReady:1;
        unsigned int noStatuses:1;
        unsigned int recordNextDisruptorImpression:1;
    } _flags;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)endContextModeForCell:(id)arg1;
- (void)endContextModeForCurrentCell;
- (void)beginContextModeForCell:(id)arg1;
- (float)_headerHeight;
- (void)_performScrollingEndUpdates;
- (void)_setLoadNewerState:(int)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)_updateLoadingNewerState;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (BOOL)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidScrollToTop:(id)arg1;
- (id)lastUpdated;
- (void)_updateLastUpdatedLabel;
- (void)reload;
- (id)autosaveName;
- (id)_topSavedStatusIDDefaultsKey;
- (id)_topSavedStatusIDOffsetDefaultsKey;
- (void)requestTopStatusID;
- (void)noteNewTopStatusID:(id)arg1;
- (void)saveScrollPosition;
- (id)statusForRow:(int)arg1;
- (float)heightForRow:(int)arg1 inTableView:(id)arg2;
- (float)_verticalOffsetOfRow:(int)arg1;
- (void)restoreScrollPosition;
- (BOOL)isScrolling;
- (void)_updateWithNewStatuses;
@property(retain, nonatomic) NSArray *statuses; // @synthesize statuses;
- (id)appropriateSearchDisplayContentsController;
- (id)placeholderSearchStringForFilterBar;
- (void)loadHeaderView;
- (float)_headerExtraOffset;
- (void)loadView;
- (void)_updateLoadingNewerState:(BOOL)arg1;
@property(readonly, nonatomic) UITableView *tableView;
- (BOOL)shouldHideHeaderOnLoad;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (id)scribePage;
- (id)scribeSection;
- (void)loadOlder:(id)arg1;
- (BOOL)canLoadNewer;
- (void)loadNewer:(id)arg1;
- (void)viewedMostRecent:(id)arg1;
- (id)indexPathForStatus:(id)arg1 inStatusesArray:(id)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)doubleTappedRepresentativeTabItem;
- (void)viewDidAppear:(BOOL)arg1;
- (void)didBecomeActive:(id)arg1;
- (void)viewWillSwitchToAnotherSubTab;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)searchDisplayControllerWillBeginSearch:(id)arg1;
- (void)searchDisplayController:(id)arg1 didLoadSearchResultsTableView:(id)arg2;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (id)filteredStatusForRow:(int)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (BOOL)disableMentionHighlighting;
- (BOOL)isLoadingNewer;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willBeginEditingRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(int)arg2 forRowAtIndexPath:(id)arg3;
- (void)_navigateToStatus:(id)arg1 animated:(BOOL)arg2;
- (id)_activeStatusesArray;
- (id)_nonDummyActiveStatusArray;
- (void)fillInGap:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)pinchBegan:(id)arg1;
- (void)pinchChanged:(id)arg1;
- (void)pinchEnded:(id)arg1;
- (id)_statusAdjacentToStatus:(id)arg1 inDirection:(int)arg2;
- (BOOL)tweetViewController:(id)arg1 canNavigate:(int)arg2;
- (void)tweetViewController:(id)arg1 navigate:(int)arg2;
- (void)tweetViewController:(id)arg1 getCurrentIndex:(int *)arg2 of:(int *)arg3;
- (void)_commonContextAction:(id)arg1;
- (void)statusCellContextReplyAction:(id)arg1;
- (void)statusCellContextLinkAction:(id)arg1;
- (void)statusCellContextRetweetAction:(id)arg1;
- (void)statusCellContextUserAction:(id)arg1;
- (void)statusCellContextFavoriteAction:(id)arg1;
- (void)statusCellContextActionAction:(id)arg1;
@property(retain, nonatomic) NSArray *filteredStatuses; // @synthesize filteredStatuses;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

