/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class TwitterAccount, TwitterListList, TwitterUser;

@interface TweetieListListViewController : ABStaticTableViewController
{
    TwitterAccount *account;
    TwitterUser *user;
    TwitterListList *listList;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (id)persistentProxy;
- (void)loadTableView;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)listListsDidUpdateNotification:(id)arg1;
- (void)viewList:(id)arg1;
@property(retain, nonatomic) TwitterListList *listList; // @synthesize listList;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

