/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "TweetieAddAccountAdvancedViewControllerDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class ABHUD, NSString, UIBarButtonItem, UITextField;

@interface TweetieAddAccountViewController : ABStaticTableViewController <UITextFieldDelegate, TweetieAddAccountAdvancedViewControllerDelegate>
{
    id <TweetieAddAccountViewControllerDelegate> delegate;
    UIBarButtonItem *saveButton;
    UITextField *usernameField;
    UITextField *passwordField;
    NSString *apiEndpointText;
    NSString *searchAPIEndpointText;
    BOOL hidesCancelButton;
    ABHUD *hud;
}

- (void)dealloc;
- (void)loadTableView;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)advanced:(id)arg1;
- (void)tweetieAddAccountAdvancedViewControllerDismiss:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (BOOL)canSubmit;
- (void)_updateSaveButton;
- (void)viewDidAppear:(BOOL)arg1;
- (void)cancel:(id)arg1;
- (void)save:(id)arg1;
- (void)didVerifyXAuth:(id)arg1 info:(id)arg2;
- (BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (BOOL)textFieldShouldReturn:(id)arg1;
@property(nonatomic) BOOL hidesCancelButton; // @synthesize hidesCancelButton;
@property(nonatomic) id <TweetieAddAccountViewControllerDelegate> delegate; // @synthesize delegate;

@end

