/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieUserPerAccountToggleViewController.h"

@interface TweetieUserFollowViewController : TweetieUserPerAccountToggleViewController
{
}

- (void)viewDidLoad;
- (id)footerText;
- (void)toggleOnFromAccount:(id)arg1;
- (void)toggleOffFromAccount:(id)arg1;
- (void)requestToggleStateForAccount:(id)arg1;
- (void)doesFollowResponse:(id)arg1 info:(id)arg2;

@end

