/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "UIActionSheetDelegate-Protocol.h"

@class NSArray, TwitterAccount, TwitterEntityURL, TwitterStatus, UIActionSheet, UINavigationController;

@interface TweetieLinksAction : NSObject <UIActionSheetDelegate>
{
    TwitterAccount *account;
    TwitterStatus *statusContext;
    UINavigationController *navigationController;
    NSArray *links;
    UIActionSheet *_linkSheet;
    UIActionSheet *_linkSelectorSheet;
    TwitterEntityURL *selectedEntityURL;
    BOOL showOpenButton;
    BOOL showOpenInSafariButton;
    BOOL showShareablesButton;
    int openButtonIndex;
    int openInSafariButtonIndex;
    int mailLinkButtonIndex;
    int repostLinkButtonIndex;
    int readLaterButtonIndex;
    int shareablesButtonIndex;
}

+ (id)actionController;
- (void)dealloc;
- (void)specificLinkAction:(id)arg1;
- (void)expandURLResponse:(id)arg1 info:(id)arg2;
- (void)linkAction:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)showFromNavigationController:(id)arg1;
@property(nonatomic) BOOL showOpenInSafariButton; // @synthesize showOpenInSafariButton;
@property(nonatomic) BOOL showOpenButton; // @synthesize showOpenButton;
@property(copy, nonatomic) NSArray *links; // @synthesize links;
@property(retain, nonatomic) TwitterStatus *statusContext; // @synthesize statusContext;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

