/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "UIActionSheetDelegate-Protocol.h"

@class TwitterAccount, TwitterList;

@interface TweetieListDetailsViewController : ABStaticTableViewController <UIActionSheetDelegate>
{
    TwitterAccount *account;
    TwitterList *list;
    id bioSection;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (void)_updateTitle;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)loadTableView;
- (void)user:(id)arg1;
- (void)following:(id)arg1;
- (void)followers:(id)arg1;
- (void)share:(id)arg1;
- (void)edit:(id)arg1;
- (void)didEditList:(id)arg1 info:(id)arg2;
- (void)delete:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)viewWillAppear:(BOOL)arg1;
- (void)compose:(id)arg1;
- (id)toolbarItemArray;
- (void)flip:(id)arg1;
- (void)followList:(id)arg1;
- (void)unfollowList:(id)arg1;
- (void)confirmFollow:(id)arg1 info:(id)arg2;
- (void)confirmUnfollow:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) TwitterList *list; // @synthesize list;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

