/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@class NSMutableArray;

@interface TweetieComposeActionView : UIView
{
    id <TweetieComposeActionViewDelegate> delegate;
    NSMutableArray *actionButtons;
    BOOL highlightGeotagButton;
}

- (id)buttonImage:(id)arg1 highlight:(BOOL)arg2;
- (void)_addButton:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) BOOL highlightGeotagButton; // @synthesize highlightGeotagButton;
- (void)dealloc;
- (void)buttonAction:(id)arg1;
- (struct CGRect)frameForButton:(int)arg1;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) id <TweetieComposeActionViewDelegate> delegate; // @synthesize delegate;

@end

