/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIButton.h"

@class NSString;

@interface TweetieComposeTitleView : UIButton
{
    NSString *title;
    NSString *subtitle;
    struct {
        unsigned int touchDown:1;
    } _flags;
}

- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (void)_drawPortraitStyle;
- (void)_drawLandscapeStyle;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)cancelTrackingWithEvent:(id)arg1;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle;
@property(retain, nonatomic) NSString *title; // @synthesize title;

@end

