/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieStatusStreamViewController.h"

#import "UIActionSheetDelegate-Protocol.h"

@class TwitterConversationStream, TwitterStatus;

@interface TweetieReplyChainViewController : TweetieStatusStreamViewController <UIActionSheetDelegate>
{
    TwitterStatus *baseStatus;
    TwitterConversationStream *conversationStream;
}

- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)viewDidLoad;
- (id)statusStream;
- (id)placeholderSearchStringForFilterBar;
- (BOOL)canLoadNewer;
- (void)reply:(id)arg1;
- (void)action:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
@property(retain, nonatomic) TwitterStatus *baseStatus; // @synthesize baseStatus;

@end

