/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "TweetieComposeViewControllerDelegate-Protocol.h"

@class TweetieComposeViewController, UINavigationController;

@interface TweetieComposeController : NSObject <TweetieComposeViewControllerDelegate>
{
    TweetieComposeViewController *composeViewController;
    UINavigationController *sourceNavigationController;
    struct {
        unsigned int isBeingForceDismissed:1;
    } _flags;
}

+ (Class)noAnimation;
+ (id)controller;
+ (id)composeWithComposition:(id)arg1 fromAccount:(id)arg2 sourceNavigationController:(id)arg3;
+ (void)newTweetFromAccount:(id)arg1 sourceNavigationController:(id)arg2;
+ (void)newTweetWithText:(id)arg1 fromAccount:(id)arg2 sourceNavigationController:(id)arg3;
+ (void)replyToTweet:(id)arg1 fromAccount:(id)arg2 sourceNavigationController:(id)arg3;
+ (void)quoteTweet:(id)arg1 fromAccount:(id)arg2 sourceNavigationController:(id)arg3;
+ (void)repostLink:(id)arg1 fromStatus:(id)arg2 fromAccount:(id)arg3 sourceNavigationController:(id)arg4;
+ (void)retweet:(id)arg1 fromAccount:(id)arg2 sourceNavigationController:(id)arg3;
+ (void)retweetResponse:(id)arg1 info:(id)arg2;
+ (void)replyToUser:(id)arg1 fromAccount:(id)arg2 sourceNavigationController:(id)arg3;
+ (void)directMessageUser:(id)arg1 fromAccount:(id)arg2 sourceNavigationController:(id)arg3;
+ (void)directMessageUsername:(id)arg1 fromAccount:(id)arg2 sourceNavigationController:(id)arg3;
- (BOOL)animated;
- (void)dealloc;
- (void)forceDismissAndSaveAsDraft;
- (void)showComposeViewController:(id)arg1 sourceNavigationController:(id)arg2;
- (void)composeViewControllerDidDismiss:(id)arg1;

@end

