/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieSearchAllTweetsController.h"

@class CLLocation, MKPlacemark;

@interface TweetieSearchNearbyController : TweetieSearchAllTweetsController
{
    id gpsRequestToken;
    MKPlacemark *mostRecentPlacemark;
    CLLocation *mostRecentLocation;
}

- (void)dealloc;
- (BOOL)_isNearbySearch;
- (void)startSearch:(id)arg1;
- (id)nearString;
- (void)locationUpdate:(id)arg1;
@property(retain, nonatomic) CLLocation *mostRecentLocation; // @synthesize mostRecentLocation;
@property(retain, nonatomic) MKPlacemark *mostRecentPlacemark; // @synthesize mostRecentPlacemark;

@end

