/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIWindow.h"

@interface TweetieWindow : UIWindow
{
    struct CGPoint startTouch;
    struct {
        unsigned int touchState:3;
    } _flags;
}

- (struct CGPoint)_ab_convertPoint:(struct CGPoint)arg1;
- (void)sendEvent:(id)arg1;

@end

