/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class TweetiePickPlaceViewController, TwitterPlaceResponse, UISearchDisplayController;

@interface TweetieGeoSearchDelegate : NSObject <UITableViewDataSource, UITableViewDelegate, UISearchBarDelegate, UISearchDisplayDelegate>
{
    TwitterPlaceResponse *searchResponse;
    UISearchDisplayController *searchController;
    TweetiePickPlaceViewController *picker;
    BOOL isSearching;
}

- (BOOL)emptyResults;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (id)grayCell:(id)arg1;
- (id)promptCell:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)searchDidLoad:(id)arg1 info:(id)arg2;
- (void)performSearch;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (BOOL)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)dealloc;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
@property(retain, nonatomic) TweetiePickPlaceViewController *picker; // @synthesize picker;
@property(retain, nonatomic) UISearchDisplayController *searchController; // @synthesize searchController;

@end

