/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieStatusStreamViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class TwitterSearch, UIActionSheet, UIBarButtonItem;

@interface TweetieSearchResultsViewController : TweetieStatusStreamViewController <UITextFieldDelegate, UIActionSheetDelegate>
{
    TwitterSearch *search;
    UIBarButtonItem *saveSearchButton;
    UIBarButtonItem *moreInfoButton;
    BOOL isTrend;
    UIActionSheet *saveSearchSheet;
    UIActionSheet *removeSavedSearchSheet;
    UIActionSheet *stockInfoSheet;
}

- (void)setupToolbar;
- (id)scribePage;
- (id)scribeSection;
- (id)init;
- (void)dealloc;
- (void)_updateTitle;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewDidAppear:(BOOL)arg1;
- (BOOL)isSavedSearch;
- (BOOL)isHashtag;
- (BOOL)definitionsEnabled;
- (BOOL)isStockLink;
- (id)stockSymbol;
- (void)_updateToolbar;
- (void)viewWillAppear:(BOOL)arg1;
- (id)statusStream;
- (void)compose:(id)arg1;
- (void)searchDisplayControllerWillEndSearch:(id)arg1;
- (void)moreInfo:(id)arg1;
- (void)defineResponse:(id)arg1 info:(id)arg2;
- (void)showDefinitonPanelForTerm:(id)arg1 existingDefinition:(id)arg2;
- (void)didDefine:(id)arg1 info:(id)arg2;
- (void)shouldDefine:(id)arg1 info:(id)arg2;
- (void)willPresentActionSheet:(id)arg1;
- (void)didPresentActionSheet:(id)arg1;
- (void)saveSearch:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (BOOL)shouldHideHeaderOnLoad;
@property(nonatomic) BOOL isTrend; // @synthesize isTrend;
@property(retain, nonatomic) TwitterSearch *search; // @synthesize search;

@end

