/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieStatusStreamViewController.h"

@class TwitterList;

@interface TweetieListViewController : TweetieStatusStreamViewController
{
    TwitterList *list;
}

- (void)dealloc;
- (void)_updateTitle;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (id)statusStream;
- (void)viewWillAppear:(BOOL)arg1;
- (void)compose:(id)arg1;
- (void)flip:(id)arg1;
- (void)followList:(id)arg1;
- (void)unfollowList:(id)arg1;
- (void)confirmFollow:(id)arg1 info:(id)arg2;
- (void)confirmUnfollow:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) TwitterList *list; // @synthesize list;

@end

