/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString, NSURL, TwitterUser;

@interface TweetBlocker : NSObject
{
    id <TweetBlockerDelegate> delegate;
    TwitterUser *user;
    BOOL loading;
    NSString *score;
    NSString *grade;
    NSURL *gradeImageURL;
}

- (id)apiRoot;
- (id)apiKey;
- (void)_loadRating;
- (void)reportSpammer;
- (void)reportSpamResponse:(id)arg1 info:(id)arg2;
- (void)_loadRatingResponse:(id)arg1 info:(id)arg2;
- (id)initWithTwitterUser:(id)arg1;
- (void)dealloc;
- (void)parseJSON:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSURL *gradeImageURL; // @synthesize gradeImageURL;
@property(copy, nonatomic) NSString *score; // @synthesize score;
@property(copy, nonatomic) NSString *grade; // @synthesize grade;
@property(readonly, nonatomic) BOOL loading; // @synthesize loading;
@property(nonatomic) id <TweetBlockerDelegate> delegate; // @synthesize delegate;

@end

