/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class TwitterAccount;

@interface TweetieMoreViewController : ABStaticTableViewController
{
    TwitterAccount *account;
    id listSection;
    int lastListsCount;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (id)backBarButtonItemTitle;
- (id)lists;
- (void)_setupListSection;
- (void)aboutRED:(id)arg1;
- (void)joinRED:(id)arg1;
- (void)sul:(id)arg1;
- (void)loadTableView;
- (void)benchmarks:(id)arg1;
- (void)accountsAndSettings:(id)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)myProfile:(id)arg1;
- (void)favorites:(id)arg1;
- (void)drafts:(id)arg1;
- (void)listsDidUpdate:(id)arg1;
- (void)viewList:(id)arg1;
- (void)createList:(id)arg1;
- (void)createListResponse:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

