/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface Tweetshrink : NSObject
{
    int difference;
    NSString *text;
}

+ (void)shrink:(id)arg1 callback:(id)arg2;
+ (void)didShrink:(id)arg1 info:(id)arg2;
- (void)dealloc;
- (void)parseXML:(id)arg1 info:(id)arg2;
- (int)difference;
@property(copy, nonatomic) NSString *text; // @synthesize text;

@end

