/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

@protocol TweetieTweetViewControllerDelegate
- (BOOL)tweetViewController:(id)arg1 canNavigate:(int)arg2;
- (void)tweetViewController:(id)arg1 navigate:(int)arg2;
- (void)tweetViewController:(id)arg1 getCurrentIndex:(int *)arg2 of:(int *)arg3;
@end

