/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieStatusStreamViewController.h"

@class TwitterUser, TwitterUserFavoritesStream;

@interface TweetieUserFavoritesViewController : TweetieStatusStreamViewController
{
    TwitterUser *user;
    TwitterUserFavoritesStream *stream;
}

- (void)recordImpressionFromReferringEvent:(id)arg1;
- (void)dealloc;
- (id)statusStream;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;

@end

