/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "ABPersonViewControllerDelegate-Protocol.h"
#import "ABUnknownPersonViewControllerDelegate-Protocol.h"
#import "TweetieUserPerAccountToggleViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class TwitterAccount, TwitterUser, UIActionSheet, UIButton, UIImageView, UILabel;

@interface TweetieUserProfileViewController : ABStaticTableViewController <UIActionSheetDelegate, ABPersonViewControllerDelegate, ABUnknownPersonViewControllerDelegate, TweetieUserPerAccountToggleViewControllerDelegate>
{
    id <TweetieUserProfileViewControllerDelegate> delegate;
    TwitterAccount *account;
    TwitterUser *user;
    UIButton *_profileImageButton;
    UIButton *_contactCardButton;
    UILabel *_usernameLabel;
    UILabel *_usernameLabel2;
    UILabel *_userNumberLabel;
    UILabel *_bioLabel;
    UIImageView *_protectedView;
    UIImageView *_verifiedView;
    BOOL iFollowThem;
    BOOL iFollowThem_pending;
    BOOL theyFollowMe;
    id bioSection;
    id actionsSection;
    id followButton;
    UIActionSheet *_followSheet;
    UIActionSheet *_unfollowSheet;
    UIActionSheet *_notificationsSheet;
    UIActionSheet *_reportSpamSheet;
    struct {
        unsigned int loadingFollowStatus:1;
        unsigned int didLoadFollowStatus:1;
        unsigned int errorLoadingFollowStatus:1;
    } _flags;
    CDStruct_daa5b662 _impressionFlags;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)dealloc;
- (BOOL)userIsLoaded;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)userDidUpdate:(id)arg1;
- (void)_loadFollowStateIfNeededAndPossible;
- (void)_updateFollowButton;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;
- (void)followStatus:(id)arg1 info:(id)arg2;
- (void)viewLargeProfileImage:(id)arg1;
- (BOOL)isMe;
- (void)loadTableView;
- (void)_follow;
- (void)didFollow:(id)arg1 info:(id)arg2;
- (id)_originatingTweet;
- (void)follow:(id)arg1;
- (void)unfollow:(id)arg1;
- (void)addToList:(id)arg1;
- (void)showListList:(id)arg1;
- (void)usersLists:(id)arg1;
- (void)subscribedToLists:(id)arg1;
- (void)memberOfLists:(id)arg1;
- (void)dismissAddToList:(id)arg1 info:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)bio:(id)arg1;
- (void)web:(id)arg1;
- (void)location:(id)arg1;
- (void)followers:(id)arg1;
- (void)following:(id)arg1;
- (void)favorites:(id)arg1;
- (void)tweets:(id)arg1;
- (void)_showRetweetStreamType:(int)arg1;
- (void)retweetedToMe:(id)arg1;
- (void)retweetsOfMe:(id)arg1;
- (void)retweetedByMe:(id)arg1;
- (void)tweetblocker:(id)arg1;
- (void)followcost:(id)arg1;
- (void)favrd:(id)arg1;
- (void)overlapr:(id)arg1;
- (void)reportSpam:(id)arg1;
- (void)favstar:(id)arg1;
- (void)tweeteorites:(id)arg1;
- (void)block:(id)arg1;
- (void)multiFollow:(id)arg1;
- (void)dismissPerAccountToggleViewController:(id)arg1;
- (void)notification:(id)arg1;
- (void)showContactCardAnimated:(BOOL)arg1;
- (void)_showContactCardAnimated;
- (void)contactCard:(id)arg1;
- (BOOL)_actionForPerson:(void *)arg1 property:(int)arg2 identifier:(int)arg3;
- (BOOL)personViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (BOOL)unknownPersonViewController:(id)arg1 shouldPerformDefaultActionForPerson:(void *)arg2 property:(int)arg3 identifier:(int)arg4;
- (void)unknownPersonViewController:(id)arg1 didResolveToPerson:(void *)arg2;
- (void)ab_attemptToRecordImpressionFromReferringEvent:(id)arg1;
- (void)ab_resetImpression;
@property(nonatomic) id <TweetieUserProfileViewControllerDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

