/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

#import "TweetBlockerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class TweetBlocker, TwitterAccount, TwitterUser, UITableViewCell;

@interface TweetBlockerViewController : ABStaticTableViewController <TweetBlockerDelegate, UIActionSheetDelegate>
{
    TwitterAccount *account;
    TwitterUser *user;
    TweetBlocker *tweetBlocker;
    UITableViewCell *gradeCell;
    BOOL reported;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)loadTableView;
- (void)viewDidLoad;
- (void)reportSpammer:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)tweetBlocker:(id)arg1 error:(id)arg2;
- (void)dismissError:(id)arg1 info:(id)arg2;
- (void)tweetBlockerDidUpdate:(id)arg1;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

