/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TweetieComposeViewController.h"

@interface TweetieComposeViewController (ABAdditions)
- (BOOL)isWorthSaving;
- (BOOL)isWorthSending;
- (void)setText:(id)arg1;
- (void)appendWhitespaceAndText:(id)arg1;
- (void)appendUsername:(id)arg1;
- (void)_didAddAttachment:(id)arg1;
- (void)_handleMedia:(id)arg1;
- (void)handleMedia:(id)arg1 info:(id)arg2;
- (void)shortenURLsResponse:(id)arg1 info:(id)arg2;
@end

