/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "MKMapViewDelegate-Protocol.h"

@class ABHUD, CALayer, MKMapView, NSMutableArray, NSMutableSet, TwitterAccount, TwitterSearch;

@interface TweetieNearbyViewController : UIViewController <MKMapViewDelegate>
{
    TwitterAccount *account;
    TwitterSearch *search;
    MKMapView *_mapView;
    NSMutableSet *statusesOnMap;
    NSMutableArray *annotations;
    BOOL didFirstAnimation;
    CALayer *sweepLayer;
    ABHUD *hud;
    struct _flags;
}

+ (id)map_list_toolbarItems:(int)arg1 target:(id)arg2 action:(SEL)arg3;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)switchTo:(id)arg1;
- (void)dealloc;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)loadView;
- (void)viewDidLoad;
- (void)currentLocation:(id)arg1 info:(id)arg2;
- (void)viewDidUnload;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)_loadNearby;
- (void)doSweepAnimation;
- (void)searchDidUpdate:(id)arg1;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (void)refresh:(id)arg1;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 didAddAnnotationViews:(id)arg2;
- (void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

