/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABSubTabBarController.h"

#import "ABSubTabBarControllerDelegate-Protocol.h"
#import "ChooseUserViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class TwitterAccount;

@interface TweetieMainViewController : ABSubTabBarController <ABSubTabBarControllerDelegate, UIActionSheetDelegate, ChooseUserViewControllerDelegate>
{
    TwitterAccount *account;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)init;
- (void)dealloc;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;
- (id)persistentProxy;
- (void)decodeWithPersistentProxy:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)accountUpdateNotification:(id)arg1;
- (void)_doneSending;
- (void)updateSendingProgress:(float)arg1;
- (int)numberOfTabsInSubTabController:(id)arg1;
- (id)subTabBarController:(id)arg1 accessibilityLabelForIndex:(int)arg2;
- (id)subTabBarController:(id)arg1 barItemForIndex:(int)arg2;
- (id)subTabBarController:(id)arg1 viewControllerForIndex:(int)arg2;
- (BOOL)subTabBarController:(id)arg1 drawGlowForIndex:(int)arg2;
- (void)subTabBarController:(id)arg1 didSelectViewControllerAtIndex:(int)arg2;
- (void)subTabBarController:(id)arg1 doubleTapTabItemAtIndex:(int)arg2;
- (void)_newTweet;
- (void)_newDirectMessage;
- (void)compose:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)newConversationWith:(id)arg1;
- (void)chooseUserViewController:(id)arg1 didChooseUser:(id)arg2;
- (void)chooseUserViewController:(id)arg1 didChooseUsername:(id)arg2;
- (void)didLoadUserForDirectMessage:(id)arg1 info:(id)arg2;
- (void)chooseUserViewControllerDidCancel:(id)arg1;

@end

