/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (BlockMethods)
- (void)blockingIDs;
- (void)didReceiveBlockingIds:(id)arg1 info:(id)arg2;
- (void)blockUserID:(id)arg1;
- (void)blockUsername:(id)arg1;
- (void)unblockUserID:(id)arg1;
- (void)unblockUsername:(id)arg1;
- (id)blocksExistsCallback;
- (void)isBlockingUserID:(id)arg1;
- (void)isBlockingUsername:(id)arg1;
- (void)blocksExistsResponse:(id)arg1 info:(id)arg2;
- (void)ignoreRetweetsIDs;
- (void)didReceiveIgnoreRetweets:(id)arg1 info:(id)arg2;
@end

