/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "ABActiveTextRange-Protocol.h"
#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString, NSValue;

@interface TwitterEntity : NSObject <NSCoding, NSCopying, ABActiveTextRange>
{
    struct _NSRange range;
}

+ (void)parseEntityXML:(id)arg1 info:(id)arg2;
+ (void)setIndices:(id)arg1 parser:(id)arg2;
+ (void)parseEntitiesXML:(id)arg1 info:(id)arg2;
+ (void)parseEntityJSON:(id)arg1 info:(id)arg2;
+ (void)parseEntitiesJSON:(id)arg1 info:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) NSValue *rangeNSValue;
@property(readonly, nonatomic) NSString *displayString;
@property(readonly, nonatomic) struct _NSRange rangeValue;
@property(readonly, nonatomic) int rangeFlavor;
- (void)parseIndexJSON:(id)arg1 info:(id)arg2;
- (void)parseEntityJSON:(id)arg1 info:(id)arg2;
- (void)parseDict:(id)arg1;
@property(nonatomic) struct _NSRange range; // @synthesize range;

@end

