/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextViewDelegate-Protocol.h"

@class TwitterAccount, TwitterDirectMessage, TwitterDirectMessageConversation, UIBarButtonItem, UINavigationBar, UITableView, UITextView, UIView;

@interface TwitterPadDirectMessageConversationViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, UITextViewDelegate, UIActionSheetDelegate>
{
    TwitterAccount *account;
    TwitterDirectMessageConversation *conversation;
    UITableView *_tableView;
    UIView *bottomView;
    UITextView *_textView;
    UINavigationBar *_topBar;
    UIBarButtonItem *_send;
    float keyboardHeight;
    BOOL startReplyImmediately;
    struct {
        unsigned int rotating:1;
        unsigned int keyboardVisible:1;
    } _flags;
    TwitterDirectMessage *selectedMessage;
}

- (void)dealloc;
- (BOOL)_isInPopover;
- (id)currentComposition;
- (void)loadView;
- (void)_scrollToBottom:(BOOL)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)conversationDidUpdate:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(int)arg1;
- (void)_updateKeyboardChange:(id)arg1 animated:(BOOL)arg2;
- (void)send:(id)arg1;
- (void)cancel:(id)arg1;
- (void)keyboardShow:(id)arg1;
- (void)_scrollToBottomAnimated;
- (void)keyboardHide:(id)arg1;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)errorButtonTouch:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
@property(nonatomic) BOOL startReplyImmediately; // @synthesize startReplyImmediately;
@property(retain, nonatomic) TwitterDirectMessageConversation *conversation; // @synthesize conversation;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

