/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

@class GeoRSSPoint, MKMapView, TwitterPlace;

@interface TwitterPadPlaceViewController : UIViewController
{
    TwitterPlace *place;
    GeoRSSPoint *point;
    MKMapView *_mapView;
}

- (void)loadView;
@property(retain, nonatomic) GeoRSSPoint *point; // @synthesize point;
@property(retain, nonatomic) TwitterPlace *place; // @synthesize place;

@end

