/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface TwitterStream : NSObject
{
    double cacheTime;
}

@property(retain, nonatomic) NSArray *statuses;
- (void)loadNewer;
- (void)loadOlder;
- (void)fillInGap:(id)arg1;
- (BOOL)supportsFillingInGaps;
- (BOOL)hasData;
- (void)didLoadOlder;
- (id)lastUpdated;
- (BOOL)isLoadingNewer;
- (id)autosaveName;
- (void)noteNewTopStatusID:(id)arg1;
- (void)requestTopStatusID;
@property(readonly, nonatomic) NSString *emptyStreamMessage;
@property(nonatomic) double cacheTime; // @synthesize cacheTime;

@end

