/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStream.h"

#import "NSCoding-Protocol.h"

@class NSArray, NSDate, NSError, NSString, TwitterStatus;

@interface TwitterConcreteStatusesStream : TwitterStream <NSCoding>
{
    NSString *guid;
    NSArray *statuses;
    NSDate *lastUpdated;
    TwitterStatus *_newestStatus;
    NSError *loadNewerError;
    NSError *loadOlderError;
    struct {
        unsigned int isLoadingNewer:1;
        unsigned int isLoadingOlder:1;
        unsigned int isAtEnd:1;
        unsigned int loadingOlderLessThan20Count:5;
        unsigned int needsToLoadFromDisk:1;
        unsigned int needsToWriteToDisk:1;
        unsigned int loadConservatively:1;
    } _flags;
}

- (id)init;
- (id)guid;
- (id)storedStreamPath;
- (id)autosaveName;
- (void)_readFromDisk;
- (void)_writeToDisk;
- (void)saveStream;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)errorStatusForError:(id)arg1;
- (id)statuses;
- (id)newestStatus;
- (id)oldestStatus;
- (id)newestStatusID;
- (id)oldestStatusID;
- (id)lastUpdated;
- (void)postStatusesChangedNotification;
- (void)setStatuses:(id)arg1;
@property(nonatomic) BOOL loadConservatively;
- (BOOL)hasData;
- (id)definitiveStatuses:(id)arg1;
- (void)addStatus:(id)arg1;
- (int)maxCount;
- (BOOL)shouldIndexUsersInAutocomplete;
- (void)addStatuses:(id)arg1;
- (void)_deleteStatus:(id)arg1;
- (void)deleteStatusNotification:(id)arg1;
- (void)_postError:(id)arg1;
- (int)minStatusesToConsiderBeingGap;
- (void)statusesResponse:(id)arg1 couldBeGap:(BOOL)arg2 isFromFillingInGap:(BOOL)arg3;
- (void)loadNewerResponse:(id)arg1 info:(id)arg2;
- (void)markAtEnd;
- (void)loadOlderResponse:(id)arg1 info:(id)arg2;
- (void)fillInGapResponse:(id)arg1 info:(id)arg2;
- (void)_loadNewer;
- (void)_loadOlder;
- (void)loadNewer;
- (BOOL)isLoadingNewer;
- (void)loadOlder;
- (void)retryLoadOlder;
- (void)_loadBeforeGap:(id)arg1;
- (void)fillInGap:(id)arg1;
- (id)loadNewerResponseCallback;
- (id)loadOlderResponseCallback;
- (id)fillInGapResponseCallback:(id)arg1;
@property(retain, nonatomic) NSError *loadNewerError; // @synthesize loadNewerError;
@property(retain, nonatomic) NSError *loadOlderError; // @synthesize loadOlderError;

@end

