/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSString, TwitterAccount, TwitterListStream, TwitterUser;

@interface TwitterList : NSObject <NSCoding>
{
    TwitterAccount *account;
    NSString *listID;
    NSString *name;
    NSString *mode;
    NSString *slug;
    NSString *description;
    int subscriberCount;
    int memberCount;
    TwitterUser *user;
    TwitterListStream *stream;
}

+ (id)listWithDictionary:(id)arg1;
+ (id)listWithXML:(id)arg1;
+ (id)listsWithXML:(id)arg1;
+ (id)listWithSlug:(id)arg1 account:(id)arg2;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)assimilateList:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (int)compare:(id)arg1;
@property(readonly, nonatomic) NSString *fullName;
- (BOOL)isPrivate;
- (id)stream;
@property(nonatomic) TwitterAccount *account; // @synthesize account;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;
@property(nonatomic) int memberCount; // @synthesize memberCount;
@property(nonatomic) int subscriberCount; // @synthesize subscriberCount;
@property(retain, nonatomic) NSString *description; // @synthesize description;
@property(retain, nonatomic) NSString *slug; // @synthesize slug;
@property(retain, nonatomic) NSString *mode; // @synthesize mode;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *listID; // @synthesize listID;

@end

