/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterDummyEmptyStreamStatus.h"

@interface TwitterDummyEmptyStreamStatus (UIAdditions)
- (id)cellForTableView:(id)arg1 account:(id)arg2 delegate:(id)arg3 disableMentionHighlighting:(BOOL)arg4;
@end

