/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (Signup)
- (void)mobileSignupUsername:(id)arg1 password:(id)arg2 fullName:(id)arg3 email:(id)arg4 captchaToken:(id)arg5 captchaSolution:(id)arg6;
- (void)mobileSignupResponse:(id)arg1 info:(id)arg2;
- (void)generateAccountWithUsername:(id)arg1 password:(id)arg2 name:(id)arg3 email:(id)arg4 language:(id)arg5 timeZone:(id)arg6 discoverableByEmail:(id)arg7 discoverableByMobile:(id)arg8;
- (void)generateAccountResponse:(id)arg1 info:(id)arg2;
- (void)parseGenerateAccountErrorJSON:(id)arg1 info:(id)arg2;
- (void)xAuthRequestAccessTokens;
- (void)xAuthMigrateResponse:(id)arg1 info:(id)arg2;
@end

