/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (PlaceMethods)
- (void)geoSearch:(id)arg1;
- (void)reverseGeocode:(id)arg1;
- (void)topPlaces:(id)arg1;
- (void)similarPlaces:(id)arg1;
- (void)gotPlaces:(id)arg1 info:(id)arg2;
- (void)createPlace:(id)arg1;
- (void)findPlace:(id)arg1;
- (void)gotPlace:(id)arg1 info:(id)arg2;
@end

