/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (Follow)
- (void)checkIfUser:(id)arg1 follows:(id)arg2 callback:(id)arg3;
- (void)followingStatus:(id)arg1 info:(id)arg2;
- (void)user:(id)arg1 follows:(id)arg2 callback:(id)arg3;
- (void)userFollowsResponse:(id)arg1 info:(id)arg2;
- (void)followUserID:(id)arg1 callback:(id)arg2;
- (void)unfollowUserID:(id)arg1 callback:(id)arg2;
- (void)follow:(id)arg1 callback:(id)arg2;
- (void)stopFollowing:(id)arg1 callback:(id)arg2;
@end

