/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterCompositionAttachment.h"

@interface TwitterCompositionVideoAttachment : TwitterCompositionAttachment
{
}

- (id)title;
- (id)thumbnail;
- (void)_uploadFromAccount:(id)arg1 associatedMessage:(id)arg2 callback:(id)arg3;
- (void)didUploadVideo:(id)arg1 info:(id)arg2;
- (int)type;

@end

