/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (FavoriteMethods)
- (void)favoritesForUserID:(id)arg1 page:(id)arg2;
- (void)favoritesForUsername:(id)arg1 page:(id)arg2;
- (void)favoriteStatus:(id)arg1;
- (void)unfavoriteStatus:(id)arg1;
- (void)didFavorite:(id)arg1 info:(id)arg2;
@end

