/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITextView.h"

#import "MPMediaPickerControllerDelegate-Protocol.h"
#import "TIComposeAttachmentsViewDelegate-Protocol.h"
#import "TIComposeMapViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class TIComposeAttachmentsView, TIComposeMapView, TwitterPadComposeViewController, UIActivityIndicatorView, UIButton, UIPopoverController, UIView;

@interface TwitterPadComposeTextView : UITextView <UIPopoverControllerDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, TIComposeAttachmentsViewDelegate, TIComposeMapViewDelegate, UIActionSheetDelegate, MPMediaPickerControllerDelegate>
{
    TwitterPadComposeViewController *composeViewController;
    UIButton *at;
    UIButton *hashtag;
    UIButton *attachment;
    UIButton *geotag;
    UIActivityIndicatorView *geoSpinner;
    UIPopoverController *mediaPickerPopover;
    UIPopoverController *attachmentsPopover;
    UIPopoverController *mapPopover;
    id GPSRequestToken;
    struct CGRect originalAtRect;
    struct CGRect originalHashtagRect;
    struct CGRect originalGeoRect;
    struct CGRect originalAttachmentRect;
    TIComposeAttachmentsView *attachmentsView;
    TIComposeMapView *mapView;
    UIView *_buttonBar;
}

- (void)dealloc;
- (void)_shutdown;
- (void)_updateAttachments:(BOOL)arg1;
- (void)_updateGeotagButton:(BOOL)arg1;
- (void)updateButtons;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_typeText:(id)arg1;
- (void)_prepareForAutoComplete;
- (void)mention:(id)arg1;
- (void)hashtag:(id)arg1;
- (void)place:(id)arg1;
- (void)setContentSize:(struct CGSize)arg1;
- (void)setContentInset:(struct UIEdgeInsets)arg1;
- (void)_selectFromLibrary;
- (id)composition;
- (id)account;
- (void)camera:(id)arg1;
- (void)photoLibrary:(id)arg1;
- (void)didRemoveAttachment:(id)arg1;
- (void)attachment:(id)arg1;
- (void)didRemoveLastAttachment;
- (void)addAnotherAttachment;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (BOOL)geoEnabled;
- (void)setGeoEnabled:(BOOL)arg1;
- (void)geotag:(id)arg1;
- (void)gpsUpdate:(id)arg1 info:(id)arg2;
- (void)didSelectPlaceEntity:(id)arg1;
@property(nonatomic) TwitterPadComposeViewController *composeViewController; // @synthesize composeViewController;

@end

