/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (Block)
- (void)blockUserID:(id)arg1;
- (void)blockUsername:(id)arg1;
- (void)block:(id)arg1;
- (void)unblockUserID:(id)arg1;
- (void)unblockUsername:(id)arg1;
- (void)unblock:(id)arg1;
- (void)userID:(id)arg1 isBlocked:(id)arg2;
- (void)user:(id)arg1 isBlocked:(id)arg2;
- (void)isBlockedResponse:(id)arg1 info:(id)arg2;
- (void)blockUserAndRemoveAssociatedStatuses:(id)arg1;
@end

