/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStream.h"

@class NSArray;

@interface TwitterAggregateStatusesStream : TwitterStream
{
    NSArray *streams;
}

- (void)dealloc;
- (id)statuses;
@property(retain, nonatomic) NSArray *streams; // @synthesize streams;
- (void)streamDidUpdate:(id)arg1;

@end

