/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (Trends)
- (void)trendLocationsAt:(id)arg1;
- (void)trendsAtLocation:(id)arg1 excludingHashtags:(BOOL)arg2;
- (void)trendLocationsResponse:(id)arg1 info:(id)arg2;
- (void)_trends:(id)arg1 excludeHashtags:(BOOL)arg2;
- (void)trends;
- (void)currentTrendsExcludingHashtags:(BOOL)arg1;
- (void)dailyTrendsExcludingHashtags:(BOOL)arg1;
- (void)weeklyTrendsExcludingHashtags:(BOOL)arg1;
- (void)localTrendsResponse:(id)arg1 info:(id)arg2;
- (void)trendsResponse:(id)arg1 info:(id)arg2;
- (void)parseTrendsJSON:(id)arg1 info:(id)arg2;
@end

