/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterEntity.h"

@class NSString, NSURL;

@interface TwitterEntityURL : TwitterEntity
{
    NSURL *url;
    NSURL *expandedURL;
    NSString *displayURL;
    struct _NSRange rangeInDisplayText;
}

+ (void)parseEntityXML:(id)arg1 info:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)parseEntityJSON:(id)arg1 info:(id)arg2;
- (int)compare:(id)arg1;
- (id)displayString;
- (int)rangeFlavor;
- (struct _NSRange)rangeValue;
- (void)parseDict:(id)arg1;
- (id)description;
- (void)dealloc;
@property(nonatomic) struct _NSRange rangeInDisplayText; // @synthesize rangeInDisplayText;
@property(retain, nonatomic) NSString *displayURL; // @synthesize displayURL;
@property(retain, nonatomic) NSURL *expandedURL; // @synthesize expandedURL;
@property(retain, nonatomic) NSURL *url; // @synthesize url;

@end

