/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterConcreteStatusesStream.h"

#import "NSCoding-Protocol.h"

@class TwitterAccount;

@interface TwitterAccountStream : TwitterConcreteStatusesStream <NSCoding>
{
    TwitterAccount *account;
    struct {
        unsigned int didRequestTopStatusID:1;
    } _accountStreamFlags;
}

- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)newestStatusThatIsNotMine;
- (id)definitiveStatuses:(id)arg1;
- (id)autosaveName;
- (id)_statusIDSyncKey;
- (void)noteNewTopStatusID:(id)arg1;
- (void)requestTopStatusID;
- (void)requestTopStatusIDResponse:(id)arg1 info:(id)arg2;
@property(nonatomic) TwitterAccount *account; // @synthesize account;

@end

