/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (Lists)
- (void)updateLists;
- (BOOL)isLoadingLists;
- (id)_listMatchingList:(id)arg1;
- (id)definitiveLists:(id)arg1;
- (void)listsResponse:(id)arg1 replaceList:(id *)arg2;
- (void)listsResponse:(id)arg1 info:(id)arg2;
- (void)listSubscriptionsResponse:(id)arg1 info:(id)arg2;
- (id)followingLists;
- (id)subscribedLists;
- (id)lists;
- (BOOL)_listSet:(id)arg1 containsList:(id)arg2;
- (BOOL)ownsList:(id)arg1;
- (BOOL)followsList:(id)arg1;
- (void)createList:(id)arg1 description:(id)arg2 mode:(id)arg3 callback:(id)arg4;
- (void)didCreateList:(id)arg1 info:(id)arg2;
- (void)updateList:(id)arg1 name:(id)arg2 description:(id)arg3 mode:(id)arg4 callback:(id)arg5;
- (void)didUpdateList:(id)arg1 info:(id)arg2;
- (void)deleteList:(id)arg1;
- (void)listNamed:(id)arg1 callback:(id)arg2;
- (void)listWithUsername:(id)arg1 slug:(id)arg2 callback:(id)arg3;
- (void)listResponse:(id)arg1 info:(id)arg2;
- (void)followList:(id)arg1;
- (void)unfollowList:(id)arg1;
- (void)list:(id)arg1 doesFollow:(id)arg2 callback:(id)arg3;
- (void)listDoesFollowUser:(id)arg1 info:(id)arg2;
- (void)list:(id)arg1 follow:(id)arg2;
- (void)list:(id)arg1 unfollow:(id)arg2;
@end

