/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (Push)
- (void)registerForPushWithDeviceToken:(id)arg1 enabledFor:(int)arg2;
- (void)loadPushSettings;
- (void)didReceiveSettings:(id)arg1 info:(id)arg2;
- (void)unregisterForPush;
- (void)didUnregisterForPush:(id)arg1 info:(id)arg2;
- (void)didRegisterForPush:(id)arg1 info:(id)arg2;
@end

