/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStatusStreamFilter.h"

@class NSString;

@interface TwitterStatusStreamFilterSimpleSearchFilter : TwitterStatusStreamFilter
{
    NSString *query;
}

- (BOOL)validStatus:(id)arg1;
- (void)dealloc;
@property(copy, nonatomic) NSString *query; // @synthesize query;

@end

