/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterUserList.h"

@class NSArray, NSString, TwitterAccount, TwitterUser;

@interface TwitterUserUserList : TwitterUserList
{
    TwitterAccount *account;
    TwitterUser *user;
    NSArray *users;
    NSString *cursor;
    int page;
    struct {
        unsigned int isLoading:1;
        unsigned int isAtEnd:1;
        unsigned int loadMoreLessThanMinCount:5;
    } _flags;
}

- (void)dealloc;
- (id)page;
- (id)receiveUsersCallback;
- (id)users;
- (void)_addUsers:(id)arg1;
- (void)_markAtEnd;
- (void)markAtEnd;
- (void)receiveUsers:(id)arg1 info:(id)arg2;
- (void)loadMore;
- (void)_loadMore;
@property(readonly, nonatomic) NSString *cursor; // @synthesize cursor;
@property(nonatomic) TwitterUser *user; // @synthesize user;
@property(nonatomic) TwitterAccount *account; // @synthesize account;

@end

