/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UINavigationController.h"

#import "UINavigationControllerDelegate-Protocol.h"

@class TwitterAccount;

@interface TwitterWelcomeNavigationController : UINavigationController <UINavigationControllerDelegate>
{
    id welcomeDelegate;
    TwitterAccount *account;
}

- (id)initWithAccount:(id)arg1;
- (void)dealloc;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (id)sulViewController;
- (void)navigationController:(id)arg1 willShowViewController:(id)arg2 animated:(BOOL)arg3;
- (void)backToWelcome:(id)arg1;
- (void)done:(id)arg1;
- (id)originatingTweet;
@property(nonatomic) id welcomeDelegate; // @synthesize welcomeDelegate;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

