/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "ABSwipeColumnViewControllerDelegate-Protocol.h"
#import "TweetieAddAccountViewControllerDelegate-Protocol.h"
#import "TweetieSignUpViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, TwitterAccount, TwitterComposition, UIActionSheet, UIButton, UITableView, UIView;

@interface TwitterPadSidebarViewController : UIViewController <UINavigationControllerDelegate, UITableViewDataSource, UITableViewDelegate, TweetieAddAccountViewControllerDelegate, ABSwipeColumnViewControllerDelegate, UIPopoverControllerDelegate, TweetieSignUpViewControllerDelegate, UIActionSheetDelegate>
{
    UITableView *_tableView;
    UIView *bottom;
    TwitterAccount *selectedAccount;
    int selectedItem;
    UIActionSheet *plusActionSheet;
    UIButton *compose;
    UIButton *settings;
    UIButton *plus;
    TwitterAccount *duckie;
    NSArray *categories;
    TwitterComposition *nextComp;
    struct {
        unsigned int accountDidChange:1;
        unsigned int showingPopover:1;
        unsigned int loadingSuggestions:1;
    } _flags;
}

- (id)init;
- (void)dealloc;
- (float)ab_swipeColumnWidth:(int)arg1;
- (BOOL)hasAccounts;
- (void)_updateBottomView;
- (void)loadView;
- (void)viewDidAppear:(BOOL)arg1;
- (void)longPress:(id)arg1;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)swipeColumnController:(id)arg1 willBeginInteractionOnViewController:(id)arg2;
- (void)_showCompose:(id)arg1;
- (void)compose:(id)arg1;
- (void)_compose;
- (void)plus:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)more:(id)arg1;
- (void)signin;
- (void)addAccountController:(id)arg1 didAddAccount:(id)arg2;
- (void)_firstSelect;
- (id)duckie;
- (void)setup;
- (void)swipeColumnControllerDidHideOverViewController:(id)arg1;
- (void)_dismissCompose:(id)arg1;
- (void)composeViewControllerDidDismiss:(id)arg1;
- (void)accountsDidChange;
- (void)settingsDidComplete:(id)arg1;
- (void)accountUpdate:(id)arg1;
- (void)signup;
- (void)signUpViewController:(id)arg1 didSignUpNewAccount:(id)arg2;
- (void)welcomeDidEnd:(id)arg1;
- (void)ab_columnViewController:(id)arg1 willShowOverViewController:(id)arg2 animated:(BOOL)arg3;
- (void)ab_columnViewController:(id)arg1 willHideOverViewController:(id)arg2 animated:(BOOL)arg3;
- (int)selectedAccountIndex;
- (id)accountAtIndex:(int)arg1;
- (id)firstAccount;
- (id)lastAccount;
- (BOOL)itemShouldGlow:(id)arg1;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)categories;
- (void)suggestionCategoriesResponse:(id)arg1 info:(id)arg2;
- (struct CGRect)coordinatesOfMessagesIconForAccount:(id)arg1;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)redrawAllCells;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)_setNewRoot:(Class)arg1;
- (void)selectItem:(int)arg1;
@property(retain, nonatomic) TwitterAccount *selectedAccount; // @synthesize selectedAccount;
- (void)didSelectRowAtIndexPath:(id)arg1 animated:(BOOL)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
@property(retain, nonatomic) TwitterComposition *nextComp; // @synthesize nextComp;

@end

