/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterEntityURL.h"

@class NSString, NSURL;

@interface TwitterEntityMedia : TwitterEntityURL
{
    NSString *mediaID;
    NSURL *mediaURL;
    struct CGSize thumbSize;
    struct CGSize smallSize;
    struct CGSize mediumSize;
    struct CGSize largeSize;
    int mediaType;
}

+ (void)parseEntityXML:(id)arg1 info:(id)arg2;
- (void)parseSize:(id)arg1 info:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)thumbURL;
- (id)smallURL;
- (id)mediumURL;
- (id)largeURL;
- (void)dealloc;
@property(retain, nonatomic) NSString *mediaID; // @synthesize mediaID;
@property(retain, nonatomic) NSURL *mediaURL; // @synthesize mediaURL;
@property(nonatomic) int mediaType; // @synthesize mediaType;
@property(nonatomic) struct CGSize largeSize; // @synthesize largeSize;
@property(nonatomic) struct CGSize mediumSize; // @synthesize mediumSize;
@property(nonatomic) struct CGSize thumbSize; // @synthesize thumbSize;
@property(nonatomic) struct CGSize smallSize; // @synthesize smallSize;

@end

