/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface TwitterTrendLocation : NSObject
{
    NSString *parentID;
    NSString *name;
    NSString *country;
    NSString *woeid;
}

+ (id)locationsWithJSON:(id)arg1;
+ (void)parseArrayJSON:(id)arg1 info:(id)arg2;
+ (id)globalLocation;
- (BOOL)isEqual:(id)arg1;
- (BOOL)isGlobal;
- (void)parseJSON:(id)arg1 info:(id)arg2;
- (void)dealloc;
@property(retain, nonatomic) NSString *woeid; // @synthesize woeid;
@property(retain, nonatomic) NSString *country; // @synthesize country;
@property(retain, nonatomic) NSString *name; // @synthesize name;
@property(retain, nonatomic) NSString *parentID; // @synthesize parentID;

@end

