/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStatus.h"

@interface TwitterStatus (TwitterStatusCellAdditions)
- (float)statusHeightInTableView:(id)arg1;
- (id)attributedTextWithSelectedRange:(id)arg1 baseColor:(id)arg2 linkColor:(id)arg3;
- (id)attributedTextWithSelectedRange:(id)arg1 baseColor:(id)arg2;
- (id)attributedTextWithSelectedRange:(id)arg1;
@end

