/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterCommonAppDelegate.h"

@interface TwitterCommonAppDelegate (Push)
- (void)parsePushDictionary:(id)arg1 sender:(id *)arg2 recipient:(id *)arg3 status:(id *)arg4;
- (void)updatePushToken:(id)arg1;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)refreshPushToken:(BOOL)arg1;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)handlePushPayload:(id)arg1;
@end

