/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class ABActiveTextRanges, GeoRSSPoint, NSArray, NSDate, NSMutableArray, NSString, NSURL, TwitterEntitySet, TwitterPlace, TwitterUser;

@interface TwitterStatus : NSObject
{
    NSDate *lastUpdated;
    NSString *statusID;
    NSString *originalText;
    NSString *text;
    NSString *displayText;
    NSString *source;
    ABActiveTextRanges *originalTextRanges;
    ABActiveTextRanges *activeTextRanges;
    NSArray *displayTextRanges;
    NSDate *date;
    NSDate *fakeDate;
    TwitterUser *fromUser;
    NSMutableArray *contributors;
    NSString *inReplyToStatusID;
    GeoRSSPoint *location;
    TwitterPlace *place;
    TwitterStatus *retweetedStatus;
    TwitterStatus *retweetingStatus;
    int recentRetweets;
    TwitterEntitySet *entities;
    struct {
        NSArray *links;
        NSString *sourceName;
        NSString *sourceLink;
        NSString *accessibilityText;
    } _derived;
    struct {
        unsigned short _476;
    } _height;
    struct {
        unsigned int didPrepare:1;
        unsigned int isPartialStatus:1;
        unsigned int isRead:1;
        unsigned int wasSeen:1;
        unsigned int didGlobalNotification:1;
        unsigned int containsMedia:1;
        unsigned int containsMusic:1;
        unsigned int containsRED:1;
        unsigned int contains4SQ:1;
        unsigned int mentionsLoadingAccount:1;
        unsigned int favoritedByLoadingAccount:1;
        unsigned int searchResultType:2;
        unsigned int isPromoted:1;
        unsigned int hasRecordedImpression:1;
    } _flags;
}

+ (id)statusWithDictionary:(id)arg1;
+ (id)statusWithXML:(id)arg1;
+ (id)statusWithJSON:(id)arg1;
+ (id)statusesWithXML:(id)arg1;
+ (id)promotedStatusesWithJSON:(id)arg1;
+ (id)statusesWithJSON:(id)arg1;
+ (id)statusesWithSearchJSON:(id)arg1;
@property(nonatomic) BOOL hasRecordedImpression;
@property(copy, nonatomic) NSString *originalText; // @synthesize originalText;
- (void)_parseEntities;
@property(retain, nonatomic) TwitterEntitySet *entities; // @synthesize entities;
- (void)parseDictionary:(id)arg1;
- (id)init;
- (void)dealloc;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)comparableDate;
- (int)compare:(id)arg1;
- (void)_assimilateStatus:(id)arg1;
- (void)assimilateStatus:(id)arg1;
- (int)buoyancy;
- (BOOL)isPromoted;
- (BOOL)isPopular;
- (BOOL)isNotPromoted;
@property(copy, nonatomic) NSString *text; // @synthesize text;
@property(retain, nonatomic) NSString *displayText; // @synthesize displayText;
- (void)_renderDisplayText;
@property(readonly, nonatomic) ABActiveTextRanges *originalTextRanges; // @synthesize originalTextRanges;
@property(readonly, nonatomic) ABActiveTextRanges *activeTextRanges; // @synthesize activeTextRanges;
- (void)_updateFlags;
- (void)_renderAccessibilityText;
- (void)_prepare;
@property(readonly, nonatomic) NSString *accessibilityText;
@property(nonatomic) BOOL isPartialStatus;
@property(nonatomic) BOOL isRead;
@property(nonatomic) BOOL wasSeen;
@property(readonly, nonatomic) NSURL *twitterURL;
- (BOOL)isNotADummyStatus;
@property(nonatomic) BOOL didGlobalNotification;
@property(readonly, nonatomic) BOOL containsMedia;
@property(readonly, nonatomic) BOOL isMusicLink;
@property(readonly, nonatomic) BOOL containsRED;
@property(readonly, nonatomic) BOOL contains4SQ;
@property(readonly, nonatomic) BOOL favoritedByLoadingAccount;
@property(readonly, nonatomic) BOOL mentionsLoadingAccount;
- (BOOL)isRetweet;
- (BOOL)hasSubtext;
- (BOOL)isGap;
@property(readonly, nonatomic) TwitterUser *retweetedBy;
@property(readonly, nonatomic) TwitterStatus *representedStatus;
@property(nonatomic) int searchResultType;
- (BOOL)matchesSearchString:(id)arg1;
- (id)arrayOfStringsForRanges:(id)arg1 inString:(id)arg2 chopLeading:(id)arg3;
@property(readonly, nonatomic) NSArray *links;
@property(readonly, nonatomic) NSArray *usernames;
@property(readonly, nonatomic) NSArray *hashtags;
- (void)_parseSource;
- (void)parseSourceXML:(id)arg1 info:(id)arg2;
@property(readonly, nonatomic) NSString *sourceName;
@property(readonly, nonatomic) NSString *sourceLink;
@property(readonly, nonatomic) NSString *inReplyToUsername;
@property(readonly, nonatomic) NSArray *displayTextRanges;
@property(nonatomic) int recentRetweets; // @synthesize recentRetweets;
@property(nonatomic) TwitterStatus *retweetingStatus; // @synthesize retweetingStatus;
@property(retain, nonatomic) TwitterStatus *retweetedStatus; // @synthesize retweetedStatus;
@property(retain, nonatomic) TwitterPlace *place; // @synthesize place;
@property(retain, nonatomic) GeoRSSPoint *location; // @synthesize location;
@property(copy, nonatomic) NSString *inReplyToStatusID; // @synthesize inReplyToStatusID;
@property(retain, nonatomic) NSMutableArray *contributors; // @synthesize contributors;
@property(retain, nonatomic) TwitterUser *fromUser; // @synthesize fromUser;
@property(retain, nonatomic) NSDate *fakeDate; // @synthesize fakeDate;
@property(retain, nonatomic) NSDate *date; // @synthesize date;
@property(copy, nonatomic) NSString *statusID; // @synthesize statusID;
@property(copy, nonatomic) NSString *source; // @synthesize source;
@property(retain, nonatomic) NSDate *lastUpdated; // @synthesize lastUpdated;

@end

