/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABMasterViewController.h"

@class UINavigationController;

@interface TwitterPadSplitViewController : ABMasterViewController
{
    UINavigationController *masterNavigationController;
    UINavigationController *detailNavigationController;
    BOOL isLandscape;
}

- (id)initWithMasterViewController:(id)arg1 detailViewController:(id)arg2;
- (void)dealloc;
- (float)masterWidth;
- (void)layoutSplitViews;
- (void)loadView;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (id)visibleViewControllers;
- (void)viewDidLoad;

@end

