/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSArray, NSMutableArray, TwitterEntityPromotedContent;

@interface TwitterEntitySet : NSObject <NSCoding>
{
    NSMutableArray *urls;
    NSMutableArray *mentions;
    NSMutableArray *hashtags;
    NSArray *activeRanges;
    TwitterEntityPromotedContent *promotedContent;
}

+ (id)entitiesWithDict:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (void)dealloc;
@property(retain, nonatomic) TwitterEntityPromotedContent *promotedContent; // @synthesize promotedContent;
@property(retain, nonatomic) NSMutableArray *hashtags; // @synthesize hashtags;
@property(retain, nonatomic) NSMutableArray *mentions; // @synthesize mentions;
@property(retain, nonatomic) NSMutableArray *urls; // @synthesize urls;

@end

