/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (Retweet)
- (void)retweet:(id)arg1;
- (void)retweetResponse:(id)arg1 info:(id)arg2;
- (void)retweetedByMeSinceID:(id)arg1 maxID:(id)arg2 count:(id)arg3 page:(id)arg4;
- (void)retweetedToMeSinceID:(id)arg1 maxID:(id)arg2 count:(id)arg3 page:(id)arg4;
- (void)retweetsOfMeSinceID:(id)arg1 maxID:(id)arg2 count:(id)arg3 page:(id)arg4;
@end

