/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UITableView.h"

@class NSIndexPath;

@interface TwitterPadTableView : UITableView
{
    struct {
        NSIndexPath *indexPath;
        struct CGPoint oldOffset;
        struct CGRect oldCellRect;
    } stayOnScreen;
    struct CGRect _lastFrame;
}

- (BOOL)touchesShouldCancelInContentView:(id)arg1;
- (void)_saveScrollPosition;
- (void)_restoreScrollPosition;

@end

