/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface TwitterTrend : NSObject <NSCoding>
{
    NSString *name;
    NSString *query;
    NSString *promotedTrendID;
    NSString *username;
    NSString *userID;
    BOOL hasRecordedImpression;
}

+ (id)parseLocalTrends:(id)arg1;
+ (void)parseLocalTrendsJSON:(id)arg1 info:(id)arg2;
+ (id)parseTrends:(id)arg1;
+ (void)parseTrendsJSON:(id)arg1 info:(id)arg2;
+ (void)parseOuterTrendsJSONArray:(id)arg1 info:(id)arg2;
+ (void)parseTrendsJSONArray:(id)arg1 info:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (void)parseTrendJSON:(id)arg1 info:(id)arg2;
- (void)parseTrendPromotedJSON:(id)arg1 info:(id)arg2;
- (void)parseTrendUserJSON:(id)arg1 info:(id)arg2;
- (id)description;
- (BOOL)isPromoted;
@property(nonatomic) BOOL hasRecordedImpression; // @synthesize hasRecordedImpression;
@property(retain, nonatomic) NSString *userID; // @synthesize userID;
@property(retain, nonatomic) NSString *username; // @synthesize username;
@property(retain, nonatomic) NSString *promotedTrendID; // @synthesize promotedTrendID;
@property(retain, nonatomic) NSString *query; // @synthesize query;
@property(retain, nonatomic) NSString *name; // @synthesize name;

@end

