/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitPicCompatibleImageService.h"

@interface TwitPic : TwitPicCompatibleImageService
{
}

+ (id)adjustedImageURLForURL:(id)arg1 insertPath:(id)arg2;
+ (id)fullSizeImageURLForURL:(id)arg1;
+ (id)thumbnailImageURLForURL:(id)arg1;
- (id)apiRoot;
- (id)messageParameterName;
- (id)apiKey;
- (id)apiKeyParameterName;
- (id)mediaURLResponseTag;
- (BOOL)useOAuthEcho;

@end

