/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate;

@interface TwitterApplePushDestination : NSObject
{
    int enabledFor;
    int availableLevels;
    NSDate *lastRefreshed;
}

+ (id)defaultApplePushDestination;
+ (id)applePushDestinationFromXML:(id)arg1;
- (void)parseApplePushDestinationXML:(id)arg1 info:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic) BOOL messages;
@property(nonatomic) BOOL tweets;
@property(nonatomic) BOOL mentionsFromFollowing;
@property(nonatomic) BOOL mentionsFromAll;
@property(nonatomic) BOOL mentions;
- (BOOL)isAvailable:(int)arg1;
- (BOOL)needsRefresh;
- (id)enabledSummary;
- (void)dealloc;
@property(nonatomic) int availableLevels; // @synthesize availableLevels;
@property(nonatomic) int enabledFor; // @synthesize enabledFor;
@property(retain, nonatomic) NSDate *lastRefreshed; // @synthesize lastRefreshed;

@end

