/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABRowView.h"

@class TwitterAccount;

@interface TwitterSavedSearchesRowView : ABRowView
{
    TwitterAccount *account;
}

- (void)dealloc;
- (void)savedSearchesUpdate:(id)arg1;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

