/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterPadStatusStreamViewController.h"

@class TwitterConversationStream, TwitterStatus;

@interface TwitterPadReplyChainViewController : TwitterPadStatusStreamViewController
{
    TwitterStatus *baseStatus;
    TwitterConversationStream *conversationStream;
}

- (void)dealloc;
- (id)statusStream;
- (BOOL)canPullToRefresh;
@property(retain, nonatomic) TwitterStatus *baseStatus; // @synthesize baseStatus;

@end

