/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterDummyStatus.h"

@class ABCallback, NSError;

@interface TwitterDummyErrorStatus : TwitterDummyStatus
{
    NSError *error;
    ABCallback *callback;
}

- (void)dealloc;
@property(retain, nonatomic) ABCallback *callback; // @synthesize callback;
@property(retain, nonatomic) NSError *error; // @synthesize error;

@end

