/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABStaticTableViewController.h"

@class TwitterAccount;

@interface TwitterPadListsViewController : ABStaticTableViewController
{
    TwitterAccount *account;
    id mainSection;
    int lastCount;
}

- (void)dealloc;
- (id)lists;
- (int)tableViewStyle;
- (void)_setupMainSection;
- (void)loadTableView;
- (void)viewDidLoad;
- (void)listsDidUpdate:(id)arg1;
- (void)selectList:(id)arg1;
- (BOOL)automaticallyDeselect;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

