/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABRowViewController.h"

#import "ABUITextViewDelegate-Protocol.h"
#import "TweetieEditProfileViewControllerDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class ABRowView, ABTableViewPinchPreviewController, NSArray, NSError, NSString, TwitterAccount, TwitterStatus, TwitterUser, UIActionSheet, UIButton, UIImageView;

@interface TwitterPadUserViewController : ABRowViewController <UIPopoverControllerDelegate, TweetieEditProfileViewControllerDelegate, ABUITextViewDelegate, UIActionSheetDelegate>
{
    TwitterAccount *account;
    TwitterUser *user;
    NSString *username;
    NSString *userID;
    TwitterStatus *statusContext;
    BOOL mini;
    ABTableViewPinchPreviewController *pinchPreviewController;
    UIActionSheet *actionActionSheet;
    UIActionSheet *unfollowActionSheet;
    UIButton *actionButton;
    UIImageView *avatar;
    ABRowView *relationshipInfoGroup;
    ABRowView *similarHeaderRowView;
    ABRowView *similarLoadingRowView;
    ABRowView *listsHeaderRowView;
    ABRowView *listsLoadingRowView;
    BOOL iFollowThem;
    BOOL theyFollowMe;
    struct {
        unsigned char reply;
        unsigned char dm;
        unsigned char notifications;
        unsigned char block;
        unsigned char spam;
    } buttonIndex;
    NSArray *lists;
    NSError *error;
    struct {
        unsigned int loading:1;
        unsigned int errorLoading:1;
        unsigned int loadingFollowStatus:1;
        unsigned int errorLoadingFollowStatus:1;
        unsigned int didLoadFollowStatus:1;
        unsigned int loadingLists:1;
        unsigned int errorLoadingLists:1;
        unsigned int didLoadLists:1;
        unsigned int loadingRecs:1;
        unsigned int didLoadRecs:1;
        unsigned int errorLoadingRecs:1;
    } _flags;
}

- (void)dealloc;
- (void)userResponse:(id)arg1 info:(id)arg2;
- (BOOL)userIsLoaded;
- (BOOL)miniHeader;
- (void)_loadUser;
- (void)_updateAvatar;
- (void)userDidUpdate:(id)arg1;
- (id)attributedBio;
- (id)originatingTweet;
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)arg1;
- (BOOL)isMe;
- (void)_loadFollowState;
- (void)_updateFollowButton;
- (void)followStatus:(id)arg1 info:(id)arg2;
- (void)_loadLists;
- (void)listsResponse:(id)arg1 info:(id)arg2;
- (void)_loadSimilar;
- (void)similarResponse:(id)arg1 info:(id)arg2;
- (void)selectRecommendedUser:(id)arg1;
- (void)selectList:(id)arg1;
- (float)contentHeight;
- (id)moreInfoGroup;
- (void)loadRowView;
- (void)retry:(id)arg1;
- (void)_didDismissPinch_pushColumn:(id)arg1 info:(id)arg2;
- (void)_pushColumn:(id)arg1;
- (void)moreInfo:(id)arg1;
- (void)viewWeb:(id)arg1;
- (void)profilePic:(id)arg1;
- (id)activeRangesForTextRenderer:(id)arg1;
- (void)textView:(id)arg1 didTapActiveRange:(id)arg2;
- (void)rowView:(id)arg1 didSelectChildRow:(id)arg2;
- (void)follow:(id)arg1;
- (void)unfollow:(id)arg1;
- (void)action:(id)arg1;
- (void)_showPopover:(id)arg1 from:(id)arg2;
- (void)popoverControllerDidDismissPopover:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)reallyBlock:(id)arg1 info:(id)arg2;
- (void)tweets:(id)arg1;
- (void)mentions:(id)arg1;
- (void)favorites:(id)arg1;
- (void)followers:(id)arg1;
- (void)following:(id)arg1;
- (void)editProfile:(id)arg1;
- (void)editProfileControllerWillCancel:(id)arg1;
- (void)editProfileControllerDidSave:(id)arg1;
- (void)ab_didPopDetails;
@property(nonatomic) ABTableViewPinchPreviewController *pinchPreviewController; // @synthesize pinchPreviewController;
@property(nonatomic) BOOL mini; // @synthesize mini;
@property(retain, nonatomic) TwitterStatus *statusContext; // @synthesize statusContext;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;
@property(retain, nonatomic) NSString *userID; // @synthesize userID;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;
@property(retain, nonatomic) NSString *username; // @synthesize username;

@end

