/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABTableViewCellView.h"

#import "ABUITextRendererDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class ABUITextRenderer, TwitterStatus, TwitterStatusCell, UIButton;

@interface TwitterStatusCellView : ABTableViewCellView <UIActionSheetDelegate, ABUITextRendererDelegate>
{
    ABUITextRenderer *renderer;
    UIButton *avatarButton;
}

+ (void)initialize;
- (id)initWithFrame:(struct CGRect)arg1 cell:(id)arg2;
- (void)dealloc;
- (id)hitStringForRangeValue:(id)arg1;
- (BOOL)canBecomeFirstResponder;
@property(readonly, nonatomic) TwitterStatusCell *statusCell;
@property(readonly, nonatomic) TwitterStatus *status;
- (void)longPress:(id)arg1;
- (id)activeRanges;
- (id)activeRangesForTextRenderer:(id)arg1;
@property(readonly, nonatomic) ABUITextRenderer *renderer;
- (struct CGRect)textRect;
- (void)displayDate:(id *)arg1 alt:(id *)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)tapAvatar:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;

@end

