/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterComposition.h"

@interface TwitterComposition (Additions)
+ (id)replyAllTextForStatus:(id)arg1 fromAccount:(id)arg2;
+ (id)quoteTweetTextForStatus:(id)arg1 fromAccount:(id)arg2;
+ (struct _NSRange)initialSelectedRangeForComposeText:(id)arg1;
@end

