/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (Trends)
- (BOOL)_ignoreLocalTrends;
- (void)updateTrends;
- (void)_endTrendLocationGPSUpdates;
- (void)_updateTrends;
- (void)_findTrendLocationsFrom:(id)arg1;
- (void)detectTrendLocation;
- (void)currentLocationResponse:(id)arg1;
- (void)trendLocationsResponse:(id)arg1 info:(id)arg2;
- (id)trends;
- (BOOL)trendsNeedRefresh;
- (void)trendsResponse:(id)arg1 info:(id)arg2;
- (void)updateSULCategories;
- (id)sulCategories;
- (void)sulCategoriesResponse:(id)arg1 info:(id)arg2;
@end

