/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (Uniquification)
- (id)cachedUserWithID:(id)arg1;
- (id)cachedUserWithUsername:(id)arg1;
- (id)cachedStatusWithID:(id)arg1;
- (id)cachedDirectMessageWithID:(id)arg1;
- (id)definitiveUser:(id)arg1;
- (id)definitiveStatus:(id)arg1;
- (id)definitiveMessage:(id)arg1;
- (id)definitiveUsers:(id)arg1;
- (id)definitiveStatuses:(id)arg1;
- (id)definitiveDirectMessages:(id)arg1;
- (id)cachedUsers;
- (id)usersStartingWith:(id)arg1;
- (id)cachedStatuses;
@end

