/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class ABHTTPRequest, NSDate, NSString, TwitterAccount, TwitterSearchStream;

@interface TwitterSearch : NSObject <NSCoding>
{
    TwitterAccount *account;
    NSString *searchID;
    NSString *name;
    NSDate *createdAt;
    TwitterSearchStream *stream;
    ABHTTPRequest *liveStream;
    float liveSearchStreamReconnectDelay;
    BOOL droppedLastLiveStreamConnection;
    BOOL supportsLiveStream;
    struct {
        unsigned int queryChanged:1;
    } _flags;
}

+ (id)searchQuery:(id)arg1 account:(id)arg2 via:(id)arg3;
+ (id)searchQuery:(id)arg1 account:(id)arg2;
+ (id)savedSearchesWithXML:(id)arg1;
+ (void)parseSavedSearchesXML:(id)arg1 info:(id)arg2;
+ (id)savedSearchWithXML:(id)arg1;
+ (id)restPrefixOperators;
- (void)setSource:(id)arg1;
- (BOOL)isConnectedToLiveSearchStream;
- (void)loadNewerForced:(BOOL)arg1;
- (BOOL)supportsLiveStream;
- (void)openLiveSearchStream;
- (void)didDropStream:(id)arg1 info:(id)arg2;
- (void)_scheduleSearchStreamReconnectAfterDelay:(float)arg1;
- (void)_cancelSearchStreamReconnect;
- (void)_reopenStream;
- (void)didReceiveStreamSearchResult:(id)arg1 info:(id)arg2;
- (void)closeLiveSearchStream;
- (void)parseSavedSearchXML:(id)arg1 info:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) TwitterSearchStream *stream;
@property(copy, nonatomic) NSString *query;
@property(copy, nonatomic) NSString *geocodeQuery;
- (id)displayName;
@property(nonatomic) TwitterAccount *account; // @synthesize account;
- (void)dealloc;
@property(retain, nonatomic) NSDate *createdAt; // @synthesize createdAt;
@property(copy, nonatomic) NSString *searchID; // @synthesize searchID;
@property(copy, nonatomic) NSString *name; // @synthesize name;

@end

