/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (UserMethods)
+ (id)usersLookupParamDataWithEmails:(id)arg1 phones:(id)arg2;
- (void)friendsForUserID:(id)arg1 cursor:(id)arg2;
- (void)friendsForUsername:(id)arg1 cursor:(id)arg2;
- (void)followersForUserID:(id)arg1 cursor:(id)arg2;
- (void)userWithID:(id)arg1;
- (void)userWithUsername:(id)arg1;
- (void)searchUsers:(id)arg1 count:(id)arg2 page:(id)arg3;
- (void)recommendationsForUsername:(id)arg1 limit:(id)arg2;
- (void)recommendationsForUserID:(id)arg1 limit:(id)arg2;
- (void)userRecommendationsResponse:(id)arg1 info:(id)arg2;
- (void)suggestionCategoriesForLanguage:(id)arg1 country:(id)arg2;
- (void)suggestionCategoriesResponse:(id)arg1 info:(id)arg2;
- (void)suggestedUsersForCategory:(id)arg1;
- (void)suggestedUsersForCategoryResponse:(id)arg1 info:(id)arg2;
- (void)usersWithEmails:(id)arg1 phones:(id)arg2;
- (void)usersLookupResponse:(id)arg1 info:(id)arg2;
- (void)parseUsersLookupJSON:(id)arg1 info:(id)arg2;
- (void)parseSULUsersJSON:(id)arg1 info:(id)arg2;
@end

