/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (UserStream)
- (id)openUserStream:(id)arg1 track:(id)arg2;
- (void)didReceiveUserStreamJSON:(id)arg1 info:(id)arg2;
- (void)handleUserStreamEvent:(id)arg1 callback:(id)arg2;
- (void)didCloseStream:(id)arg1 info:(id)arg2;
@end

