/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAPI.h"

@interface TwitterAPI (StatusMethods)
- (void)publicTimeline;
- (void)friendsTimelineSinceID:(id)arg1 maxID:(id)arg2 count:(id)arg3 page:(id)arg4;
- (void)repliesSinceID:(id)arg1 maxID:(id)arg2 count:(id)arg3 page:(id)arg4;
- (void)userTimelineForUserID:(id)arg1 sinceID:(id)arg2 maxID:(id)arg3 count:(id)arg4 page:(id)arg5;
- (void)userTimelineForUsername:(id)arg1 sinceID:(id)arg2 maxID:(id)arg3 count:(id)arg4 page:(id)arg5;
- (void)statusWithID:(id)arg1;
- (void)_update:(id)arg1 inReplyToStatusID:(id)arg2 geotag:(BOOL)arg3 latitude:(double)arg4 longitude:(double)arg5;
- (void)updateWithComposition:(id)arg1;
- (void)update:(id)arg1 inReplyToStatusID:(id)arg2 latitude:(double)arg3 longitude:(double)arg4;
- (void)update:(id)arg1 inReplyToStatusID:(id)arg2;
- (void)destroyStatus:(id)arg1;
@end

