/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSDate;

@interface TwitterSettings : NSObject
{
    BOOL geoEnabled;
    NSDate *lastUpdated;
}

+ (id)settingsWithXML:(id)arg1;
- (void)parseSettingsXML:(id)arg1 info:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) NSDate *lastUpdated; // @synthesize lastUpdated;
@property(nonatomic) BOOL geoEnabled; // @synthesize geoEnabled;

@end

