/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStatus.h"

@class NSString;

@interface TwitterDummyStatus : TwitterStatus
{
    NSString *messageText;
}

- (BOOL)isNotADummyStatus;
- (void)dealloc;
@property(retain, nonatomic) NSString *messageText; // @synthesize messageText;

@end

