/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStatus.h"

@interface TwitterStatus (XML)
+ (void)parseStatusesXML:(id)arg1 info:(id)arg2;
- (void)parseStatusXML:(id)arg1 info:(id)arg2; //IMPORTANTZ
@end

