/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterCommonAppDelegate.h"

#import "UIAlertViewDelegate-Protocol.h"

@class ABSwipeColumnViewController, TwitterPadSidebarViewController, UIWindow;

@interface TwitterPadAppDelegate : TwitterCommonAppDelegate <UIAlertViewDelegate>
{
    UIWindow *window;
    UIWindow *statusBarWindow;
    ABSwipeColumnViewController *rootViewController;
    TwitterPadSidebarViewController *sidebar;
    int expect;
    UIWindow *blackout;
}

- (void)dealloc;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)_handleOpenURL:(id)arg1;
- (void)application:(id)arg1 willChangeStatusBarOrientation:(int)arg2 duration:(double)arg3;
- (void)_endStatusBarChange;
- (void)_saveState;
- (id)rootView;
- (void)tapStatusBar:(struct CGPoint)arg1;
@property(readonly, nonatomic) TwitterPadSidebarViewController *sidebar; // @synthesize sidebar;
@property(readonly, nonatomic) ABSwipeColumnViewController *rootViewController; // @synthesize rootViewController;

@end

