/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABRowViewController.h"

#import "SearchRowViewDelegate-Protocol.h"
#import "TopTweetsRailViewDelegate-Protocol.h"

@class ABRowView, TopTweetsRailView, TwitterAccount, TwitterSavedSearchesRowView, TwitterTrendsRowView;

@interface TwitterPadSearchesViewController : ABRowViewController <TopTweetsRailViewDelegate, SearchRowViewDelegate>
{
    TwitterAccount *account;
    ABRowView *everythingContainer;
    TwitterSavedSearchesRowView *savedSearchesRowView;
    TopTweetsRailView *topTweetsRailView;
    TwitterTrendsRowView *trendsRowView;
}

- (void)dealloc;
- (BOOL)loggedOutMode;
- (void)addTopSectionTo:(id)arg1;
- (void)_addTrends;
- (void)_addTopTweets;
- (void)loadRowView;
- (void)rowView:(id)arg1 didSelectChildRow:(id)arg2;
- (void)ab_didPopDetails;
- (void)viewWillAppear:(BOOL)arg1;
- (void)topTweetsRailView:(id)arg1 selectedTweet:(id)arg2;
- (void)topTweetsRailViewShowAllTopTweets:(id)arg1;
- (void)topTweetsDidUpdate:(id)arg1;
- (void)searchRowViewDidBegin:(id)arg1;
- (void)searchRowViewDidCancel:(id)arg1;
- (void)searchFor:(id)arg1;
- (void)gotoUsername:(id)arg1;
- (void)searchNearby:(id)arg1 coordinates:(CDStruct_2c43369c)arg2;
- (void)gotoUser:(id)arg1;
- (void)goToPromotedTOSViaTrend:(id)arg1;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

