/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIViewController.h"

#import "ABVerticalFlowViewDelegate-Protocol.h"

@class ABVerticalFlowView, NSArray, NSURL, TwitterAccount, TwitterStatus;

@interface TwitterPadTweetMediaViewController : UIViewController <ABVerticalFlowViewDelegate>
{
    TwitterAccount *account;
    TwitterStatus *status;
    NSURL *selectedURL;
    NSArray *_mediaURLs;
    ABVerticalFlowView *_flowView;
    int nextThumbIndex;
}

- (void)dealloc;
- (id)mediaURLs;
- (void)loadView;
- (void)loadNextThumb;
- (void)imageResponse:(id)arg1 info:(id)arg2;
- (void)viewDidAppear:(BOOL)arg1;
@property(retain, nonatomic) NSURL *selectedURL; // @synthesize selectedURL;
- (int)verticalFlowViewNumberOfItems:(id)arg1;
- (id)verticalFlowViewFullscreenContainer:(id)arg1;
@property(retain, nonatomic) TwitterStatus *status; // @synthesize status;
@property(retain, nonatomic) TwitterAccount *account; // @synthesize account;

@end

