/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (UserStream)
- (void)_scheduleReconnectAfterDelay:(float)arg1;
- (void)_cancelUserStreamReconnect;
- (BOOL)isConnectedToUserStream;
- (void)_reopenStream;
- (void)openUserStream;
- (void)closeUserStream;
- (void)successfullyConnected;
- (void)_handleUserStreamStatus:(id)arg1;
- (void)didReceiveStreamObject:(id)arg1 info:(id)arg2;
- (void)didCheckReplyInUserStream:(id)arg1 info:(id)arg2;
- (void)didDropStream:(id)arg1 info:(id)arg2;
- (void)_checkUserStreamHealth;
@end

