/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterPadStatusStreamViewController.h"

@class TwitterSearch, UIActionSheet, UIBarButtonItem;

@interface TwitterPadSearchResultsViewController : TwitterPadStatusStreamViewController
{
    TwitterSearch *search;
    UIBarButtonItem *saveSearch;
    UIActionSheet *_saveSearchSheet;
}

- (void)dealloc;
- (id)statusStream;
- (void)viewDidLoad;
- (void)viewedMostRecent:(id)arg1;
- (BOOL)isHashtag;
- (BOOL)showToolbar;
- (void)_noteSavedSearchesDidChange;
- (BOOL)isSavedSearch;
- (void)_updateSaveSearchButton;
- (void)saveSearch:(id)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (id)toolbarView;
@property(retain, nonatomic) TwitterSearch *search; // @synthesize search;

@end

