/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSKeyedUnarchiverDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"

@interface TwitterCommonAppDelegate : NSObject <UIApplicationDelegate, NSKeyedUnarchiverDelegate>
{
    BOOL handlingURL;
}

+ (BOOL)isLoadingViaPush;
+ (void)setIsLoadingViaPush:(BOOL)arg1;
- (void)dealloc;
- (id)applicationStateFile;
- (id)applicationState;
- (void)saveApplicationState:(id)arg1;
- (id)reloadApplicationState;
- (void)firstLaunch;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)handleLaunchOptions:(id)arg1;
- (void)_handleOpenURL:(id)arg1;
- (void)handleOpenURL:(id)arg1;
- (BOOL)application:(id)arg1 handleOpenURL:(id)arg2;
- (BOOL)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (void)_saveState;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationDidReceiveMemoryWarning:(id)arg1;
- (void)applicationStateDidReload;
- (void)purgeCaches;
- (void)beginNetworkActivity:(id)arg1;
- (void)endNetworkActivity:(id)arg1;
- (void)errorPostingNotification:(id)arg1;
- (void)_logLoadedViewController;
- (void)_resetImpressionLog;

@end

