/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterStatus.h"

@class FusionAd;

@interface TwitterDummyAdStatus : TwitterStatus
{
    FusionAd *ad;
}

- (id)init;
- (void)dealloc;
@property(readonly, nonatomic) FusionAd *ad; // @synthesize ad;

@end

