/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString, TwitterAccount;

@interface TwitterListList : NSObject
{
    TwitterAccount *account;
    NSString *nextCursor;
    NSString *previousCursor;
    NSArray *lists;
    struct {
        unsigned int loadingNext:1;
    } _listListFlags;
}

- (void)dealloc;
@property(copy, nonatomic) NSArray *lists; // @synthesize lists;
- (void)loadNextOnRequester:(id)arg1;
- (void)loadNext;
- (void)didLoadNextListList:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSString *previousCursor; // @synthesize previousCursor;
@property(retain, nonatomic) NSString *nextCursor; // @synthesize nextCursor;
@property(nonatomic) TwitterAccount *account; // @synthesize account;

@end

