/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterDirectMessagesStream.h"

@interface TwitterSentDirectMessagesStream : TwitterDirectMessagesStream
{
}

- (void)_loadNewer;
- (void)_loadOlder;
- (BOOL)forceReadBit;

@end

