/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABMutableAttributedArray.h"

@class NSString;

@interface TwitterPaginatedResults : ABMutableAttributedArray
{
}

@property(retain, nonatomic) NSString *nextCursor;
@property(retain, nonatomic) NSString *previousCursor;
- (BOOL)isAtEnd;

@end

