/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABRowView.h"

@class TwitterUser;

@interface TwitterPadUserRowView : ABRowView
{
    TwitterUser *user;
}

- (id)initWithTwitterUser:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) TwitterUser *user; // @synthesize user;
- (void)userDidUpdate:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

