/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "ABPlainRowCell.h"

@class TweetiePromotedButton, TwitterTrend;

@interface TwitterPadTrendRowCell : ABPlainRowCell
{
    TwitterTrend *trend;
    TweetiePromotedButton *promotedLabel;
}

- (id)init;
- (void)didClickPromotedLabel:(id)arg1;
@property(retain, nonatomic) TwitterTrend *trend; // @synthesize trend;
- (void)layoutSubviews;
- (void)dealloc;

@end

