/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@class ABCallback, GeoRSSPoint, NSMutableArray, NSString, TwitterPlace, TwitterStatus, TwitterUser;

@interface TwitterComposition : NSObject <NSCoding>
{
    NSString *text;
    TwitterUser *replyToUser;
    TwitterUser *directMessageUser;
    TwitterStatus *replyToStatus;
    BOOL isDraft;
    NSMutableArray *attachments;
    GeoRSSPoint *geotag;
    TwitterPlace *place;
    NSMutableArray *placeEntities;
    ABCallback *didSendCallback;
    unsigned int backgroundIdentifier;
    BOOL dirty;
    BOOL hadFailedSend;
    struct {
        unsigned int didBeginSend:1;
        unsigned int isSending:1;
    } _flags;
    int urlLength;
}

- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
@property(readonly, nonatomic) BOOL isSending;
- (void)_beginSend;
- (void)_endSend:(BOOL)arg1;
@property(retain, nonatomic) TwitterUser *replyToUser; // @synthesize replyToUser;
@property(readonly, nonatomic) int compositionType;
- (BOOL)isGeoTaggable;
- (BOOL)isDirectMessage;
- (BOOL)isPublicReply;
- (void)_addUsernamePrefixIfNeeded;
- (BOOL)_removePrefix:(id)arg1;
- (void)_removeUsernamePrefix;
- (void)switchToPublicReply;
- (void)switchToDirectMessage;
- (int)characterLimit;
@property(nonatomic) int urlLength; // @synthesize urlLength;
- (int)attachmentsLength;
- (int)remainingCharacters;
- (BOOL)isWorthSaving;
- (BOOL)isWorthSending;
- (BOOL)containsMoreThanMentions;
- (BOOL)isDocumentEdited;
- (id)appropriateTitle;
- (id)appropriateDraftTitle;
- (id)appropriateImage;
- (BOOL)matchesSearchString:(id)arg1;
- (void)addAttachment:(id)arg1;
- (void)removeAttachment:(id)arg1;
- (id)attachments;
- (BOOL)hasRoomForAnotherAttachment;
- (void)willDiscard;
- (id)textWithAttachments;
- (void)_sendFromAccount:(id)arg1;
- (void)didSend:(id)arg1;
- (void)errorSending;
- (int)numberOfAttachmentsPendingUpload;
- (BOOL)hasPendingAttachments;
- (void)sendFromAccount:(id)arg1;
@property(readonly, nonatomic) float sendProgress;
- (void)didUploadAttachment:(id)arg1 info:(id)arg2;
- (id)displayName;
- (id)fileURL;
- (void)trimEntities;
- (int)_updatedIndex:(int)arg1 range:(struct _NSRange)arg2 newText:(id)arg3;
- (void)reindexEntitiesWithRange:(struct _NSRange)arg1 replacementText:(id)arg2;
@property(nonatomic) BOOL hadFailedSend; // @synthesize hadFailedSend;
@property(nonatomic) BOOL dirty; // @synthesize dirty;
@property(retain, nonatomic) ABCallback *didSendCallback; // @synthesize didSendCallback;
@property(retain, nonatomic) NSMutableArray *placeEntities; // @synthesize placeEntities;
@property(retain, nonatomic) TwitterPlace *place; // @synthesize place;
@property(retain, nonatomic) GeoRSSPoint *geotag; // @synthesize geotag;
@property(nonatomic) BOOL isDraft; // @synthesize isDraft;
@property(copy, nonatomic) NSString *text; // @synthesize text;
@property(retain, nonatomic) TwitterUser *directMessageUser; // @synthesize directMessageUser;
@property(retain, nonatomic) TwitterStatus *replyToStatus; // @synthesize replyToStatus;

@end

