/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitterAccount.h"

@interface TwitterAccount (Push)
- (void)registerForPushWithDeviceToken:(id)arg1;
- (void)unregisterForPush;
- (void)didRegisterForPush:(id)arg1 info:(id)arg2;
@end

