/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIBarButtonItem.h"

@interface UIBarButtonItem (ABAdditions)
+ (id)miniGap:(float)arg1;
+ (id)flexibleSpace;
+ (id)fixedSpace;
+ (id)backBarButtonItemWithTitle:(id)arg1;
+ (id)backBarButtonItemWithImage:(id)arg1;
@end

