/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIColor.h"

@interface UIColor (ABAdditions)
+ (id)linkColor;
+ (id)blueLabelColor;
+ (id)tableFooterLabelColor;
+ (id)graphiteColor;
+ (id)darkBlueLabelColor;
+ (id)grayDividerColor;
+ (id)blueDateColor;
+ (id)fadedBlueDateColor;
+ (id)hashBackgroundColor;
+ (id)lightHashBackgroundColor;
+ (id)conversationBackgroundColor;
+ (id)mailTableViewBackgroundColor;
+ (id)embeddedSearchBarTintColor;
+ (id)flatPinstripesShadeColor;
+ (id)projectREDColor;
+ (id)iPadSteel;
+ (id)selectedGradientTopBlue;
+ (id)selectedGradientBottomBlue;
@end

