/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIImage.h"

@interface UIImage (ABAdditions)
+ (id)_ab_imageFromBitmapContext:(struct CGContext *)arg1;
- (id)_ab_imageByFindingEdges;
- (id)_ab_gradientShadowImage;
- (id)_ab_squareImageWithHeight:(int)arg1;
- (id)_ab_fixOrientationConstrainToSize:(int)arg1 compress:(float)arg2;
@end

