/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UINavigationController.h"

@interface UINavigationController (ABAdditions)
- (id)_ab_setupTransition:(id)arg1 subtype:(id)arg2 onLayer:(id)arg3;
- (void)releaseVC:(id)arg1;
- (void)replaceTopViewController:(id)arg1 animation:(id)arg2 subtype:(id)arg3;
- (void)replaceTopViewController:(id)arg1 animated:(BOOL)arg2;
- (void)replaceTopViewController:(id)arg1 contentViewTransition:(int)arg2 duration:(double)arg3;
- (void)replaceTopViewControllerDidStop:(id)arg1 finished:(id)arg2 context:(id)arg3;
- (void)replaceModalViewController:(id)arg1 animated:(BOOL)arg2;
- (void)presentModalViewControllerInANavigationController:(id)arg1 animated:(BOOL)arg2;
- (void)resetToDefaultStyleAnimated:(BOOL)arg1;
@end

