/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIView.h"

@interface UIView (ABAdditions)
- (void)ab_pixelAlignFrame;
- (id)firstViewOfClass:(Class)arg1;
- (id)firstSuperviewOfClass:(Class)arg1;
@property(nonatomic) float left;
@property(nonatomic) float top;
@property(nonatomic) float right;
@property(nonatomic) float bottom;
@property(nonatomic) float centerX;
@property(nonatomic) float centerY;
@property(nonatomic) float width;
@property(nonatomic) float height;
@end

