/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIWebView.h"

@class UIScrollView;

@interface UIWebView (ABAdditions)
@property(readonly, nonatomic) UIScrollView *_ab_scrollView;
- (void)_ab_killShadows;
@end

