/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface URLShorteningService : NSObject
{
}

+ (id)shortener;
+ (id)currentService;
+ (BOOL)isShortURLString:(id)arg1;
+ (void)shortenURLString:(id)arg1 callback:(id)arg2;
+ (void)shortenURLString:(id)arg1 fromAccount:(id)arg2 callback:(id)arg3;
+ (void)expandURLString:(id)arg1 callback:(id)arg2;
+ (void)expandURLResponse:(id)arg1 info:(id)arg2;
+ (void)parseLongURLPleaseJSON:(id)arg1 info:(id)arg2;
- (void)shortenURLString:(id)arg1 callback:(id)arg2;
- (void)shortenURLString:(id)arg1 fromAccount:(id)arg2 callback:(id)arg3;
- (void)expandURLString:(id)arg1 callback:(id)arg2;

@end

