/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "TwitPicCompatibleImageService.h"

@interface Vidly : TwitPicCompatibleImageService
{
}

- (id)apiRoot;
- (id)mediaParameterName;
- (id)mediaURLResponseTag;
- (id)messageParameterName;
- (BOOL)useBasicAuth;

@end

