/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@class NSError, NSString;

@interface WhatTheTrend : NSObject
{
    NSString *term;
    NSString *definition;
    NSError *error;
}

+ (void)define:(id)arg1 callback:(id)arg2;
+ (id)locale;
+ (void)define:(id)arg1 as:(id)arg2 username:(id)arg3 userID:(id)arg4;
+ (void)defineDefinitionResponse:(id)arg1 info:(id)arg2;
- (void)dealloc;
- (void)defineResponse:(id)arg1 info:(id)arg2;
- (void)parseJSON:(id)arg1 info:(id)arg2;
- (void)parseTrend:(id)arg1 info:(id)arg2;
- (void)parseBlurb:(id)arg1 info:(id)arg2;
@property(retain, nonatomic) NSError *error; // @synthesize error;
@property(copy, nonatomic) NSString *definition; // @synthesize definition;
@property(copy, nonatomic) NSString *term; // @synthesize term;

@end

