/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "NSObject.h"

@interface YAJLGen : NSObject
{
    struct yajl_gen_t *gen_;
    unsigned int genOptions_;
}

- (id)init;
- (id)initWithGenOptions:(unsigned int)arg1 indentString:(id)arg2;
- (void)dealloc;
- (void)object:(id)arg1;
- (void)null;
- (void)_Bool:(BOOL)arg1;
- (void)number:(id)arg1;
- (void)string:(id)arg1;
- (void)startDictionary;
- (void)endDictionary;
- (void)startArray;
- (void)endArray;
- (void)clear;
- (id)buffer;

@end

